import { useCallback, useEffect, useLayoutEffect, useMemo, useRef, useState } from 'react'
import type { FormEvent, ReactNode } from 'react'
import { Search, SlidersHorizontal, X, Sun, Moon, Monitor, Heart, Phone, MapPin, ArrowRight, ArrowLeft, ChevronLeft, ChevronRight, Check, Plus, Share2, Maximize2, Scale, Mail, Clock, Menu, CarFront, Fuel, Gauge, CalendarDays, CircleHelp } from 'lucide-react'
import Lenis from 'lenis'
import { Wordmark } from './Wordmark'
import { asset, carTitle, cashURL, driveLabel, filterCars, filterNames, fuelLabel, keys, mileage, price, sellURL } from './data'
import type { Car, FilterKey } from './data'

const isTouch=()=>navigator.maxTouchPoints>0||'ontouchstart' in window
function readParams(){const p=new URLSearchParams(location.search);for(const k of ['min','max','yearMin','yearMax','kmMax','limit']){if(p.has(k)&&!/^\d{1,9}$/.test(p.get(k)||''))p.delete(k)}return p}
function readList(key:string):string[]{try{const v=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(v)?[...new Set(v.filter(x=>typeof x==='string'))].slice(0,key==='bg-compare'?3:100):[]}catch{return []}}
function usePersistentList(key:string){const [list,setList]=useState(()=>readList(key));useEffect(()=>{try{localStorage.setItem(key,JSON.stringify(list))}catch{/* Storage is optional. */}},[key,list]);return [list,setList] as const}
function useTheme(){
 const [preference,setPreference]=useState(()=>{try{const p=localStorage.getItem('bg-theme');return p==='light'||p==='dark'?p:'system'}catch{return 'system'}})
 const [darkSystem,setDarkSystem]=useState(()=>matchMedia('(prefers-color-scheme: dark)').matches)
 const theme=preference==='system'?(darkSystem?'dark':'light'):preference
 useEffect(()=>{const m=matchMedia('(prefers-color-scheme: dark)');const fn=()=>setDarkSystem(m.matches);m.addEventListener('change',fn);const sync=(e:StorageEvent)=>{if(e.key==='bg-theme')setPreference(e.newValue==='dark'||e.newValue==='light'?e.newValue:'system')};window.addEventListener('storage',sync);return()=>{m.removeEventListener('change',fn);window.removeEventListener('storage',sync)}},[])
 useLayoutEffect(()=>{document.documentElement.dataset.theme=theme;document.documentElement.style.colorScheme=theme;document.querySelector('meta[name="theme-color"]')?.setAttribute('content',theme==='dark'?'#0A0C10':'#F5F6F7')},[theme])
 function choose(p:string){setPreference(p);try{localStorage.setItem('bg-theme',p)}catch{/* Keep working without storage. */}}
 return {theme,preference,choose}
}
function Modal({title,children,onClose,wide=false}:{title:string;children:ReactNode;onClose:()=>void;wide?:boolean}){
 const ref=useRef<HTMLDialogElement>(null)
 useLayoutEffect(()=>{
  const d=ref.current!;const before=document.activeElement as HTMLElement;const y=scrollY
  d.showModal();document.body.style.position='fixed';document.body.style.top=`-${y}px`;document.body.style.width='100%';document.documentElement.dataset.dialog='true'
  return()=>{d.close();document.body.style.position='';document.body.style.top='';document.body.style.width='';delete document.documentElement.dataset.dialog;window.scrollTo({top:y,behavior:'instant'});if(before?.isConnected)before.focus({preventScroll:true})}
 },[])
 return <dialog ref={ref} className={`bg-dialog ${wide?'bg-dialog-wide':''}`} aria-label={title} onCancel={e=>{e.preventDefault();onClose()}} onClick={e=>{if(e.target===e.currentTarget)onClose()}}><div className="bg-dialog-inner"><div className="bg-dialog-head"><h2>{title}</h2><button className="bg-icon" aria-label="Loka glugga" onClick={onClose} autoFocus><X aria-hidden="true"/></button></div>{children}</div></dialog>
}
function VehicleImage({src,alt,eager=false,className=''}:{src:string;alt:string;eager?:boolean;className?:string}){
 const [failed,setFailed]=useState(false)
 useEffect(()=>setFailed(false),[src])
 return failed?<div className={`bg-image-fallback ${className}`}><CarFront aria-hidden="true"/><span>Mynd ekki tiltæk</span></div>:<img className={className} src={asset(src)} alt={alt} width="1280" height="1024" loading={eager?'eager':'lazy'} fetchPriority={eager?'high':undefined} decoding="async" onError={()=>setFailed(true)}/>
}
function Snapshot(){return <p className="bg-snapshot"><span/>Frumgerð · Söluskrá frá 30. september 2026. Staðfestu verð og framboð hjá Bílagallerí.</p>}
function Facts({car}:{car:Car}){return <dl className="bg-facts"><div><dt><CalendarDays aria-hidden="true"/>Nýskráning</dt><dd>{car.registration||'Ekki tilgreint'}</dd></div><div><dt><Gauge aria-hidden="true"/>Akstur</dt><dd>{mileage(car)}</dd></div><div><dt><Fuel aria-hidden="true"/>Orkugjafi</dt><dd>{fuelLabel(car)}</dd></div><div><dt><CarFront aria-hidden="true"/>Skipting</dt><dd>{car.transmission||'Ekki tilgreint'}</dd></div></dl>}
function Price({car,large=false}:{car:Car;large?:boolean}){return <div className={`bg-price ${large?'bg-price-large':''}`}><strong>{price(car.price)}</strong>{car.priceNote&&<span>{car.priceNote}</span>}</div>}

export default function Page(){
 const [params,setParams]=useState(readParams)
 const [cars,setCars]=useState<Car[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState(false);const [attempt,setAttempt]=useState(0)
 const [saved,setSaved]=usePersistentList('bg-saved');const [compare,setCompare]=usePersistentList('bg-compare')
 const {theme,preference,choose}=useTheme();const [modal,setModal]=useState<'menu'|'filters'|'theme'|'enquiry'|'gallery'|null>(null)
 const [notice,setNotice]=useState('');const [galleryIndex,setGalleryIndex]=useState(0);const [heroIndex,setHeroIndex]=useState(0)
 const rootRef=useRef<HTMLDivElement>(null);const restoration=useRef<number|null>(null);const lenisRef=useRef<Lenis|null>(null)
 const view=params.get('view')||'home';const car=cars.find(c=>c.id===params.get('car'))
 const notify=useCallback((message:string)=>setNotice(message),[])
 useEffect(()=>{if(!notice)return;const id=setTimeout(()=>setNotice(''),4000);return()=>clearTimeout(id)},[notice])
 useEffect(()=>{const abort=new AbortController();setLoading(true);setError(false);fetch(asset('./inventory.json'),{signal:abort.signal}).then(r=>{if(!r.ok)throw Error('inventory');return r.json()}).then(data=>{if(!Array.isArray(data)||!data.length)throw Error('inventory');setCars(data);setLoading(false)}).catch(e=>{if(e.name!=='AbortError'){setError(true);setLoading(false)}});return()=>abort.abort()},[attempt])
 useEffect(()=>{const prev=history.scrollRestoration;history.scrollRestoration='manual';const onPop=()=>{restoration.current=history.state?.bgScroll||0;setParams(readParams());setModal(null)};window.addEventListener('popstate',onPop);return()=>{history.scrollRestoration=prev;window.removeEventListener('popstate',onPop)}},[])
 useLayoutEffect(()=>{if(restoration.current!==null&&!loading){const y=restoration.current;const id=requestAnimationFrame(()=>{lenisRef.current?.scrollTo(y,{immediate:true});window.scrollTo({top:y,behavior:'instant'});restoration.current=null});return()=>cancelAnimationFrame(id)}},[params,loading])
 useEffect(()=>{
  const media=matchMedia('(prefers-reduced-motion: reduce)');const pointer=matchMedia('(pointer: fine)')
  let frame=0
  const setup=()=>{cancelAnimationFrame(frame);lenisRef.current?.destroy();lenisRef.current=null;if(media.matches||isTouch()||!pointer.matches)return
   const lenis=isTouch()?null:new Lenis({lerp:.2,smoothWheel:true,anchors:true,prevent:node=>node.closest('dialog')!==null});if(!lenis)return;lenisRef.current=lenis
   const raf=(t:number)=>{lenis.raf(t);frame=requestAnimationFrame(raf)};frame=requestAnimationFrame(raf)
  };setup();media.addEventListener('change',setup);pointer.addEventListener('change',setup);return()=>{cancelAnimationFrame(frame);lenisRef.current?.destroy();lenisRef.current=null;media.removeEventListener('change',setup);pointer.removeEventListener('change',setup)}
 },[])
 useEffect(()=>{if(modal)lenisRef.current?.stop();else lenisRef.current?.start()},[modal])
 useEffect(()=>{const h=document.querySelector<HTMLElement>('#bg-main h1');if(h){h.tabIndex=-1;h.focus({preventScroll:true})}},[view,car?.id])
 useEffect(()=>{document.title=car?`${carTitle(car)} · ${price(car.price)} · Bílagallerí`:'Bílagallerí · Finndu næsta bíl';setGalleryIndex(0)},[car])
 useEffect(()=>{const el=rootRef.current?.querySelector<HTMLElement>('.bg-hero-media');if(!el||matchMedia('(prefers-reduced-motion: reduce)').matches)return;let frame=0
  const update=()=>{frame=0;const amount=Math.min(1,Math.max(0,scrollY/650));el.style.transform=`translateY(${amount*24}px)`}
  const onScroll=()=>{if(!frame)frame=requestAnimationFrame(update)};window.addEventListener('scroll',onScroll,{passive:true});update();return()=>{window.removeEventListener('scroll',onScroll);cancelAnimationFrame(frame);el.style.transform=''}
 },[view,loading])
 function navigate(next:URLSearchParams,restoreY=0){history.replaceState({...history.state,bgScroll:scrollY},'',location.href);history.pushState({bgScroll:0},'',`${location.pathname}${next.size?'?'+next:''}`);restoration.current=restoreY;setParams(next);setModal(null)}
 function go(nextView:string){const p=new URLSearchParams();if(nextView!=='home')p.set('view',nextView);navigate(p)}
 function update(key:string,value:string){if(['min','max','yearMin','yearMax','kmMax'].includes(key)&&value&&!/^\d+$/.test(value))return;const p=new URLSearchParams(params);if(value)p.set(key,value);else p.delete(key);if(key==='make')p.delete('model');p.delete('limit');history.replaceState({...history.state},'',`${location.pathname}${p.size?'?'+p:''}`);setParams(p)}
 function reset(){const p=new URLSearchParams();if(view==='saved')p.set('view','saved');else if(view!=='home')p.set('view','cars');history.replaceState({},'',`${location.pathname}${p.size?'?'+p:''}`);setParams(p)}
 function openCar(c:Car){const p=new URLSearchParams(params);p.set('car',c.id);navigate(p)}
 function backToCars(){const origin=history.state?.bgOrigin;if(origin){navigate(new URLSearchParams(origin.search),origin.scroll);return}const p=new URLSearchParams(params);p.delete('car');p.set('view','cars');navigate(p)}
 function detail(c:Car){const origin=car?history.state?.bgOrigin:{search:location.search,scroll:scrollY};openCar(c);history.replaceState({...history.state,bgOrigin:origin},'',location.href)}
 function toggleSave(id:string){setSaved(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);notify(saved.includes(id)?'Bíll fjarlægður úr völdum bílum.':'Bíll vistaður í völdum bílum.')}
 function toggleCompare(id:string){if(compare.includes(id)){setCompare(v=>v.filter(x=>x!==id));return}if(compare.length>=3){notify('Þú getur borið saman allt að þrjá bíla. Fjarlægðu einn til að bæta öðrum við.');return}setCompare(v=>[...v,id])}
 async function share(){try{await navigator.clipboard.writeText(location.href);notify('Slóð afrituð. Leitin þín fylgir með.')}catch{notify('Ekki tókst að afrita. Þú getur afritað slóðina úr veffangastikunni.')}}
 const source=view==='saved'?cars.filter(c=>saved.includes(c.id)):cars
 const results=useMemo(()=>filterCars(source,params),[source,params])
 const active=keys.filter(k=>params.get(k));const compareCars=cars.filter(c=>compare.includes(c.id))
 const limit=Math.max(12,Math.min(120,Number(params.get('limit'))||12))
 const heroCars=cars.filter(c=>['526687','750823','443852'].includes(c.id));const hero=heroCars[heroIndex%Math.max(1,heroCars.length)]
 const invalidRange=(params.get('min')&&params.get('max')&&Number(params.get('min'))>Number(params.get('max')))||(params.get('yearMin')&&params.get('yearMax')&&Number(params.get('yearMin'))>Number(params.get('yearMax')))
 const jumpInventory=()=>{const el=document.getElementById('bilar');if(el){if(lenisRef.current)lenisRef.current.scrollTo(el,{offset:-88});else el.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}else go('cars')}
 const InventoryHeading=view==='home'?'h2':'h1'
 const filters=(advanced=false)=> <Filters cars={cars} params={params} update={update} advanced={advanced}/>
 return <div className="bg-app" ref={rootRef}>
  <a className="bg-skip" href="#bg-main">Fara í efni</a><div className="bg-awning" aria-hidden="true"/>
  <header className="bg-header"><div className="bg-header-inner">
   <a className="bg-logo" href="?" aria-label="Bílagallerí, forsíða" onClick={e=>{e.preventDefault();go('home')}}><Wordmark/></a>
   <nav aria-label="Aðalvalmynd" className="bg-desktop-nav"><a href="?view=cars" aria-current={view==='cars'?'page':undefined} onClick={e=>{e.preventDefault();go('cars')}}>Bílar til sölu</a><a href="?view=cash" onClick={e=>{e.preventDefault();go('cash')}}>Kaupum bíla</a><a href="?view=sell" onClick={e=>{e.preventDefault();go('sell')}}>Selja bíl</a><a href="?view=about" onClick={e=>{e.preventDefault();go('about')}}>Um okkur</a></nav>
   <div className="bg-header-actions"><button className="bg-icon bg-saved-nav" onClick={()=>go('saved')} aria-label={`Valdir bílar, ${saved.length}`}><Heart aria-hidden="true"/>{saved.length>0&&<b>{saved.length}</b>}</button><button className="bg-theme-switch" role="switch" aria-checked={theme==='dark'} aria-label="Dökkt útlit" title={theme==='dark'?'Skipta í ljóst útlit':'Skipta í dökkt útlit'} onClick={()=>choose(theme==='dark'?'light':'dark')}><span className="bg-theme-track"><Sun aria-hidden="true"/><Moon aria-hidden="true"/><span className="bg-theme-thumb"/></span></button><a className="bg-header-phone" href="tel:+3545546700"><Phone aria-hidden="true" size={16}/>554 6700</a><button className="bg-icon bg-menu-trigger" aria-label="Opna valmynd" onClick={()=>setModal('menu')}><Menu aria-hidden="true"/></button></div>
  </div></header>
  <main id="bg-main">
  {loading?<div className="bg-loading bg-container" aria-busy="true"><p>Sæki söluskrá…</p><div/><div/></div>:error?<section className="bg-empty bg-container"><h1>Söluskráin hlóðst ekki.</h1><p>Athugaðu nettenginguna og reyndu aftur.</p><button className="bg-button primary" onClick={()=>setAttempt(x=>x+1)}>Reyna aftur</button><a href="https://www.bilagalleri.is/">Opna söluskrá Bílagallerís</a></section>:car?<>
   <div className="bg-container bg-detail-top"><button className="bg-text-button" onClick={backToCars}><ArrowLeft aria-hidden="true"/>Til baka í leit</button><button className="bg-text-button" onClick={share}><Share2 aria-hidden="true"/>Deila bíl</button></div>
   <section className="bg-container bg-detail">
    <div className="bg-gallery"><div className="bg-gallery-main"><button className="bg-gallery-expand" aria-label="Stækka mynd" onClick={()=>setModal('gallery')}><VehicleImage src={car.photos[galleryIndex]} alt={`${carTitle(car)}, mynd ${galleryIndex+1}`} eager/></button><div className="bg-photo-tools"><button className="bg-icon" aria-label="Fyrri mynd" onClick={()=>setGalleryIndex(i=>(i-1+car.photos.length)%car.photos.length)}><ChevronLeft aria-hidden="true"/></button><span>{galleryIndex+1} / {car.photos.length}</span><button className="bg-icon" aria-label="Næsta mynd" onClick={()=>setGalleryIndex(i=>(i+1)%car.photos.length)}><ChevronRight aria-hidden="true"/></button><button className="bg-icon" aria-label="Stækka myndasafn" onClick={()=>setModal('gallery')}><Maximize2 aria-hidden="true"/></button></div></div><div className="bg-thumbnails" aria-label="Myndir bíls">{car.photos.slice(0,6).map((src,i)=><button key={src} aria-label={`Sýna mynd ${i+1}`} aria-pressed={galleryIndex===i} onClick={()=>setGalleryIndex(i)}><VehicleImage src={src} alt=""/></button>)}{car.photos.length>6&&<button onClick={()=>setModal('gallery')}>Allar {car.photos.length}</button>}</div></div>
    <div className="bg-detail-summary"><div className="bg-topline"><span>{car.type} · Raðnúmer {car.id}</span>{car.offer&&<span className="bg-offer">Tilboð</span>}</div><h1>{carTitle(car)}</h1><p className="bg-trim">{car.trim}</p><Price car={car} large/><Facts car={car}/><div className="bg-inline-facts"><span>{driveLabel(car)}</span><span>{car.seats?`${car.seats} sæti`:'Sæti ekki tilgreind'}</span></div><p className="bg-location"><MapPin aria-hidden="true" size={17}/>{car.location||'Staðsetning ekki tilgreind. Hafðu samband áður en þú kemur.'}</p><button className="bg-button primary" onClick={()=>setModal('enquiry')}><Mail aria-hidden="true"/>Fyrirspurn um þennan bíl</button><div className="bg-detail-actions"><a className="bg-button" href="tel:+3545546700"><Phone aria-hidden="true" size={17}/>554 6700</a><button className="bg-button" aria-pressed={saved.includes(car.id)} onClick={()=>toggleSave(car.id)}><Heart aria-hidden="true" fill={saved.includes(car.id)?'currentColor':'none'}/>{saved.includes(car.id)?'Vistaður':'Vista bíl'}</button></div><button className="bg-text-button" aria-pressed={compare.includes(car.id)} onClick={()=>toggleCompare(car.id)}><Scale aria-hidden="true"/>{compare.includes(car.id)?'Fjarlægja úr samanburði':'Bæta í samanburð'}</button><Snapshot/></div>
   </section>
   <section className="bg-container bg-detail-content"><div><h2>Það sem fylgir bílnum</h2>{car.notes.length>0?<div className="bg-seller-notes"><h3>Upplýsingar frá seljanda</h3>{car.notes.map(n=><p key={n}>{n}</p>)}</div>:<p>Frekari lýsing seljanda er ekki tilgreind.</p>}<Equipment car={car}/></div><aside><h2>Nánari upplýsingar</h2><dl className="bg-specs">{Object.entries(car.specs).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v||'Ekki tilgreint'}</dd></div>)}</dl><p className="bg-help"><CircleHelp aria-hidden="true"/>Bílagallerí mælir með óháðri ástandsskoðun fyrir kaup. Staðfestu búnað og ástand áður en gengið er frá viðskiptum.</p><a href={car.source} target="_blank" rel="noreferrer" className="bg-text-button">Sjá upprunalega auglýsingu <ArrowRight aria-hidden="true"/></a></aside></section>
   <section className="bg-container bg-related"><h2>Fleiri bílar til að skoða</h2><div className="bg-results">{cars.filter(c=>c.id!==car.id&&c.type===car.type).sort((a,b)=>Math.abs(a.price-car.price)-Math.abs(b.price-car.price)).slice(0,2).map(c=><VehicleCard key={c.id} car={c} saved={saved.includes(c.id)} comparing={compare.includes(c.id)} onOpen={()=>detail(c)} onSave={()=>toggleSave(c.id)} onCompare={()=>toggleCompare(c.id)}/>)}</div></section>
  </>:params.get('car')?<section className="bg-empty bg-container"><h1>Bíllinn fannst ekki.</h1><p>Þessi bíll er ekki í söluskrá frumgerðarinnar.</p><button className="bg-button primary" onClick={()=>go('cars')}>Skoða alla bíla</button></section>:view==='cash'||view==='sell'?<SellPage key={view} kind={view}/>:view==='about'?<About/>:view==='compare'?<Compare cars={compareCars} onRemove={toggleCompare} onOpen={detail} goCars={()=>go('cars')}/>:<>
  {view==='home'&&hero&&<section className="bg-hero"><div className="bg-hero-copy"><div className="bg-hero-location"><MapPin aria-hidden="true" size={16}/>Hólshrauni 5 · Hafnarfirði</div><h1>NÆSTI BÍLL.<br/><span>ÞÍN LEIÐ.</span></h1><p>Finndu bíl sem hentar þér.<br/>Verð, búnaður og allar upplýsingar á einum stað.</p><button className="bg-button primary" onClick={jumpInventory}>Skoða bílana <ArrowRight aria-hidden="true"/></button><div className="bg-hero-hours"><Clock aria-hidden="true" size={16}/>Mánudaga til föstudaga · 10–17</div></div><div className="bg-hero-showroom"><div className="bg-hero-media"><VehicleImage src={hero.photos[0]} alt={carTitle(hero)} eager/></div><div className="bg-hero-caption"><button onClick={()=>detail(hero)}><span>{carTitle(hero)}</span><strong>{price(hero.price)}</strong><ArrowRight aria-hidden="true"/></button><div className="bg-hero-controls"><button className="bg-icon" aria-label="Fyrri bíll" onClick={()=>setHeroIndex(i=>(i-1+heroCars.length)%heroCars.length)}><ChevronLeft aria-hidden="true"/></button><span>0{heroIndex%heroCars.length+1} / 0{heroCars.length}</span><button className="bg-icon" aria-label="Næsti bíll" onClick={()=>setHeroIndex(i=>(i+1)%heroCars.length)}><ChevronRight aria-hidden="true"/></button></div></div></div></section>}
  <section id="bilar" className={`bg-inventory bg-container ${view!=='home'?'bg-inventory-page':''}`}>
   <div className="bg-section-head"><div><InventoryHeading className="bg-inventory-title">{view==='saved'?'VALDIR BÍLAR':'FINNDU ÞINN BÍL.'}</InventoryHeading><p>{view==='saved'?'Bílarnir sem þú hefur vistað í þessum vafra.':'Leitaðu, veldu og berðu saman.'}</p></div><button className="bg-text-button" onClick={share}><Share2 aria-hidden="true"/>Deila leit</button></div>
   <div className="bg-search-sticky"><div className="bg-search-input"><Search aria-hidden="true"/><input aria-label="Leita í söluskrá" placeholder="T.d. jeppi, 7 sæta, rafmagn undir 5 milljónum" value={params.get('q')||''} onChange={e=>update('q',e.target.value)} type="search" name="q" autoComplete="off"/>{params.get('q')&&<button className="bg-icon" onClick={()=>update('q','')} aria-label="Hreinsa leitarorð"><X aria-hidden="true"/></button>}</div><button className="bg-button bg-filter-trigger" onClick={()=>setModal('filters')}><SlidersHorizontal aria-hidden="true"/>Síur{active.length>0&&<b>{active.length}</b>}</button></div>
   <div className="bg-quick" aria-label="Flýtival">{[['','Allt'],['Jeppar','Jeppar'],['Rafmagn','Rafmagn'],['7','7+ sæta'],['Fjórhjóladrif','4×4'],['offer','Tilboð']].map(([value,label])=>{const k=value==='Rafmagn'?'fuel':value==='7'?'seats':value==='Fjórhjóladrif'?'drive':value==='offer'?'offer':'type';const v=value==='offer'?'1':value;const checked=value?params.get(k)===v:!active.length;const test=new URLSearchParams();if(value)test.set(k,v);return <button key={label} aria-pressed={checked} onClick={()=>value?update(k,checked?'':v):reset()}>{label}<span>{filterCars(source,test).length}</span></button>})}</div>
   <div className="bg-desktop-filters">{filters()}<details><summary><SlidersHorizontal aria-hidden="true" size={16}/>Fleiri síur</summary>{filters(true)}</details></div>
   {active.length>0&&<div className="bg-active-filters">{active.map(k=><button key={k} onClick={()=>update(k,'')} aria-label={`Fjarlægja síu: ${filterNames[k]}`}><span>{filterNames[k]}{!['offer','tow','site'].includes(k)?`: ${['min','max'].includes(k)?price(Number(params.get(k))):params.get(k)}`:''}</span><X aria-hidden="true" size={14}/></button>)}<button className="bg-clear" onClick={reset}>Hreinsa allt</button></div>}
   {invalidRange&&<p className="bg-error" role="alert">Lágmark þarf að vera lægra en hámark. Breyttu verðbili eða árgerð.</p>}
   <p className="bg-dated">Söluskrá 30.09.2026 · Frumgerð</p><div className="bg-result-toolbar"><p aria-live="polite" aria-atomic="true"><strong>{results.length}</strong> {results.length===1?'ökutæki':'ökutæki'}{active.length?' passa við leitina':''}</p><label>Raða eftir<select aria-label="Raða bílum" value={params.get('sort')||'default'} onChange={e=>update('sort',e.target.value)}><option value="default">Röðun söluskrár</option><option value="price-up">Lægsta verði</option><option value="price-down">Hæsta verði</option><option value="year">Nýjustu árgerð</option><option value="km">Minnstum akstri</option></select></label></div>
   {results.length?<div className="bg-results">{results.slice(0,limit).map((c,i)=><VehicleCard key={c.id} car={c} saved={saved.includes(c.id)} comparing={compare.includes(c.id)} onOpen={()=>detail(c)} onSave={()=>toggleSave(c.id)} onCompare={()=>toggleCompare(c.id)} eager={i<2}/>)}</div>:<div className="bg-empty"><Search aria-hidden="true"/><h2>{view==='saved'&&!saved.length?'Engir bílar vistaðir enn.':'Enginn bíll passar við þessa leit.'}</h2><p>{view==='saved'&&!saved.length?'Ýttu á hjartað við bíl til að eiga hann hér.':'Prófaðu að víkka verðbilið eða fjarlægja eina síu.'}</p><button className="bg-button primary" onClick={()=>view==='saved'&&!saved.length?go('cars'):reset()}>{view==='saved'&&!saved.length?'Skoða bílana':'Hreinsa leit og síur'}</button><a className="bg-text-button" href="tel:+3545546700">Hafðu samband · 554 6700</a></div>}
   {limit<results.length&&<div className="bg-loadmore"><p>Sýni {Math.min(limit,results.length)} af {results.length} ökutækjum</p><button className="bg-button" onClick={()=>{const p=new URLSearchParams(params);p.set('limit',String(limit+12));history.replaceState(history.state,'',`${location.pathname}?${p}`);setParams(p)}}>Sýna fleiri bíla <Plus aria-hidden="true"/></button></div>}
   <Snapshot/>
  </section>
  {view==='home'&&<section className="bg-sell-band"><div className="bg-container"><h2>HVAÐ VILTU<br/>GERA VIÐ ÞINN?</h2><div className="bg-sell-options"><a href="?view=cash" onClick={e=>{e.preventDefault();go('cash')}}><span>Fá staðgreiðslutilboð</span><p>Sendu upplýsingar um bílinn. Bílagallerí skoðar kaup á fólksbílum og jeppum.</p><ArrowRight aria-hidden="true"/></a><a href="?view=sell" onClick={e=>{e.preventDefault();go('sell')}}><span>Setja bíl í sölu</span><p>Fáðu aðstoð löggilts bifreiðasala við sölu á bílnum þínum.</p><ArrowRight aria-hidden="true"/></a></div></div></section>}
  </>}
  </main>
  <footer className="bg-footer bg-container"><div className="bg-footer-main"><div><a className="bg-logo" href="?" onClick={e=>{e.preventDefault();go('home')}}><Wordmark/></a><p>Örugg og ánægjuleg bílaviðskipti.</p><a href="https://www.google.com/maps/search/?api=1&query=H%C3%B3lshraun+5+Hafnarfj%C3%B6r%C3%B0ur" target="_blank" rel="noreferrer"><MapPin aria-hidden="true" size={16}/>Hólshrauni 5, 220 Hafnarfirði</a></div><div><h3>Hafðu samband</h3><a href="tel:+3545546700">554 6700</a><a href="mailto:bilagalleri@bilagalleri.is">bilagalleri@bilagalleri.is</a><p>Mánudaga til föstudaga<br/>10:00–17:00</p></div><div><h3>Bílagallerí</h3><a href="?view=about" onClick={e=>{e.preventDefault();go('about')}}>Um okkur og verðskrá</a><a href="?view=sell" onClick={e=>{e.preventDefault();go('sell')}}>Setja bíl í sölu</a><button className="bg-text-button" onClick={()=>setModal('theme')}>{theme==='dark'?<Moon aria-hidden="true"/>:<Sun aria-hidden="true"/>}Útlit: {preference==='system'?'Fylgir tæki':theme==='dark'?'Dökkt':'Ljóst'}</button></div></div><div className="bg-footer-bottom"><span>Bílagallerí ehf. · Kt. 630914-2560</span><span>Designed by <a href="https://sndrstudio.is" target="_blank" rel="noreferrer">SNDR Studio</a></span><span>Frumgerð · ekki tengd lifandi söluskrá</span></div></footer>
  {compareCars.length>0&&view!=='compare'&&<div className="bg-compare-tray"><div><Scale aria-hidden="true"/><span><strong>{compareCars.length} valdir</strong><small>{compareCars.length<2?'Veldu annan bíl til að bera saman':compareCars.map(c=>carTitle(c)).join(' · ')}</small></span><button className="bg-button primary" disabled={compareCars.length<2} onClick={()=>go('compare')}>Bera saman</button><button className="bg-icon" aria-label="Hreinsa samanburð" onClick={()=>setCompare([])}><X aria-hidden="true"/></button></div></div>}
  {notice&&<div className="bg-toast" role="status">{notice}<button className="bg-icon" aria-label="Loka tilkynningu" onClick={()=>setNotice('')}><X aria-hidden="true" size={16}/></button></div>}
  {modal==='menu'&&<Modal title="Valmynd" onClose={()=>setModal(null)}><nav className="bg-mobile-nav">{[['cars','Bílar til sölu'],['saved',`Valdir bílar (${saved.length})`],['cash','Fá staðgreiðslutilboð'],['sell','Setja bíl í sölu'],['about','Um okkur og verðskrá']].map(([v,l])=><a key={v} href={`?view=${v}`} onClick={e=>{e.preventDefault();go(v)}}>{l}<ArrowRight aria-hidden="true"/></a>)}</nav><ThemeOptions preference={preference} choose={choose}/><a className="bg-button primary" href="tel:+3545546700"><Phone aria-hidden="true"/>Hringja í 554 6700</a></Modal>}
  {modal==='theme'&&<Modal title="Útlit síðunnar" onClose={()=>setModal(null)}><ThemeOptions preference={preference} choose={choose}/><p>Valið þitt er geymt í þessum vafra. Veldu „Fylgja tæki“ til að nota útlitsstillingu símans eða tölvunnar.</p></Modal>}
  {modal==='filters'&&<Modal title="Finndu þinn bíl" onClose={()=>setModal(null)}><div className="bg-modal-filters">{filters()}{filters(true)}</div>{invalidRange&&<p className="bg-error">Lágmark þarf að vera lægra en hámark.</p>}<div className="bg-dialog-foot"><button className="bg-text-button" onClick={reset}>Hreinsa síur</button><button className="bg-button primary" onClick={()=>setModal(null)}>Sjá {results.length} ökutæki</button></div></Modal>}
  {modal==='enquiry'&&car&&<Modal title="Fyrirspurn um bíl" onClose={()=>setModal(null)}><div className="bg-enquiry-car"><VehicleImage src={car.photos[0]} alt=""/><div><h3>{carTitle(car)}</h3><p>{car.registration} · {mileage(car)}</p><strong>{price(car.price)}</strong></div></div><RequestForm car={car}/></Modal>}
  {modal==='gallery'&&car&&<Modal title={`${carTitle(car)} · ${galleryIndex+1} / ${car.photos.length}`} onClose={()=>setModal(null)} wide><div className="bg-lightbox" onKeyDown={e=>{if(e.key==='ArrowRight')setGalleryIndex(i=>(i+1)%car.photos.length);if(e.key==='ArrowLeft')setGalleryIndex(i=>(i-1+car.photos.length)%car.photos.length)}}><VehicleImage src={car.photos[galleryIndex]} alt={`${carTitle(car)}, mynd ${galleryIndex+1}`} eager/><div className="bg-lightbox-controls"><button className="bg-button" onClick={()=>setGalleryIndex(i=>(i-1+car.photos.length)%car.photos.length)}><ChevronLeft aria-hidden="true"/>Fyrri</button><span>{galleryIndex+1} / {car.photos.length}</span><button className="bg-button" onClick={()=>setGalleryIndex(i=>(i+1)%car.photos.length)}>Næsta<ChevronRight aria-hidden="true"/></button></div></div></Modal>}
 </div>
}

function ThemeOptions({preference,choose}:{preference:string;choose:(p:string)=>void}){return <fieldset className="bg-theme-options"><legend>Útlit</legend>{[['light','Ljóst',Sun],['dark','Dökkt',Moon],['system','Fylgja tæki',Monitor]].map(([v,l,Icon])=>{const I=Icon as typeof Sun;return <label key={v as string}><input type="radio" name="theme" checked={preference===v} onChange={()=>choose(v as string)}/><I aria-hidden="true" size={18}/>{l as string}</label>})}</fieldset>}
function Filters({cars,params,update,advanced}:{cars:Car[];params:URLSearchParams;update:(k:string,v:string)=>void;advanced:boolean}){
 const select=(key:FilterKey,label:string,values:string[])=> <label>{label}<select name={key} value={params.get(key)||''} onChange={e=>update(key,e.target.value)}><option value="">{key==='make'?'Allar tegundir':key==='model'?'Allar gerðir':'Allt'}</option>{[...new Set(values.filter(Boolean))].sort((a,b)=>a.localeCompare(b,'is')).map(v=><option key={v}>{v}</option>)}</select></label>
 const numeric=(key:FilterKey,label:string,placeholder:string,max=99999999)=><label>{label}<input name={key} type="number" inputMode="numeric" min="0" max={max} step="1" placeholder={placeholder} value={params.get(key)||''} onChange={e=>update(key,e.target.value)}/></label>
 return <div className={`bg-filter-grid ${advanced?'advanced':''}`}>{advanced?<>{select('type','Flokkur',cars.map(c=>c.type))}{select('gear','Skipting',cars.map(c=>c.transmission))}{select('drive','Drif',cars.map(c=>c.specs.Drif))}{numeric('yearMin','Árgerð frá','T.d. 2018',2027)}{numeric('yearMax','Árgerð til','T.d. 2026',2027)}{numeric('kmMax','Hámarksakstur (km)','T.d. 100000',1000000)}<label>Sætafjöldi<select name="seats" value={params.get('seats')||''} onChange={e=>update('seats',e.target.value)}><option value="">Allur sætafjöldi</option><option value="5">5 eða fleiri</option><option value="7">7 eða fleiri</option><option value="9">9 eða fleiri</option></select></label><div className="bg-checkboxes">{[['offer','Aðeins tilboð'],['tow','Með dráttarkrók'],['site','Skráð á staðnum']].map(([k,l])=><label key={k}><input type="checkbox" checked={params.get(k)==='1'} onChange={e=>update(k,e.target.checked?'1':'')}/>{l}</label>)}</div></>:<>{select('make','Tegund',cars.map(c=>c.make))}{select('model','Gerð',cars.filter(c=>!params.get('make')||c.make===params.get('make')).map(c=>c.name))}{select('fuel','Orkugjafi',cars.map(c=>c.fuel))}{numeric('min','Verð frá (kr.)','Ekkert lágmark')}{numeric('max','Verð að (kr.)','Ekkert hámark')}</>}</div>
}
function VehicleCard({car,saved,comparing,onOpen,onSave,onCompare,eager=false}:{car:Car;saved:boolean;comparing:boolean;onOpen:()=>void;onSave:()=>void;onCompare:()=>void;eager?:boolean}){
 return <article className="bg-car"><div className="bg-car-photo"><a href={`?car=${car.id}`} onClick={e=>{if(e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;e.preventDefault();onOpen()}} tabIndex={-1} aria-hidden="true"><VehicleImage src={car.photos[0]} alt={carTitle(car)} eager={eager}/></a>{car.offer&&<span className="bg-offer">Tilboð</span>}<button className="bg-icon bg-save" aria-label={`${saved?'Fjarlægja':'Vista'} ${carTitle(car)}`} aria-pressed={saved} onClick={onSave}><Heart aria-hidden="true" fill={saved?'currentColor':'none'}/></button><span className="bg-photo-count">{car.photos.length} myndir</span></div><div className="bg-car-body"><div className="bg-car-identity"><h2><a href={`?car=${car.id}`} onClick={e=>{if(e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;e.preventDefault();onOpen()}}>{carTitle(car)}</a></h2><p>{car.trim||car.type}</p></div><Price car={car}/><Facts car={car}/><div className="bg-card-extra"><span>{car.specs.Drif==='Fjórhjóladrif'?'4×4':car.type}</span>{car.seats>0&&<span>{car.seats} sæti</span>}{car.highlight&&<span>{car.highlight}</span>}</div><div className="bg-card-foot"><button className="bg-text-button" aria-pressed={comparing} onClick={onCompare}>{comparing?<Check aria-hidden="true" size={17}/>:<Plus aria-hidden="true" size={17}/>}Bera saman</button><button className="bg-text-button" onClick={onOpen}>Skoða bíl <ArrowRight aria-hidden="true" size={17}/></button></div></div></article>
}
function Equipment({car}:{car:Car}){
 const all=[...new Set(car.groups.flat())]
 const categories=[['Saga og viðhald',/Tímareim|Þjónustu|Smurbók|Reyklaust/],['Dráttur og burður',/Dráttar|eftirvagn|tengibúnað/],['Orka og afköst',/rafhlöð|hleðsl|eyðsla|CO 2|Innspýting|Túrbína|Intercooler/],['Öryggi og akstursaðstoð',/ABS|hemla|loftpúð|Akrein|Blindsvæð|myndavél|nálgun|spól|stöðug|Brekk|hraðastill|að leggja/i],['Skjáir og tengingar',/CarPlay|Android|Bluetooth|hljóð|símateng|USB|AUX|leiðsögu|Navi|skjá|tölva/i],['Hjól og ytra byrði',/dekk|felgur|ljós|lýsing|þakbog|Brettakant/i],['Þægindi og annar búnaður',/./]] as const
 const used=new Set<string>()
 return <div className="bg-equipment">{categories.map(([title,pattern],i)=>{const list=all.filter(x=>!used.has(x)&&pattern.test(x));list.forEach(x=>used.add(x));if(!list.length)return null;return <details key={title} open={i===0||i===1}><summary>{title}<span>{list.length}<Plus aria-hidden="true" size={18}/></span></summary><ul>{list.map(x=><li key={x}><Check aria-hidden="true" size={15}/>{x}</li>)}</ul></details>})}</div>
}
function RequestForm({car,kind}:{car?:Car;kind?:'cash'|'sell'}){
 const [review,setReview]=useState<Record<string,string>|null>(null);const [copied,setCopied]=useState(false);const draft=useRef<Record<string,string>>({});const dirty=useRef(false);const reviewRef=useRef<HTMLDivElement>(null);const formRef=useRef<HTMLFormElement>(null)
 useEffect(()=>{if(review)reviewRef.current?.focus();else if(Object.keys(draft.current).length)formRef.current?.querySelector<HTMLInputElement>('input')?.focus()},[review])
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty.current){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[])
 const subject=car?`Fyrirspurn: ${carTitle(car)} (${car.id})`:kind==='cash'?'Ósk um staðgreiðslutilboð':'Ósk um söluskráningu'
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();draft.current=Object.fromEntries([...new FormData(e.currentTarget).entries()].map(([k,v])=>[k,String(v)]));setReview(draft.current)}
 const body=review?`${subject}\n${car?car.source+'\n':''}\n${Object.entries(review).map(([k,v])=>`${k}: ${v}`).join('\n')}`:''
 if(review)return <div className="bg-review" ref={reviewRef} tabIndex={-1}><Check aria-hidden="true"/><h3>Beiðnin er tilbúin til yfirferðar.</h3><p>Hún hefur ekki verið send. Opnaðu tölvupóstinn þinn og sendu hana þaðan.</p><dl>{Object.entries(review).filter(([,v])=>v).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><a className="bg-button primary" onClick={()=>{dirty.current=false}} href={`mailto:bilagalleri@bilagalleri.is?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`}><Mail aria-hidden="true"/>Opna tölvupóst</a><button className="bg-button" onClick={async()=>{try{await navigator.clipboard.writeText(body);setCopied(true)}catch{setCopied(false)}}}>{copied?'Afritað':'Afrita beiðni'}</button><button className="bg-text-button" onClick={()=>setReview(null)}>Breyta upplýsingum</button></div>
 return <form ref={formRef} onSubmit={submit} onChange={()=>{dirty.current=true}} className="bg-request-form"><p className="bg-form-note">Frumgerð: þú ferð yfir beiðnina áður en þú opnar hana í tölvupósti. Ekkert er sent sjálfkrafa.</p>{!car&&<div className="bg-form-row"><label>Skráningarnúmer<input name="Skráningarnúmer" defaultValue={draft.current["Skráningarnúmer"]} autoComplete="off" required maxLength={12} autoCapitalize="characters" placeholder="AB 123"/></label><label>Akstur (km)<input name="Akstur (km)" defaultValue={draft.current["Akstur (km)"]} autoComplete="off" type="number" inputMode="numeric" min="0" max="2000000" required placeholder="85000"/></label></div>}<label>Nafn<input name="Nafn" defaultValue={draft.current.Nafn} autoComplete="name" required maxLength={120}/></label><div className="bg-form-row"><label>Sími<input name="Sími" defaultValue={draft.current.Sími} type="tel" inputMode="tel" autoComplete="tel" required pattern="[+0-9 ()-]{7,20}" title="Sláðu inn símanúmer, að lágmarki 7 stafi."/></label><label>Netfang<input name="Netfang" defaultValue={draft.current.Netfang} spellCheck={false} type="email" autoComplete="email" required maxLength={160}/></label></div><label>{car?'Hvað viltu vita?':'Upplýsingar um bílinn'}<textarea name="Skilaboð" rows={4} maxLength={4000} defaultValue={draft.current.Skilaboð??(car?`Ég hef áhuga á ${carTitle(car)}. Er bíllinn enn til sölu og hvenær væri hægt að skoða hann?`:'')} placeholder={car?'Fyrirspurn, reynsluakstur eða skipti':'Tegund, árgerð, ástand, þjónustusaga og annað sem skiptir máli.'}/></label><button className="bg-button primary" type="submit">Yfirfara beiðni <ArrowRight aria-hidden="true"/></button><p className="bg-small">Upplýsingarnar eru aðeins á þessari síðu þar til þú sendir tölvupóst. Þær eru ekki vistaðar af frumgerðinni.</p><a className="bg-text-button" href={car?.inquiry||(kind==='cash'?cashURL:sellURL)} target="_blank" rel="noreferrer">Nota núverandi eyðublað Bílagallerís <ArrowRight aria-hidden="true" size={16}/></a></form>
}
function SellPage({kind}:{kind:'cash'|'sell'}){return <section className="bg-container bg-service-page"><div><span className="bg-service-label">{kind==='cash'?'Bílagallerí kaupir bílinn':'Bílagallerí sér um söluna'}</span><h1>{kind==='cash'?'FÁÐU TILBOÐ Í ÞINN BÍL.':'SETTU BÍLINN Í SÖLU.'}</h1><p className="bg-lead">{kind==='cash'?'Viltu selja bílinn gegn staðgreiðslu? Sendu okkur upplýsingar eða komdu með hann til okkar.':'Fáðu aðstoð löggilts bifreiðasala við að selja bílinn þinn.'}</p><ol className="bg-steps"><li><span>1</span><div><h3>Segðu okkur frá bílnum</h3><p>Skráningarnúmer, akstur og upplýsingar um ástand.</p></div></li><li><span>2</span><div><h3>{kind==='cash'?'Við skoðum bílinn':'Við förum yfir skráninguna'}</h3><p>{kind==='cash'?'Bílagallerí metur bílinn og gerir þér tilboð.':'Verð, búnaður og skilmálar eru staðfestir með þér.'}</p></div></li><li><span>3</span><div><h3>{kind==='cash'?'Þú tekur ákvörðun':'Bíllinn fer á söluskrá'}</h3><p>{kind==='cash'?'Ef þú samþykkir tilboðið er gengið frá viðskiptunum.':'Skráningin er birt þegar gengið hefur verið frá samkomulagi.'}</p></div></li></ol>{kind==='sell'?<div className="bg-fee"><h3>Söluþóknun</h3><strong>4,2% <small>af söluverði, auk vsk.</small></strong><p>Lágmarkssölulaun eru 105.000 kr. með vsk. fyrir ökutæki undir 1.890.000 kr. Innifalin eru ein eigendaskipti, veðbandayfirlit og ferilskrá. Aðrir kostnaðarliðir eru staðfestir við skráningu.</p><a href="https://bilagalleri.is/um-okkur" target="_blank" rel="noreferrer">Verðskrá Bílagallerís</a></div>:<p className="bg-help">Bílagallerí skoðar kaup á fólksbílum og jeppum á verðbilinu 1–20 milljónir króna.</p>}<a className="bg-text-button" href="tel:+3545546700"><Phone aria-hidden="true"/>Frekar í síma? 554 6700</a></div><div className="bg-form-panel"><h2>{kind==='cash'?'Óska eftir tilboði':'Óska eftir söluskráningu'}</h2><RequestForm key={kind} kind={kind}/></div></section>}
function About(){return <section className="bg-container bg-about"><h1>BÍLAGALLERÍ.<br/>VIÐ FJARÐARKAUP.</h1><p className="bg-lead">„Okkar markmið nú sem endranær eru örugg og ánægjuleg bílaviðskipti.“</p><div className="bg-about-grid"><div><h2>Ásberg Helgi Helgason</h2><p>Löggiltur bifreiðasali og framkvæmdastjóri.</p><p>Ásberg hefur yfir 30 ára reynslu af sölu nýrra og notaðra bíla og innflutningi ökutækja frá Evrópu, Kanada og Bandaríkjunum.</p><a className="bg-text-button" href="mailto:asi@bilagalleri.is"><Mail aria-hidden="true"/>asi@bilagalleri.is</a><a className="bg-text-button" href="tel:+3546632430"><Phone aria-hidden="true"/>663 2430</a></div><div><h2>Komdu við</h2><p>Hólshrauni 5, 220 Hafnarfirði<br/>Við Fjarðarkaup.</p><p>Mánudaga til föstudaga: 10:00–17:00.</p><a className="bg-button primary" href="https://www.google.com/maps/search/?api=1&query=H%C3%B3lshraun+5+Hafnarfj%C3%B6r%C3%B0ur" target="_blank" rel="noreferrer"><MapPin aria-hidden="true"/>Fá leiðarlýsingu</a></div></div><div className="bg-about-grid"><div><h2>Verðskrá</h2><dl className="bg-specs"><div><dt>Söluþóknun</dt><dd>4,2% auk vsk.</dd></div><div><dt>Lágmarkssölulaun undir 1.890.000 kr.</dt><dd>105.000 kr. með vsk.</dd></div><div><dt>Umsýslugjald kaupanda vegna fjármögnunar</dt><dd>24.800 kr. með vsk.</dd></div></dl><p>Lágmarkssölulaun innihalda ein eigendaskipti, veðbandayfirlit og ferilskrá. Umsýslugjald fjármögnunar leggst ofan á lánsupphæð. Verðskrá er birt með fyrirvara um breytingar.</p></div><div><h2>Áður en þú prófar bílinn</h2><p>Framvísa þarf gildu ökuskírteini. Hámarkstími reynsluaksturs er 20 mínútur nema um annað sé samið.</p><p>Bílagallerí mælir með að kaupendur láti óháðan aðila ástandsskoða ökutæki fyrir kaup.</p><a href="https://bilagalleri.is/um-okkur" target="_blank" rel="noreferrer" className="bg-text-button">Allir skilmálar og upprunaleg verðskrá <ArrowRight aria-hidden="true"/></a></div></div></section>}
function Compare({cars,onRemove,onOpen,goCars}:{cars:Car[];onRemove:(id:string)=>void;onOpen:(c:Car)=>void;goCars:()=>void}){
 const rows:[string,(c:Car)=>string][]=[['Verð',c=>price(c.price)+(c.priceNote?` · ${c.priceNote}`:'')],['Nýskráning',c=>c.registration||'Ekki tilgreint'],['Akstur',mileage],['Orkugjafi',fuelLabel],['Skipting',c=>c.transmission||'Ekki tilgreint'],['Drif',driveLabel],['Sæti',c=>c.seats?String(c.seats):'Ekki tilgreint'],['Hestöfl',c=>c.specs.Hestöfl||'Ekki tilgreint'],['Næsta skoðun',c=>c.specs['Næsta skoðun']||'Ekki tilgreint'],['Dráttargeta, hemlað',c=>c.groups.flat().find(x=>x.startsWith('Þyngd hemlaðs'))?.replace('Þyngd hemlaðs eftirvagns ','')||'Ekki tilgreint']]
 return <section className="bg-container bg-comparison"><button className="bg-text-button" onClick={goCars}><ArrowLeft aria-hidden="true"/>Velja fleiri bíla</button><h1>BERÐU SAMAN.</h1><p>Verð, búnaður og helstu upplýsingar hlið við hlið.</p>{cars.length<2?<div className="bg-empty"><Scale aria-hidden="true"/><h2>Veldu tvo eða þrjá bíla.</h2><p>Notaðu „Bera saman“ við þá bíla sem vekja áhuga þinn.</p><button className="bg-button primary" onClick={goCars}>Skoða bílana</button>{cars.map(c=><button key={c.id} className="bg-text-button" onClick={()=>onRemove(c.id)}>Fjarlægja {carTitle(c)} <X aria-hidden="true"/></button>)}</div>:<><p className="bg-mobile-hint">Strjúktu til hliðar til að sjá allan samanburðinn.</p><div className="bg-compare-scroll" tabIndex={0} role="region" aria-label="Samanburður bíla"><table><thead><tr><th scope="col">Upplýsingar</th>{cars.map(c=><th scope="col" key={c.id}><button className="bg-icon" aria-label={`Fjarlægja ${carTitle(c)} úr samanburði`} onClick={()=>onRemove(c.id)}><X aria-hidden="true"/></button><VehicleImage src={c.photos[0]} alt={carTitle(c)}/><button className="bg-text-button" onClick={()=>onOpen(c)}>{carTitle(c)}<ArrowRight aria-hidden="true"/></button><p>{c.trim}</p></th>)}</tr></thead><tbody>{rows.map(([label,value])=><tr key={label}><th scope="row">{label}</th>{cars.map(c=><td key={c.id}>{value(c)}</td>)}</tr>)}</tbody></table></div><Snapshot/></>}</section>
}
