/* Málning hf product range as published on malning.is (read 2026-09-29): descriptions are
 * their own sentences (product names re-cased from capitals), consumption ("notkun", litres per
 * square metre per coat) and overcoat times ("yfir", hours) are taken from each product's
 * data-sheet PDF, PDF links are theirs. Nothing here is estimated. */
export type Flokkur = 'inni' | 'uti' | 'vidur' | 'golf'
export type Vara = {
  id: string; nafn: string; fl: Flokkur; lysing: string; mynd: string
  /** litres per m2 per coat, [min, max] */
  notkun: [number, number] | null
  /** hours until the next coat may go on, [min, max] */
  yfir: [number, number] | null
  thurr: string; aferd: string; litir: string; svans: boolean
  pdf: string; oryggi: string; url: string
}

export const FLOKKAR: { id: Flokkur; nafn: string; lysing: string }[] = [
  { id: 'inni', nafn: 'Innanhúss', lysing: 'Veggir, loft og lökk fyrir heimilið.' },
  { id: 'uti', nafn: 'Utanhúss', lysing: 'Steinn, múr, stéttir og þök.' },
  { id: 'vidur', nafn: 'Viðarvörn', lysing: 'Kjörvari og hreinsiefni fyrir palla og hús.' },
  { id: 'golf', nafn: 'Gólf', lysing: 'Grunnar og lökk á gólf og stiga.' },
]

export const VORUR: Vara[] = [
  { id: "kopal-2", nafn: "Kópal 2", fl: "inni", lysing: "Kópal 2 er vatnsþynnanleg, lyktarlaus plastmálning, sem inniheldur engin lífræn leysiefni, ammóníak eða formaldehýð. Kópal 2 hylur sérlega vel og gefur mjög jafna áferð. Kópal 2 er sérlega gerð til að mála loft innanhúss og hentar einkar vel þar sem birtan gerir miklar kröfur um jafna áferð.", mynd: "kopal-2", notkun: [0.1, 0.1], yfir: [4, 8], thurr: "30 - 60 mín. við 20°C.", aferd: "Almött.", litir: "Kópal 2 er framleidd í nokkrum Staðallitum.", svans: true, pdf: "https://malning.is/wp-content/uploads/2018/11/KÓPAL-2.pdf", oryggi: "https://malning.is/wp-content/uploads/2019/11/KO%CC%81PAL-2.pdf", url: "https://malning.is/vorur/kopal-2/" },
  { id: "kopal-4", nafn: "Kópal 4", fl: "inni", lysing: "Kópal 4 er vatnsþynnanleg, lyktarlaus plastmálning sem inniheldur engin leysiefni, ammóníak eða formaldehýð. Kópal 4 hylur einstaklega vel, hefur mjög góða þvottheldni og ýrist lítið við rúllun. Kópal 4 er einkum ætluð til að mála veggi innanhúss.", mynd: "kopal-4", notkun: [0.1, 0.1], yfir: [4, 8], thurr: "30-60 mín. við 20°C.", aferd: "Mött.", litir: "Kópal 4 er framleidd í nokkrum Staðallitum og að auki er boðið upp á mikinn fjölda lita með litun á Kópal 4 í stofni.", svans: true, pdf: "https://malning.is/wp-content/uploads/2018/11/KÓPAL-4.pdf", oryggi: "https://malning.is/wp-content/uploads/2019/11/KO%CC%81PAL-4.pdf", url: "https://malning.is/vorur/kopal-4/" },
  { id: "kopal-10", nafn: "Kópal 10", fl: "inni", lysing: "Kópal 10 er vatnsþynnanleg, lyktarlaus plastmálning sem inniheldur engin leysiefni, ammóníak eða formaldehýð. Kópal 10 hylur einstaklega vel, hefur mjög góða þvottheldni og ýrist lítið við rúllun. Kópal 10 er einkum ætluð til að mála veggi innanhúss.", mynd: "kopal-10", notkun: [0.1, 0.1], yfir: [4, 8], thurr: "30-60 mín. við 20°C.", aferd: "Hálfmött.", litir: "Kópal 10 er framleidd í nokkrum Staðallitum og að auki er boðið upp á mikinn fjölda lita með litun á Kópal Glitru í stofnum.", svans: true, pdf: "https://malning.is/wp-content/uploads/2018/11/KÓPAL-10.pdf", oryggi: "https://malning.is/wp-content/uploads/2019/11/KO%CC%81PAL-10.pdf", url: "https://malning.is/vorur/kopal-10/" },
  { id: "kopal-25", nafn: "Kópal 25", fl: "inni", lysing: "Kópal 25 er vatnsþynnanleg, lyktarlaus plastmálning, sem inniheldur engin lífræn leysiefni, ammóníak eðaformaldehýð. Kópal 25 hylur sérlega vel og hefur mikla þvottheldni. Kópal 25 er einkum ætluð til að mála veggi innanhúss. Kópal 25 er sérlega hentug á ganga, stofur, svefnherbergi o.fl.", mynd: "kopal-25", notkun: [0.1, 0.12], yfir: [4, 8], thurr: "Um 1 klst. við 20°C.", aferd: "Hálfmött LEIÐBEININGAR", litir: "Kópal 25 er framleidd hvít og auk þess er boðið upp mikinn fjölda með litun Kópal 25 í stofnum.", svans: false, pdf: "https://malning.is/wp-content/uploads/2018/11/KÓPAL-25.pdf", oryggi: "https://malning.is/wp-content/uploads/2014/01/KÓPAL-BIRTA-20.pdf", url: "https://malning.is/vorur/kopal-25/" },
  { id: "kopal-akrylhud-7", nafn: "Kópal Akrýlhúð 7", fl: "inni", lysing: "Kópal Akrýlhúð 7 er vatnsþynnt mött akrýlmálning. Málningin inniheldur mygluvarnarefni sem ver málningarfilmuna. Kópal Akrýlhúð 7 er einkum ætluð til málunar á loftum og veggjum innanhúss. Hentar sérstaklega vel þar sem mikið raka- og þvottaálag er til staðar t.d. í eldhúsi, þvottahúsi og í léttum iðnaði.", mynd: "kopal-akrylhud-7", notkun: [0.1, 0.125], yfir: null, thurr: "Snertiþurrt eftir um 60 mín. við 20°C. Yfirmálun eftir 4-8 klst. allt eftir aðstæðum.", aferd: "", litir: "Hægt að lita í fjölda lita. Gljástig: 7 GU (60°)", svans: false, pdf: "https://malning.is/wp-content/uploads/2024/08/TDS-KOPAL-AKRYLHUD-7.pdf", oryggi: "https://malning.is/wp-content/uploads/2019/11/KO%cc%81PAL-AKRY%cc%81LHU%cc%81%c3%90-7.pdf", url: "https://malning.is/vorur/kopal-akrylhud-7/" },
  { id: "kopal-akrylhud-gljastig-25-60", nafn: "Kópal Akrýlhúð 25 og 60", fl: "inni", lysing: "Kópal Akrýlhúð er vatnsþynnt akrýlmálning, með mikla þvottheldni og hylur sérlega vel. Kópal Akrýlhúð er gerlavarin, þolir vel rakaálag og hefur mjög góða viðloðun. Kópal Akrýlhúð er einkum ætluð á veggi í frystihúsum, víða í matvælaiðnaði og annarsstaðar þar sem mikið raka- og þvottaálag er til staðar.", mynd: "kopal-akrylhud-gljastig-25-60", notkun: [0.1, 0.12], yfir: [4, 8], thurr: "Um 1 klst. við 20°C.", aferd: "KÓPAL AKRÝLHÚÐ 25: Silkimött KÓPAL AKRÝLHÚÐ 60: Gljáandi", litir: "Kópal Akrýlhúð er framleidd hvít og í stofnum auk þess er boðið upp á sérlitun.", svans: false, pdf: "https://malning.is/wp-content/uploads/2019/11/Ma%CC%81lning-hf-Kopal-25-60-2019.pdf", oryggi: "https://malning.is/wp-content/uploads/2019/11/KO%CC%81PAL-AKRY%CC%81LHU%CC%81%C3%90-25-60.pdf", url: "https://malning.is/vorur/kopal-akrylhud-gljastig-25-60/" },
  { id: "kopal-perlulakk-4080", nafn: "Kópal Perlulakk 40 og 80", fl: "inni", lysing: "Kópal Perlulakk er lyktarlítið vatnsþynnanlegt akrýllakk, sem er hraðþornandi og gulnar ekki. Kópal Perlulakk flýtur sérlega vel, myndar harða og áferðarfallega filmu. Kópal Perlulakk er ætlað til notkunar innanhúss á glugga, hurðir, karma, húsgögn o.fl., þar sem silkimattrar eða gljáandi áferðar er óskað.", mynd: "kopal-perlulakk-4080", notkun: [0.1, 0.1], yfir: [4, 8], thurr: "Um 1 klst. við 20°C.", aferd: "Silkimött (hálfgljáandi) og gljáandi.", litir: "Kópal Perlulakk er framleitt hvítt og að auki er unnt að fá mikinn fjölda lita með litun á stofnum.", svans: false, pdf: "https://malning.is/wp-content/uploads/2014/01/KÓPAL-PERLULAKK-40801.pdf", oryggi: "https://malning.is/wp-content/uploads/2022/02/SDS-KÓPAL-PERLULAKK-40-80.v1.0.pdf", url: "https://malning.is/vorur/kopal-perlulakk-4080/" },
  { id: "kopal-fylligrunnur", nafn: "Kópal Fylligrunnur", fl: "inni", lysing: "Kópal Fylligrunnur er vatnsþynnt, lyktarlaus grunnmálning sem inniheldur engin lífræn leysiefni, ammóníak eða formaldehýð. Kópal Fylligrunnur er með hátt þurrefni og fyllir mjög vel. Kópal Fylligrunnur er viðurkennd umhverfisvæn grunnmálning vottuð með", mynd: "kopal-fylligrunnur", notkun: [0.1, 0.12], yfir: [6, 12], thurr: "30-60 mín. við 20°C.", aferd: "Mött.", litir: "", svans: true, pdf: "https://malning.is/wp-content/uploads/2014/01/Kópal-fylligrunnur-2020.pdf", oryggi: "https://malning.is/wp-content/uploads/2014/01/KOPAL-FYLLIGRUNNUR.pdf", url: "https://malning.is/vorur/kopal-fylligrunnur/" },
  { id: "blaer-30-blaer-90", nafn: "Blær 30 og Blær 90", fl: "inni", lysing: "Blær er fljótþornandi alkýðbundið lakk, sem er afar létt í notkun, flýtur vel og myndar sterka og áferðarfallega filmu. Blær er einkum ætlaður til innanhússnotkunar á hurðir, húsgögn, glugga og aðra fleti þar sem hálfgljáandi, 30 eða hágljáandi, 90 lakkáferðar er óskað.", mynd: "blaer-30-blaer-90", notkun: [0.1, 0.1], yfir: [8, 12], thurr: "Um 3-5 klst. við 20°C.", aferd: "BLÆR 30: hálfgljáandi. BLÆR 90: hágljáandi. Áburður: Með rúllu, pensli eða háþrý", litir: "Blær er framleiddur hvítur, svartur og í stofnum sem unnt er að lita í mikinn fjölda lita.", svans: false, pdf: "https://malning.is/wp-content/uploads/2014/01/BLÆR-30+901.pdf", oryggi: "https://malning.is/wp-content/uploads/2017/08/BLÆR-30-90.pdf", url: "https://malning.is/vorur/blaer-30-blaer-90/" },
  { id: "kopal-golfgrunnur", nafn: "Kópal Gólfgrunnur", fl: "golf", lysing: "Kópal Gólfgrunnur er vatnsþynnanlegur akrýl bindigrunnur, sem smýgur vel og bindur laust yfirborð. Bætir viðloðun og vatnsþol Granítlakks.", mynd: "kopal-golfgrunnur", notkun: [0.1, 0.2], yfir: [1, 2], thurr: "Snertiþurrt eftir um 15 til 30 mín. við 20°C.", aferd: "", litir: "", svans: false, pdf: "https://malning.is/wp-content/uploads/2016/03/Kópal-Gólfgrunnur.pdf", oryggi: "https://malning.is/wp-content/uploads/2016/03/SDS-KÓPAL-GÓLFGRUNNUR.v1.0.pdf", url: "https://malning.is/vorur/kopal-golfgrunnur/" },
  { id: "kopal-granitlakk", nafn: "Kópal Granítlakk", fl: "golf", lysing: "Kópal Granítlakk er slitsterk vatnsþynnanleg málning úr sérvalinni blöndu af Akrýl og Polýúretan bindiefnum sem gulna ekki. Það er auðvelt að bera málninguna á, hún flýtur vel, þornar fljótt og gefur fallegt útlit.", mynd: "kopal-granitlakk", notkun: [0.12, 0.12], yfir: [1, 2], thurr: "Snertiþurrt eftir um 15 til 30 mín. við 20°C.", aferd: "Hálfgljáandi, um 50 (60°). Þynnir og hreinsun áhalda; vatn eða sápuvatn til þvot", litir: "Kópal Granítlakk er framleidd í stofni sem hægt er að lita í mikinn fjölda lita.", svans: false, pdf: "https://malning.is/wp-content/uploads/2016/03/Kópal-Granítlakk.pdf", oryggi: "https://malning.is/wp-content/uploads/2020/07/SDS-Ko%CC%81pal-Grani%CC%81tlakk.v1.0.pdf", url: "https://malning.is/vorur/kopal-granitlakk/" },
  { id: "kopal-leifturlakk", nafn: "Kópal Leifturlakk", fl: "golf", lysing: "Kópal Leifturlakk er glært, vatnsþynnanlegt, lyktarlaust akrýllakk án mengunar af lífrænum leysiefnum. Kópal Leifturlakk flýtur vel og myndar lakkfilmu sem gulnar ekki.", mynd: "kopal-leifturlakk", notkun: null, yfir: null, thurr: "Yfirlökkun:", aferd: "", litir: "", svans: false, pdf: "https://malning.is/wp-content/uploads/2014/01/Kópal-leifturlakk.pdf", oryggi: "https://malning.is/wp-content/uploads/2014/01/KÓPAL-LEIFTURLAKK1.pdf", url: "https://malning.is/vorur/kopal-leifturlakk/" },
  { id: "kjorvari-10", nafn: "Kjörvari 10", fl: "vidur", lysing: "Kjörvari 10 er viðarvörn gerð úr vatnsheldum alkýðolíum og öflugum fúa- og rotvarnarefnum. Kjörvari 10 er mjög þunnfljótandi, smýgur vel inn í viðinn og hleypir raka úr viðnum auðveldlega gegnum sig.", mynd: "kjorvari-10", notkun: [0.06, 0.1], yfir: [8, 12], thurr: "Um 5-6 klst. við 20°C.", aferd: "", litir: "", svans: false, pdf: "https://malning.is/wp-content/uploads/2014/02/GRUNN-KJÖRVARI-10.pdf", oryggi: "https://malning.is/wp-content/uploads/2017/08/KJORVARI-10.pdf", url: "https://malning.is/vorur/kjorvari-10/" },
  { id: "kjorvari-12-pallaolia", nafn: "Kjörvari 12 Pallaolía", fl: "vidur", lysing: "Kjörvari 12 er olíubundin viðarvörn, sem smýgur vel inn í viðinn, veitir honum góða vatnsvörn og hamlar gegn sprungumyndun. Kjörvari 12 er einkum ætlaður á gagnvarinn við utanhúss t.d. á palla, skjólveggi o.fl. Bestur verður árangurinn ef viðurinn er varinn algjörlega óveðraður.", mynd: "kjorvari-12-pallaolia", notkun: [0.08, 0.2], yfir: [6, 10], thurr: "6 – 8 klst. við 20°C.", aferd: "Slétt, mött. Efnismeðferð: KJÖRVARA 12 Kjörvara 12 má bera á flötinn með pensli,", litir: "Kjörvari 12 er framleiddur glær og í nokkrum Staðallitum, en að auki er boðið upp á mikinn fjölda lita með litun á Kjörvara 12 í stofni.", svans: false, pdf: "https://malning.is/wp-content/uploads/2019/10/Kjörvari-12-Pallaolía-2019.pdf", oryggi: "https://malning.is/wp-content/uploads/2017/08/KJORVARI-12-pallaoli%CC%81a.pdf", url: "https://malning.is/vorur/kjorvari-12-pallaolia/" },
  { id: "kjorvari-13-edalolia", nafn: "Kjörvari 13 Eðalolía", fl: "vidur", lysing: "Kjörvari 13 Eðalolía er þunnfljótandi viðarolía gerð úr sérvöldum hráefnum. Kjörvari 13 smýgur vel inn í viðinn og veitir honum góða vatnsvörn. Kjörvari 13 Eðalolía er einkum ætluð á garðhúsgögn, harðviðarpalla og aðra viðlíka fleti utanhúss. Bestur verður árangurinn ef viðurinn er varinn algjörlega óveðraður.", mynd: "kjorvari-13-edalolia", notkun: [0.06, 0.1], yfir: [6, 8], thurr: "Um 5-6 klst. við 20°C.", aferd: "", litir: "Kjörvari 13 Eðalolía er fáanleg í tekklit og einnig glær sem má lita í mikinn fjölda lita. Kjörvara 13 Eðalolíu má bera á flötinn með pensli, púða eða sprautu.", svans: false, pdf: "https://malning.is/wp-content/uploads/2019/08/Málning-Eðalolía-13.pdf", oryggi: "https://malning.is/wp-content/uploads/2017/03/KJORVARI-13-Eðalolía.pdf", url: "https://malning.is/vorur/kjorvari-13-edalolia/" },
  { id: "kjorvari-14", nafn: "Kjörvari 14", fl: "vidur", lysing: "Kjörvari 14 er gagnsæ viðarvörn, gerð úr vatnsheldum alkýðolíum, öflugum fúa- og rotvarnarefnum og ljósheldum litarefnum. Kjörvari 14 er þunnfljótandi, smýgur vel inn í viðinn og hleypir raka úr viðnum auðveldlega í gegnum sig.", mynd: "kjorvari-14", notkun: [0.06, 0.1], yfir: [8, 12], thurr: "6-8 klst. við 20°C.", aferd: "Gagnsæ. Efnismeðferð: KJÖRVARA 14 má bera á flötinn með pensli, svampi eða dýfin", litir: "Kjörvari 14 er framleiddur glær og í nokkrum Staðallitum að auki er boðið upp á mikinn fjölda lita með litun á Kjörvara 14 í stofni.", svans: false, pdf: "https://malning.is/wp-content/uploads/2019/02/Kjorvari-14-2019.pdf", oryggi: "https://malning.is/wp-content/uploads/2017/08/KJORVARI-14.pdf", url: "https://malning.is/vorur/kjorvari-14/" },
  { id: "kjorvari-15-tix", nafn: "Kjörvari 15 TIX", fl: "vidur", lysing: "Kjörvara 15 svipar til Kjörvara 14 en hefur „tixótrópíst“ flæði, hann slettast síður úr penslinum og auðveldar að mála upp fyrir sig. Kjörvari 15 er ætlaður á hvers konar við, heflaðan sem óheflaðan, einkum utanhúss þar sem þess er óskað að viðaráferð sjáist.", mynd: "kjorvari-15-tix", notkun: [0.125, 0.2], yfir: [8, 12], thurr: "Snertiþurrt á um 5-6 klst. við 20C. Lengist með lægra hitastig.", aferd: "", litir: "Kjörvara 15 má blanda fjölda lita í Stofn.", svans: false, pdf: "https://malning.is/wp-content/uploads/2020/07/Kjöarvari-15-Tix.pdf", oryggi: "", url: "https://malning.is/vorur/kjorvari-15-tix/" },
  { id: "kjorvari-16", nafn: "Kjörvari 16", fl: "vidur", lysing: "Kjörvari 16 er alkýðolíubundin viðarvörn, sem ver viðinn niðurbroti af völdum sólarljóss. Kjörvari 16 myndar mjúka filmu með gott veðrunarþol. Kjörvari 16 er einkum ætlaður á hvers konar við utanhúss, þar sem óskað er hyljandi áferðar án þess að viðaráferðin tapist.", mynd: "kjorvari-16", notkun: [0.08, 0.16], yfir: [6, 10], thurr: "2-4 klst. við 20°C.", aferd: "Hálfgljáandi.", litir: "Kjörvari 16 er framleiddur í nokkrum Staðallitum auk stofna sem unnt er að lita í fjölda lita.", svans: false, pdf: "https://malning.is/wp-content/uploads/2014/01/KJORVARI-16.pdf", oryggi: "https://malning.is/wp-content/uploads/2017/08/KJORVARI-16.pdf", url: "https://malning.is/vorur/kjorvari-16/" },
  { id: "kjorvari-20", nafn: "Kjörvari 20", fl: "vidur", lysing: "Kjörvari 20 er vatnsþynnanleg, hyljandi viðarvörn, sem ver viðinn niðurbroti af völdum sólarljóss. Kjörvari 20 er gerður úr ljósheldum litarefnum, öflugum fúa- og rotvarnarefnum, blöndu af feitu alkýði og 100% akrýlemúlsjón, sem gefur teygjanlega filmu, án þess að viðarmynstur glatist.", mynd: "kjorvari-20", notkun: [0.1, 0.2], yfir: [5, 7], thurr: "Um 1 klst. við 20°C.", aferd: "Hálfgljáandi.", litir: "Kjörvari 20 er framleiddur í nokkrum Staðallitum og að auki er boðið upp á mikinn fjölda lita með litun á stofnum.", svans: false, pdf: "https://malning.is/wp-content/uploads/2014/01/KJORVARI-20.pdf", oryggi: "https://malning.is/wp-content/uploads/2019/11/KJO%CC%88RVARI-20-1.pdf", url: "https://malning.is/vorur/kjorvari-20/" },
  { id: "kjorvari-22-pallaolia", nafn: "Kjörvari 22 Pallaolía", fl: "vidur", lysing: "Í Kjörvara 22 eru öflug rotvarnarefni og mjög ljósheld litarefni bundin vatnsheldum alkýðolíum. Kjörvari 22 er þunnfljótandi, smýgur vel inn í viðinn og veitir góða vörn gegn veðrun. Kjörvari 22 er gagnsæ viðarvörn einkum ætluð á gagnvarinn við utanhúss, t.d. palla, skjólveggi o.fl.", mynd: "kjorvari-22-pallaolia", notkun: [0.167, 0.25], yfir: [6, 8], thurr: "Snertiþurrt á um 2-4 klst. við 20C. Lengist með lægra hitastig.", aferd: "", litir: "Kjörvari 22 má blanda fjölda lita í Stofn.", svans: false, pdf: "https://malning.is/wp-content/uploads/2020/07/KJÖRVARI-22-Pallaolía.pdf", oryggi: "https://malning.is/wp-content/uploads/2020/07/SDS-KJO%CC%88RVARI-22.v1.0.pdf", url: "https://malning.is/vorur/kjorvari-22-pallaolia/" },
  { id: "kjorvari-24", nafn: "Kjörvari 24", fl: "vidur", lysing: "Kjörvari 24 er vatnsþynnt, þunnfljótandi alkýðbundin viðarvörn með öflugum rotvarnarefnum og litarefnum sem verja viðinn vel gegn niðurbroti af völdum sólarljóssins en hylja ekki viðaræðarnar, heldur framkalla og skýra þær.", mynd: "kjorvari-24", notkun: [0.167, 0.25], yfir: [8, 12], thurr: "Snertiþurrt á um 5-6 klst. við 20C. Lengist með lægra hitastig.", aferd: "", litir: "Kjörvari 24 má blanda fjölda lita í Stofn.", svans: false, pdf: "https://malning.is/wp-content/uploads/2015/11/KJÖRVARI-24.pdf", oryggi: "https://malning.is/wp-content/uploads/2020/07/SDS-KJO%CC%88RVARI-24.v1.0.pdf", url: "https://malning.is/vorur/kjorvari-24/" },
  { id: "vidarskoli", nafn: "Viðarskoli", fl: "vidur", lysing: "Viðarskoli er vatnsþynnt hreinsiefni, sem brotnar auðveldlega niður í náttúrinni. Viðarskoli inniheldur efni sem fríska upp viðarfleti og fjarlæga viðargráma og sveppagróður. Viðarskoli er einkum ætlaður til að fjarlægja viðargráma og sveppagróður á timbri utanhúss.", mynd: "vidarskoli", notkun: [0.1, 0.2], yfir: null, thurr: "", aferd: "", litir: "", svans: false, pdf: "https://malning.is/wp-content/uploads/2014/01/VIDARSKOLI.pdf", oryggi: "https://malning.is/wp-content/uploads/2017/03/VIDARSKOLI.pdf", url: "https://malning.is/vorur/vidarskoli/" },
  { id: "vidarbaes-2", nafn: "Viðarbæs", fl: "vidur", lysing: "Viðarbæs er ólakkbundin sprittbæs gert úr uppleystum litarefnum, sem hafa góða ljósheldni.", mynd: "vidarbaes-2", notkun: [0.07, 0.11], yfir: null, thurr: "10 -15 mín. við 20°C. Yfirlökkun: Eftir 2-3 klst.", aferd: "", litir: "Viðarbæs er fáanleg í um 15 staðal­ litum, sem blanda má í öllum hlutföllum.", svans: false, pdf: "https://malning.is/wp-content/uploads/2013/01/VIÐARBÆS.pdf", oryggi: "https://malning.is/wp-content/uploads/2017/03/VIDARBÆS.pdf", url: "https://malning.is/vorur/vidarbaes-2/" },
  { id: "pallahreinsir", nafn: "Pallahreinsir", fl: "vidur", lysing: "Pallahreinsir fjarlægir gamla pallaolíu, fitu og önnur óhreinindi. Pallahreinsir er vatnsþynnt lútarkennt hreinsiefni sem leysir upp gamla pallaolíu og nýtist vel ef lagfæra á flekkóttan pall eða til að skipta um lit.", mynd: "pallahreinsir", notkun: null, yfir: null, thurr: "", aferd: "", litir: "", svans: false, pdf: "https://malning.is/wp-content/uploads/2014/01/Pallahreinsir-Vidarvörn-2021.pdf", oryggi: "https://malning.is/wp-content/uploads/2020/07/SDS-PALLAHREINSIR-v1.0.pdf", url: "https://malning.is/vorur/pallahreinsir/" },
  { id: "fernis-olia", nafn: "Fernisolía", fl: "vidur", lysing: "Fernis Olía (fernis eða gljákvoða) er vökvi úr viðarolíum sem er notaður til hlífðar og fegurðar málverka. Olían er hrein jurtaolía gerð úr tvísoðinni línolíu. Hentar vel til meðhöndlunar á viði og náttúrustein. Við meðhöndlun á viði og náttúrusteini er mælt með að þynna fyrstu umferð með terpentínu.", mynd: "fernis-olia", notkun: null, yfir: null, thurr: "", aferd: "", litir: "", svans: false, pdf: "https://malning.is/wp-content/uploads/2019/11/FERNIS-OLI%CC%81A.pdf", oryggi: "", url: "https://malning.is/vorur/fernis-olia/" },
  { id: "steintex", nafn: "Steintex", fl: "uti", lysing: "Steintex er emúlsjónsmálning gerð úr ósápanlegu akrýlbindiefni og lútarþolnum litar og fylliefnum. Steintex hefur sérstaka eiginleika til að hleypa raka auðveldlega í gegnum sig. Steintex er einkum hönnuð fyrir múr og steinsteypta fleti, þar sem krafist er lútarþols, mikils veðrunarþols og rakagegnstreymis.", mynd: "steintex", notkun: [0.1, 0.1], yfir: [6, 12], thurr: "30-60 mín. við 20°C.", aferd: "Almött.", litir: "Steintex er framleidd í nokkrum Staðallitum en að auki er hægt að fá mikinn fjölda lita með litun á Steintex í stofnum.", svans: false, pdf: "https://malning.is/wp-content/uploads/2016/04/Steinvari-Steintex.pdf", oryggi: "https://malning.is/wp-content/uploads/2015/11/KOPAL-STEINTEX.pdf", url: "https://malning.is/vorur/steintex/" },
  { id: "steinskjol", nafn: "Steinskjól", fl: "uti", lysing: "Steinskjól er vatnsþynnanleg akrýlmálning sem má mála með allt niður að 0°C. Steinskjól hefur gott veðrunar- og teygjuþol, sem gefur möguleika á að brúa fíngerðar sprungur. Steinskjól er sérlega hönnuð fyrir múr og stein-steypu utanhúss.", mynd: "steinskjol", notkun: [0.1, 0.1], yfir: [6, 12], thurr: "30-60 mín. við 20°C.", aferd: "Almött. LEIÐBEININGAR", litir: "Steinskjól er framleitt í nokkrum staðallitum og að auki er boðið upp á mikinn fjölda lita með litun á Stein­ Skjóli í stofnum.", svans: false, pdf: "https://malning.is/wp-content/uploads/2016/04/STEINSKJOL.pdf", oryggi: "https://malning.is/wp-content/uploads/2019/11/STEINVARI-STEINSKJO%CC%81L.pdf", url: "https://malning.is/vorur/steinskjol/" },
  { id: "steinvari-2000", nafn: "Steinvari 2000", fl: "uti", lysing: "Steinvari 2000 er terpentínuþynnanleg akrýlbundin málning, sem hefur þá einstöku eiginleika að vera þétt gegn vatni í fljótandi ástandi, en hleypa raka í loftkenndu ástandi vel í gegnum sig eða um tvöfalt betur en hefðbundin plastmálning.", mynd: "steinvari-2000", notkun: [0.17, 0.17], yfir: [8, 16], thurr: "Um 1,5-2 klst. við 20°C.", aferd: "Slétt, mött.", litir: "Steinvari 2000 er framleiddur í um 10 Staðallitum. Auk þess er boðið upp á sérlitun, þegar um kaup á umtalsverðu magni er að ræða.", svans: false, pdf: "https://malning.is/wp-content/uploads/2016/04/STEINVARI-2000.pdf", oryggi: "https://malning.is/wp-content/uploads/2017/08/STEINVARI-2000.pdf", url: "https://malning.is/vorur/steinvari-2000/" },
  { id: "steingrunnur", nafn: "Steingrunnur", fl: "uti", lysing: "Steingrunnur er vatnsþynnanlegur bindigrunnur gerður úr sérstöku akrýlbindiefni, sem smýgur vel og bindur laust yfirborð. Er einkum ætlaður til að grunna múr og steinsteypu utanhúss undir Steintex eða Steinskjól þar sem nokkur duftsmitun er til staðar. Það má einnig nota hann til að grunna undir Steinþykkni.", mynd: "steingrunnur", notkun: [0.12, 0.2], yfir: [4, 8], thurr: "30-60 mín. við 20°C.", aferd: "", litir: "", svans: false, pdf: "https://malning.is/wp-content/uploads/2019/07/STEINGRUNNUR.pdf", oryggi: "https://malning.is/wp-content/uploads/2023/06/SDS-STEINVARI-STEINGRUNNUR.v1.0.pdf", url: "https://malning.is/vorur/steingrunnur/" },
  { id: "steinakryl", nafn: "Steinakrýl", fl: "uti", lysing: "Steinakrýl er terpentínuþynnanleg akrýlmálning, sem þornar eingöngu við uppgufun leysiefna. Steinakrýl er sérstaklega hannað til notkunar á múr og steinsteypta fleti utanhúss við íslenskar aðstæður.", mynd: "steinakryl", notkun: [0.17, 0.17], yfir: [8, 16], thurr: "Um 1,5-2 klst. við 20°C.", aferd: "Slétt, mött.", litir: "Steinakrýl er framleitt í um 10 Staðallitum og að auki má fá mikinn fjölda lita með litun í stofnum.", svans: false, pdf: "https://malning.is/wp-content/uploads/2016/04/STEINVARI-STEINAKRÝL.pdf", oryggi: "https://malning.is/wp-content/uploads/2017/08/STEINVARI-STEINAKRYL.pdf", url: "https://malning.is/vorur/steinakryl/" },
  { id: "steinthykkni", nafn: "Steinþykkni", fl: "uti", lysing: "Steinþykkni er einþátta, vatnsþynnanleg akrýlmálning, sem myndar mjög teygjanlega filmu, jafnvel við lágt hitastig. Steinþykkni er einkum ætlað á vatnsbretti, ofan á veggi og fleiri slíka lárétta og lítið hallandi steinfleti, til að þétta gegn vatni og brúa fíngerðar sprungur.", mynd: "steinthykkni", notkun: [0.6, 0.6], yfir: [12, 12], thurr: "", aferd: "Mött.", litir: "", svans: false, pdf: "https://malning.is/wp-content/uploads/2016/04/STEINVARI-STEINÞYKKNI.pdf", oryggi: "https://malning.is/wp-content/uploads/2014/01/KÓPAL-STEINÞYKKNI.pdf", url: "https://malning.is/vorur/steinthykkni/" },
  { id: "steinvari-murgrunnur-03", nafn: "Steinvari Múrgrunnur 03", fl: "uti", lysing: "Múrgrunnur 03 er glær, þunnfljótandi, leysiefnaþynntur grunnur, sem sem smýgur afar vel. Múrgrunnur 03 er einkum ætlaður til að grunna stein undir Kópal Steinþykkni. Áburður: Múrgrunn 03 má bera á flötinn með pensli, rúllu, eða sprautu.", mynd: "steinvari-murgrunnur-03", notkun: [0.15, 0.2], yfir: [3, 5], thurr: "30 – 60 mín. við 20°C.", aferd: "", litir: "", svans: false, pdf: "https://malning.is/wp-content/uploads/2015/04/STEINVARI-MÚRGRUNNUR-03.pdf", oryggi: "https://malning.is/wp-content/uploads/2017/08/STEINVARI-MURGRUNNUR-03.pdf", url: "https://malning.is/vorur/steinvari-murgrunnur-03/" },
  { id: "stettvari", nafn: "Stéttvari", fl: "uti", lysing: "Stéttvari er leysiefnaþynntur akrýlgrunnur, sem myndar þétta og veðurþolna filmu. Stéttvari er einkum ætlaður á mynstursteyptar innkeyrslur, plön, gangstéttar o.fl.", mynd: "stettvari", notkun: [0.12, 0.16], yfir: [3, 5], thurr: "30 - 60 mín við 20°C.", aferd: "Gljáandi og mött. Áburður: STÉTTVARA má bera á flötinn með rúllu, pensli eða spr", litir: "", svans: false, pdf: "https://malning.is/wp-content/uploads/2014/01/STÉTTVARI.pdf", oryggi: "https://malning.is/wp-content/uploads/2017/03/STETTVARI.pdf", url: "https://malning.is/vorur/stettvari/" },
  { id: "troppumalning", nafn: "Tröppumálning", fl: "uti", lysing: "Tröppumálning er mött terpentínuþynnt hraðþornandi sements- og akrýlmálning. Tröppumálning er einkum ætluð á útitröppur, handrið, svalagólf og ýmsa lárétta fleti utanhúss.", mynd: "troppumalning", notkun: [0.15, 0.15], yfir: [6, 12], thurr: "1 – 2 klst. við 20°C.", aferd: "Slétt, mött.", litir: "", svans: false, pdf: "https://malning.is/wp-content/uploads/2014/11/TRÖPPUMÁLNING.pdf", oryggi: "https://malning.is/wp-content/uploads/2026/06/TROPPUMALNING.pdf", url: "https://malning.is/vorur/troppumalning/" },
  { id: "vatnsvari-40", nafn: "Vatnsvari 40", fl: "uti", lysing: "Vatnsvari 40 er vatnsfæla, vatnstær lausn af mónósílani, sem smýgur afar vel inn í öll gljúp, steinrík byggingarefni. Vatnsvari 40 binst steininum órjúfanlegum efnatengjum og gerir hann þannig mjög varanlega vatnsfælin, án þess að hafa áhrif á rakaflutning í loftkenndu ástandi og truflar því ekki rakaskipti steinsins við umhverfið.", mynd: "vatnsvari-40", notkun: [0.2, 0.2], yfir: [24, 48], thurr: "Nokkrar mínútur.", aferd: "", litir: "", svans: false, pdf: "https://malning.is/wp-content/uploads/2014/01/VATNSVARI2.pdf", oryggi: "https://malning.is/wp-content/uploads/2017/03/VATNSVARI-40.pdf", url: "https://malning.is/vorur/vatnsvari-40/" },
  { id: "vatnsvari-v", nafn: "Vatnsvari V", fl: "uti", lysing: "Vatnsvari V er vatnsþynnanleg vatnsfæla, byggð á sílani, sem smýgur afar vel inn í öll gljúp, steinrík byggingarefni. Vatnsvari V er seldur sem þykkni og er að jafnaði þynntur rétt fyrir notkun. Vatnsvari V er einfaldur í notkun og minnkar losun á lífrænum leysum samanborið við hefðbundnar vatnsfælur.", mynd: "vatnsvari-v", notkun: [0.125, 0.25], yfir: null, thurr: "Snertiþurrt eftir um 1 klst. Yfirmálun oftast næsta dag.", aferd: "", litir: "Ljós þeyta. Þornar glær. Gljástig: Á ekki við", svans: false, pdf: "https://malning.is/wp-content/uploads/2022/05/TDS-VATNSVARI-V.pdf", oryggi: "https://malning.is/wp-content/uploads/2022/05/297838_Málning-hf_VATNSVARI-V_IS-is_v1_0.pdf", url: "https://malning.is/vorur/vatnsvari-v/" },
  { id: "thol-2", nafn: "Þol", fl: "uti", lysing: "Þol er feit alkýðmálning sem er létt í notkun, flýtur vel og myndar sterka og varanlega hálfgljáandi lakkfilmu. Þol hefur mikið veðrunarþol. Þol er einkum ætlað til notkunar á bárujárnsþök og aðra málmfleti utanhúss, þar sem mikið mæðir á og óskað er hálfgljáandi áferðar.", mynd: "thol-2", notkun: [0.08, 0.12], yfir: [8, 12], thurr: "Snertiþurrt eftir um 3-5 klst. við 20°C.", aferd: "Hálfgljáandi (Silkimatt).", litir: "Þol er framleitt í nokkrum Staðallitum en að auki er boðið upp á mikinn fjölda lita með litun á Þoli i stofnum.", svans: false, pdf: "https://malning.is/wp-content/uploads/2014/02/ÞOL.pdf", oryggi: "https://malning.is/wp-content/uploads/2017/08/%C3%9EOL.pdf", url: "https://malning.is/vorur/thol-2/" },
]
