/**
 * Flatbakan (flatbakan.is) - verified content only.
 * Source: flatbakan.is (studied 2026-07-07), its upsell.is ordering app and Prismic pages.
 * This is a DESIGN-HANDOFF prototype: the live ordering/sales system (upsell.is) is unchanged;
 * every "Panta" action deep-links to the real /order flow so the demo is fully functional.
 * Sample prices are the studio's own published prices; disclaimed as a prototype in the footer.
 */

export const ORDER = 'https://flatbakan.is/order'
export const PHONE_DISPLAY = '567 1717'
export const PHONE_HREF = 'tel:+3545671717'
export const EMAIL = 'flatbakan@flatbakan.is'
export const MAPS = 'https://maps.google.com/?q=Bæjarlind+2,+201+Kópavogur'

export const SOCIAL = {
  instagram: 'https://www.instagram.com/flatbakan', // TODO confirm exact handle at handoff
  facebook: 'https://www.facebook.com/flatbakan',
}

const A = `${import.meta.env.BASE_URL}img/flatbakan/`
export const IMG = {
  logoBadge: `${A}logo-badge.png`,
  // Two Higgsfield gens of the SAME pizza on the exact page orange (#F19C2C), cut out seamlessly.
  whole: `${A}pizza-whole.webp`, // intact pizza — the intro/spin state
  slice: `${A}pizza-slice.webp`, // that bottom slice, cropped tight + hull-cleaned — the traveller
  boltada: `${A}pizza-boltada.jpg`,
  dodlada: `${A}pizza-dodlada.jpg`,
  sterka: `${A}pizza-sterka.jpg`,
  peppada: `${A}pizza-peppada.jpg`,
  ingredientsBg: `${A}fb-ingredients-bg.webp`, // scattered real ingredients, bg removed + pre-blurred
}

/**
 * Geometry of the removed bottom slice within the 1200px pizza canvas, as fractions of the
 * rendered pizza width — lets the traveller overlay its gap exactly, then fly to the CTA.
 * cx/cy = slice-crop centre offset from pizza centre; w = slice-crop width. (From process_pizzas.py)
 */
export const SLICE_GEO = { cx: 0.138, cy: 0.226, w: 0.272 }

/**
 * The 8 slices as individual registered layers, for the radial "explode": each carries its
 * outward unit vector (ux,uy) so it can spread from the centre. One (uy≈+0.93, the bottom) is
 * the traveller that later detaches to the CTA. Generated by process_pizzas.py.
 */
export const SLICES = [
  { img: `${A}pizza-sl0.webp`, ux: -0.930, uy: -0.367, traveller: false },
  { img: `${A}pizza-sl1.webp`, ux: -0.403, uy: -0.915, traveller: false },
  { img: `${A}pizza-sl2.webp`, ux: 0.375, uy: -0.927, traveller: false },
  { img: `${A}pizza-sl3.webp`, ux: 0.922, uy: -0.387, traveller: false },
  { img: `${A}pizza-sl4.webp`, ux: 0.919, uy: 0.395, traveller: false },
  { img: `${A}pizza-sl5.webp`, ux: 0.362, uy: 0.932, traveller: true },
  { img: `${A}pizza-sl6.webp`, ux: -0.356, uy: 0.934, traveller: false },
  { img: `${A}pizza-sl7.webp`, ux: -0.921, uy: 0.391, traveller: false },
]
/** The traveller slice's outward direction (bottom slice) — matches SLICES[5]. */
export const TRAVELLER_VEC = { ux: 0.362, uy: 0.932 }

/** The exact solid orange both pizza images are generated on — the hero background must match. */
export const HERO_ORANGE = '#F19C2C'

/** Vinsælustu pizzurnar - copy grounded in the studio's own menu descriptions */
export const FEATURED = [
  {
    name: 'Sú Boltaða',
    img: IMG.boltada,
    desc: 'Mozzarellaosta blanda, flatböku sósa, pepperoni, skinka, sveppir, hvítlaukur, ananas, rjómaostur og svartur pipar.',
    price: '4.090',
    best: true,
  },
  {
    name: 'Sú Döðlaða',
    img: IMG.dodlada,
    desc: 'Mozzarellaosta blanda, flatböku sósa, pepperoni, döðlur, rauðlaukur, beikon, rjómaostur og svartur pipar.',
    price: '3.980',
    best: true,
  },
  {
    name: 'Sú Sterka',
    img: IMG.sterka,
    desc: 'Pepperóní, laukur, ferskur chilli, jalapeno, blandaðar ólífur, piparostur og chillikrydd.',
    price: '3.980',
    best: false,
  },
  {
    name: 'Sú Peppaða',
    img: IMG.peppada,
    desc: 'Mozzarellaosta blanda, flatböku sósa, pepperoni og rjómaostur.',
    price: '3.450',
    best: false,
  },
]

/** Landing "matseðill" quick-links - all open the real upsell ordering flow */
export const MENU_LINKS = [
  { label: 'Tilboð', note: 'Hádegis- og kvöldtilboð' },
  { label: 'Bökur', note: 'Súrdeigsbotn, hægt hefaður' },
  { label: 'Vegan', note: 'Grænt og gott' },
  { label: 'Meðlæti', note: 'Brauðstangir og dýfur' },
  { label: 'Drykkir', note: 'Gos og meira' },
  { label: 'Gjafabréf', note: 'Gefðu flatböku' },
]

export const HOURS = [
  { day: 'Mánudaga til fimmtudaga', time: '11:00 - 20:30' },
  { day: 'Föstudaga', time: '11:00 - 21:00' },
  { day: 'Laugardaga', time: '12:00 - 21:00' },
  { day: 'Sunnudaga', time: '16:00 - 20:30' },
]

/** The four promises (fixes the current site's empty value cards) */
export const VALUES = [
  { title: 'Gæða hráefni', line: 'Súrdeigsbotn hefaður í rólegheitum og ekta ítalskt hráefni.' },
  { title: 'Vegan vinalegt', line: 'Alvöru vegan bökur, ekki bara eftiráhugsun.' },
  { title: 'Gott verð', line: 'Hádegistilboð og kort sem borga sig fyrir fastagesti.' },
  { title: 'Happy hour', line: 'Betra verð á völdum tímum, fylgstu með á Instagram.' },
]

/** Pizza Truck - mobile catering arm */
export const TRUCK = {
  intro: 'Flatböku ofninn kemur til þín. Frábær lausn fyrir fyrirtæki, veislur og einkasamkvæmi.',
  packages: [
    {
      name: 'Hlaðborð',
      line: 'Þú velur allt að 3 bökur af matseðlinum, bornar fram á hlaðborði.',
      rates: [
        { label: 'Daggjald', sub: 'Mán-fös 11:00-17:00', price: '3.000', per: 'á mann' },
        { label: 'Kvöldgjald', sub: 'Mán-fös 17:00-22:00', price: '3.250', per: 'á mann' },
      ],
    },
    {
      name: 'Sneiðapartý',
      line: 'Þrjár tegundir, sneiðar afgreiddar beint úr lúgunni. Fyrir stærri viðburði.',
      rates: [
        { label: 'Daggjald', sub: 'Mán-fös 11:00-17:00', price: '2.250', per: 'á mann' },
        { label: 'Kvöldgjald', sub: 'Mán-fös 17:00-22:00', price: '2.500', per: 'á mann' },
      ],
    },
  ],
}

export const STORY = {
  heading: 'Í hjarta Kópavogs síðan 2015',
  body: 'Íslenska Flatbakan opnaði í febrúar 2015, hugmynd þeirra Valla og Gumma bróður hans, með handboltakappann Guðjón Val með í för. Allt frá fyrsta degi í Bæjarlind 2 hefur áherslan verið sú sama: frábærar bökur, hlýlegt viðmót og staður sem fólki þykir gaman að koma á.',
}

export const KAERLEIKS = {
  heading: 'Kærleikspizza',
  body: 'Í tilefni af tíu ára afmælinu tóku eigendurnir og Tolli Morthens höndum saman um kærleikspizzuna. Allur ágóði rennur í Sollusjóðinn, sem styður fólk til sjálfstæðis eftir afplánun með menntun, sjálfstyrkingu og sérfræðiaðstoð.',
  cta: 'Lesa söguna',
}

export const AWARD = { title: 'Restaurant Guru 2023', sub: 'Best Pizza in Kópavogur' }

export const ADDRESS = { street: 'Bæjarlind 2', town: '201 Kópavogur' }
