import puppeteer from 'puppeteer-core'
const br = await puppeteer.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: 'new' })
const page = await br.newPage(); await page.setViewport({ width: 1440, height: 900 })
await (await page.createCDPSession()).send('Emulation.setEmulatedMedia', { features: [{ name: 'prefers-reduced-motion', value: 'reduce' }] })
await page.goto('http://localhost:8791/', { waitUntil: 'networkidle0' })
await new Promise(r => setTimeout(r, 1500))
const y = await page.evaluate(() => { const e = document.querySelector('.ki-strata-static'); if (!e) return null; window.scrollTo(0, e.offsetTop - 60); return [e.offsetTop, e.offsetHeight] })
console.log('static', JSON.stringify(y))
await new Promise(r => setTimeout(r, 500))
await page.screenshot({ path: '/tmp/ki-rm.png' })
await br.close()
