/**
 * Nýpugarðar — getting here, and what is close (a real map).
 *
 * Every line on it is real: coastline, glacier edges and lagoons from
 * OpenStreetMap, and the drives are the OSRM driving routes from the farm's
 * own coordinates to each place's car park, generated by
 * tools/nypugardar-map.mjs into map-data.json. The minutes and kilometres in
 * the list are those same routes' figures (minutes rounded to five, because a
 * routing profile knows nothing about gravel or February). Nothing here is
 * drawn by hand and nothing is to be adjusted by hand: rerun the generator.
 *
 * Static SVG, so it prerenders, costs no library and no tiles, and a crawler
 * can read the list. Place names and drives live in the list, not in the SVG,
 * so they stay readable on a 320px phone where the map itself is small.
 *
 * Interaction: choosing a place in the list (hover, focus or tap) brings its
 * drive forward and dims the others. Motion: the drives draw out from the
 * farm, tied to scroll position; at rest (server HTML, reduced motion) they
 * are drawn.
 */
import { useEffect, useRef, useState } from 'react'
import type { Copy } from './copy'
import MAP from './map-data.json'
import { loadMotion, scrub } from './motion'

type PlaceKey = 'hofn' | 'thorbergssetur' | 'jokulsarlon' | 'diamondBeach' | 'fjallsarlon' | 'stokksnes'

/* km across the map box, for the scale bar */
const KM_ACROSS =
  (MAP.bbox.e - MAP.bbox.w) * Math.cos((((MAP.bbox.s + MAP.bbox.n) / 2) * Math.PI) / 180) * 111.32
const TEN_KM = (10 / KM_ACROSS) * 100 // % of width
const HAIR = 'rgba(244,238,226,0.14)'
/* Jökulsárlón's and Diamond Beach's car parks are 700 m apart, which is one
 * marker width at this scale. Their BADGES step apart along a short leader;
 * the true point stays marked with a small dot. The route ends are untouched. */
const BADGE_OFFSET: Partial<Record<PlaceKey, [number, number]>> = {
  jokulsarlon: [14, -16],
  diamondBeach: [-14, 16],
}

export default function RouteMap({ t, reduced }: { t: Copy; reduced: boolean }) {
  const ref = useRef<HTMLDivElement>(null)
  const panRef = useRef<HTMLDivElement>(null)
  const [active, setActive] = useState<PlaceKey | null>(null)

  /* On a phone the map is drawn 640px wide in a sideways scroller, opened
     centred on the farm. The numbered list below carries everything the map
     does, so the pan is a bonus, never the only way to the information. */
  useEffect(() => {
    const el = panRef.current
    if (!el || el.scrollWidth <= el.clientWidth) return
    el.scrollLeft = (MAP.farm.x / MAP.w) * el.scrollWidth - el.clientWidth * 0.62
  }, [])
  const places = MAP.places as Array<(typeof MAP.places)[number] & { key: PlaceKey }>

  useEffect(() => {
    if (reduced) return
    let disposed = false
    let revert: (() => void) | null = null
    loadMotion().then(({ gsap }) => {
      const el = ref.current
      if (disposed || !el) return
      const ctx = gsap.context(() => {
        const tl = gsap.timeline({
          scrollTrigger: { trigger: el, start: 'top 75%', end: 'top 30%', scrub: scrub() },
        })
        tl.fromTo(el.querySelectorAll('[data-drive]'), { strokeDashoffset: 1 }, { strokeDashoffset: 0, ease: 'none', duration: 1 })
          .fromTo(el.querySelectorAll('[data-marker]'), { opacity: 0 }, { opacity: 1, ease: 'none', duration: 0.3, stagger: 0.06 }, 0.45)
      }, el)
      revert = () => ctx.revert()
    })
    return () => {
      disposed = true
      revert?.()
    }
  }, [reduced])

  const pct = (x: number, y: number) => ({ left: `${(x / MAP.w) * 100}%`, top: `${(y / MAP.h) * 100}%` })

  return (
    <div ref={ref}>
      <div
        ref={panRef}
        className="relative overflow-x-auto overscroll-x-contain border [scrollbar-width:none] sm:overflow-hidden [&::-webkit-scrollbar]:hidden"
        style={{ borderColor: HAIR }}
      >
        <div className="relative w-full min-w-[640px] sm:min-w-0" style={{ aspectRatio: `${MAP.w} / ${MAP.h}` }} role="img" aria-label={t.journey.mapAria}>
          <svg viewBox={`0 0 ${MAP.w} ${MAP.h}`} className="absolute inset-0 h-full w-full" aria-hidden="true">
            <path d={MAP.glacier} fill="none" stroke="#B9CBD6" strokeOpacity="0.3" strokeWidth="1" strokeLinejoin="round" />
            <path d={MAP.lagoon} fill="#B9CBD6" fillOpacity="0.16" stroke="#B9CBD6" strokeOpacity="0.4" strokeWidth="0.8" />
            <path d={MAP.coast} fill="none" stroke="#F4EEE2" strokeOpacity="0.4" strokeWidth="1.1" strokeLinejoin="round" />
            {places.map((p) => (
              <path
                key={p.key}
                data-drive
                d={p.route}
                pathLength={1}
                strokeDasharray="1"
                fill="none"
                stroke="#D97D3D"
                strokeWidth={active === p.key ? 3.4 : 2.2}
                strokeLinecap="round"
                strokeLinejoin="round"
                style={{
                  opacity: active && active !== p.key ? 0.22 : 0.95,
                  transition: 'opacity 200ms ease-out, stroke-width 200ms ease-out',
                }}
              />
            ))}
          </svg>

          {/* markers: HTML, so they keep their size when the SVG scales */}
          <div aria-hidden="true" translate="no" className="absolute inset-0">
            {places.map((p, i) => {
              const [dx, dy] = BADGE_OFFSET[p.key] ?? [0, 0]
              return (
                <span key={p.key} data-marker className="absolute" style={pct(p.x, p.y)}>
                  {dx || dy ? (
                    <>
                      <span className="absolute h-1.5 w-1.5 -translate-x-1/2 -translate-y-1/2 rounded-full bg-[#F4EEE2]" />
                      <span
                        className="absolute left-0 top-0 h-px origin-left bg-[#F4EEE2]/60"
                        style={{ width: Math.hypot(dx, dy), transform: `rotate(${Math.atan2(dy, dx)}rad)` }}
                      />
                    </>
                  ) : null}
                  <span
                    className="absolute grid h-5 w-5 place-items-center rounded-full font-fragment text-[10px] tabular-nums text-[#15130F] transition-colors duration-200 sm:h-6 sm:w-6 sm:text-[11px]"
                    style={{
                      transform: `translate(calc(-50% + ${dx}px), calc(-50% + ${dy}px))`,
                      background: active === p.key ? '#D97D3D' : '#F4EEE2',
                    }}
                  >
                    {i + 1}
                  </span>
                </span>
              )
            })}
            <span className="absolute left-[9%] top-[13%] font-erode text-sm font-light italic text-[#B9CBD6]/80 sm:text-lg">Vatnajökull</span>
            <span className="absolute bottom-[24%] right-[18%] font-erode text-sm font-light italic text-[#B9CBD6]/70 sm:text-lg">
              {t.journey.ocean}
            </span>
            <span className="absolute -translate-x-1/2 -translate-y-1/2" style={pct(MAP.farm.x, MAP.farm.y)}>
              <span className="relative block h-3.5 w-3.5 rounded-full bg-[#D97D3D] ring-4 ring-[#D97D3D]/25 sm:h-4 sm:w-4" />
              <span className="absolute bottom-full left-1/2 mb-2 -translate-x-1/2 whitespace-nowrap font-erode text-base font-light text-[#F4EEE2] [text-shadow:0_1px_8px_rgba(21,19,15,0.9)] sm:text-2xl">
                Nýpugarðar
              </span>
            </span>
          </div>

          {/* full-width row, so the bar's percentage is a percentage of the map */}
          <div className="pointer-events-none absolute inset-x-0 bottom-7 flex items-center justify-end gap-2 px-3 sm:bottom-9 sm:px-4" aria-hidden="true">
            <span className="block h-1.5 shrink-0 border-x border-b border-[#F4EEE2]/60" style={{ width: `${TEN_KM}%` }} />
            <span className="font-fragment text-[10px] uppercase tracking-[0.12em] text-[#F4EEE2]/70">10 km</span>
          </div>
          <a
            href="https://www.openstreetmap.org/copyright"
            target="_blank"
            rel="noreferrer"
            className="absolute bottom-1.5 right-2 bg-[#15130F]/70 px-1.5 py-0.5 text-[10px] text-[#F4EEE2]/70 hover:text-[#F4EEE2] sm:bottom-2 sm:right-3"
          >
            © OpenStreetMap
          </a>
        </div>
      </div>

      <h3 className="mt-10 font-erode text-2xl font-light md:text-3xl">{t.journey.drivesHeading}</h3>
      <ol className="mt-6 grid gap-x-8 sm:grid-cols-2 lg:grid-cols-3">
        {places.map((p, i) => {
          const place = t.journey.places[p.key]
          return (
            <li key={p.key} className="border-t" style={{ borderColor: HAIR }}>
              <button
                type="button"
                aria-pressed={active === p.key}
                onClick={() => setActive((a) => (a === p.key ? null : p.key))}
                onMouseEnter={() => setActive(p.key)}
                onMouseLeave={() => setActive(null)}
                onFocus={() => setActive(p.key)}
                onBlur={() => setActive(null)}
                className="flex w-full touch-manipulation gap-4 py-5 text-left focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#F4EEE2]"
              >
                <span
                  aria-hidden="true"
                  className="mt-0.5 grid h-6 w-6 shrink-0 place-items-center rounded-full font-fragment text-[11px] tabular-nums text-[#15130F] transition-colors duration-200"
                  style={{ background: active === p.key ? '#D97D3D' : '#F4EEE2' }}
                >
                  {i + 1}
                </span>
                <span className="min-w-0">
                  <span className="block font-erode text-xl font-light leading-tight" translate="no">
                    {place.name}
                  </span>
                  <span className="mt-1 block text-[15px] leading-snug text-[#F4EEE2]/70">{place.note}</span>
                  <span className="mt-2 block font-fragment text-[12px] uppercase tracking-[0.12em] tabular-nums text-[#D97D3D]">
                    {p.min} {t.journey.min} · {p.km} km
                  </span>
                </span>
              </button>
            </li>
          )
        })}
      </ol>
      <p className="mt-4 max-w-[70ch] text-sm leading-relaxed text-[#F4EEE2]/60">{t.journey.driveNote}</p>
    </div>
  )
}
