/* GENERATED from saja.is collections products.json (public Shopify JSON,
 * harvested 2026-08-04). Her REAL working shop -- silk scarves and cotton bags
 * printed with patterns drawn from her paintings. Titles, prices and variant
 * notes are hers, verbatim. Regenerate with scratchpad/shop-gen/build.py.
 * `matchedWork` links a product to a gallery painting of the same name -- only
 * set where the titles genuinely match, never guessed. */

export type ShopCat = 'slaedur' | 'toskur' | 'heimili' | 'mus'

export interface ShopProduct {
  id: string
  is: string
  en: string
  cat: ShopCat
  price: number
  variant: string
  image: string
  handle: string
  /** id of the matching gallery Work, when this product's pattern is a real painting in the gallery */
  matchedWork: string | null
}

export const SHOP_CAT_IS: Record<ShopCat, string> = {"slaedur": "Slæður", "toskur": "Töskur", "heimili": "Heimili", "mus": "Mús"}
export const SHOP_CAT_EN: Record<ShopCat, string> = {"slaedur": "Scarves", "toskur": "Bags", "heimili": "Home", "mus": "Mouse"}

export const SHOP_PRODUCTS: ShopProduct[] = [
  { id: '101-snyrtitaska-101-vanitybag', is: '101 Snyrtitaska', en: '101 Vanitybag', cat: 'toskur',
    price: 11900, variant: 'Default Title', image: '/asaja/shop/101-snyrtitaska-101-vanitybag.jpg', handle: '101-snyrtitaska-101-vanitybag',
    matchedWork: null },
  { id: 'untitled-apr7_08-56', is: '101 Stór taska', en: '101 Beach bag', cat: 'toskur',
    price: 23900, variant: 'Default Title', image: '/asaja/shop/untitled-apr7_08-56.jpg', handle: 'untitled-apr7_08-56',
    matchedWork: null },
  { id: '101-taska-101-tote', is: '101 taska', en: '101 Tote', cat: 'toskur',
    price: 14900, variant: 'Default Title', image: '/asaja/shop/101-taska-101-tote.jpg', handle: '101-taska-101-tote',
    matchedWork: null },
  { id: 'birki-birch', is: 'Birki', en: 'Birch', cat: 'slaedur',
    price: 23900, variant: '90x90cm', image: '/asaja/shop/birki-birch.jpg', handle: 'birki-birch',
    matchedWork: null },
  { id: 'birki-cosmetic-bag', is: 'Birki cosmetic bag', en: 'Birki cosmetic bag', cat: 'toskur',
    price: 11900, variant: 'Built-in compartments', image: '/asaja/shop/birki-cosmetic-bag.jpg', handle: 'birki-cosmetic-bag',
    matchedWork: null },
  { id: 'birki-day-bag', is: 'Birki day-bag', en: 'Birki day-bag', cat: 'toskur',
    price: 15500, variant: 'Snap', image: '/asaja/shop/birki-day-bag.jpg', handle: 'birki-day-bag',
    matchedWork: null },
  { id: 'birki-taska-stor', is: 'Birki taska - stór', en: 'Birch beach bag', cat: 'toskur',
    price: 23900, variant: 'Cotton Duck', image: '/asaja/shop/birki-taska-stor.jpg', handle: 'birki-taska-stor',
    matchedWork: null },
  { id: 'blek-snyrtitaska-ink-cosmetics-bag', is: 'Blek snyrtitaska', en: 'Ink Cosmetics bag', cat: 'toskur',
    price: 11900, variant: 'Default Title', image: '/asaja/shop/blek-snyrtitaska-ink-cosmetics-bag.jpg', handle: 'blek-snyrtitaska-ink-cosmetics-bag',
    matchedWork: null },
  { id: 'untitled-jul30_23-13-01', is: 'Gola', en: 'Breeze', cat: 'slaedur',
    price: 23900, variant: 'Default Title', image: '/asaja/shop/untitled-jul30_23-13-01.jpg', handle: 'untitled-jul30_23-13-01',
    matchedWork: null },
  { id: 'gramosi-viskustykki-grey-moss-dishtowel', is: 'Grámosi Viskustykki', en: 'Grey moss Dishtowel', cat: 'heimili',
    price: 3900, variant: 'Default Title', image: '/asaja/shop/gramosi-viskustykki-grey-moss-dishtowel.jpg', handle: 'gramosi-viskustykki-grey-moss-dishtowel',
    matchedWork: null },
  { id: 'green-lychen', is: 'Grænar skófir', en: 'Green Lychen', cat: 'slaedur',
    price: 24500, variant: '90x90cm', image: '/asaja/shop/green-lychen.jpg', handle: 'green-lychen',
    matchedWork: null },
  { id: 'gular-skofir-taska-yellow-lychen-bag', is: 'Gular skófir taska', en: 'Yellow lychen bag', cat: 'toskur',
    price: 24500, variant: 'Default Title', image: '/asaja/shop/gular-skofir-taska-yellow-lychen-bag.jpg', handle: 'gular-skofir-taska-yellow-lychen-bag',
    matchedWork: null },
  { id: 'gular-skofir-viskustykki-yellow-lichen-dishcloth', is: 'Gular skófir viskustykki', en: 'Yellow lichen dishcloth', cat: 'heimili',
    price: 3900, variant: 'Default Title', image: '/asaja/shop/gular-skofir-viskustykki-yellow-lichen-dishcloth.jpg', handle: 'gular-skofir-viskustykki-yellow-lichen-dishcloth',
    matchedWork: null },
  { id: 'himinn-sky', is: 'Himinn', en: 'Sky', cat: 'slaedur',
    price: 23900, variant: 'Default Title', image: '/asaja/shop/himinn-sky.jpg', handle: 'himinn-sky',
    matchedWork: null },
  { id: 'jord-gravel', is: 'Jörð', en: 'Gravel', cat: 'slaedur',
    price: 23900, variant: 'Default Title', image: '/asaja/shop/jord-gravel.jpg', handle: 'jord-gravel',
    matchedWork: null },
  { id: 'lauga-snyrtitaska-lauga-cosmetics-bag', is: 'Lauga snyrtitaska', en: 'Lauga cosmetics bag', cat: 'toskur',
    price: 11900, variant: 'Default Title', image: '/asaja/shop/lauga-snyrtitaska-lauga-cosmetics-bag.jpg', handle: 'lauga-snyrtitaska-lauga-cosmetics-bag',
    matchedWork: null },
  { id: 'djupid-stor-taska', is: 'Lauga stór taska', en: 'Lauga beach bag', cat: 'toskur',
    price: 23900, variant: 'Default Title', image: '/asaja/shop/djupid-stor-taska.jpg', handle: 'djupid-stor-taska',
    matchedWork: null },
  { id: 'djupid-taska-djup-day-bag', is: 'Lauga taska', en: 'Lauga day bag', cat: 'toskur',
    price: 14900, variant: 'Multicolor / Shoulder strap', image: '/asaja/shop/djupid-taska-djup-day-bag.jpg', handle: 'djupid-taska-djup-day-bag',
    matchedWork: null },
  { id: 'lauga-viskustykki-dishcloth', is: 'Lauga Viskustykki', en: 'Dishcloth', cat: 'heimili',
    price: 3900, variant: 'Default Title', image: '/asaja/shop/lauga-viskustykki-dishcloth.jpg', handle: 'lauga-viskustykki-dishcloth',
    matchedWork: null },
  { id: 'primary-leaves', is: 'Litrík Lauf', en: 'Primary Leaves', cat: 'slaedur',
    price: 23900, variant: 'Silk Satin', image: '/asaja/shop/primary-leaves.jpg', handle: 'primary-leaves',
    matchedWork: null },
  { id: 'lyng-lyng', is: 'Lyng', en: 'Lyng', cat: 'slaedur',
    price: 24500, variant: 'Default Title', image: '/asaja/shop/lyng-lyng.jpg', handle: 'lyng-lyng',
    matchedWork: 'lyng-eftirprent' },
  { id: 'untitled-dec10_10-18', is: 'LYNG Taska', en: 'Beach bag', cat: 'toskur',
    price: 24900, variant: 'Default Title', image: '/asaja/shop/untitled-dec10_10-18.jpg', handle: 'untitled-dec10_10-18',
    matchedWork: 'lyng-eftirprent' },
  { id: 'untitled-jul30_22-59-59', is: 'Mosi', en: 'Moss 60x60cm', cat: 'slaedur',
    price: 16900, variant: 'Default Title', image: '/asaja/shop/untitled-jul30_22-59-59.jpg', handle: 'untitled-jul30_22-59-59',
    matchedWork: null },
  { id: 'mosi-day-bag', is: 'Mosi day bag', en: 'Mosi day bag', cat: 'toskur',
    price: 15500, variant: 'Cotton Duck / Dry clean only / Shoulder strap', image: '/asaja/shop/mosi-day-bag.jpg', handle: 'mosi-day-bag',
    matchedWork: null },
  { id: 'mosi-snyrtitaska-moss-cosmetics-bag', is: 'Mosi snyrtitaska', en: 'Moss cosmetics bag', cat: 'toskur',
    price: 11900, variant: 'Zipper / Cotton Duck', image: '/asaja/shop/mosi-snyrtitaska-moss-cosmetics-bag.jpg', handle: 'mosi-snyrtitaska-moss-cosmetics-bag',
    matchedWork: null },
  { id: 'mosi-taska-stor', is: 'Mosi taska -stór', en: 'Mosi taska -stór', cat: 'toskur',
    price: 24900, variant: 'Zipper / Multicolor / Shoulder strap', image: '/asaja/shop/mosi-taska-stor.jpg', handle: 'mosi-taska-stor',
    matchedWork: null },
  { id: 'mus-svort-med-turkis-eyru', is: 'Mús', en: 'Svört með túrkis eyru', cat: 'mus',
    price: 3900, variant: 'Default Title', image: '/asaja/shop/mus-svort-med-turkis-eyru.jpg', handle: 'mus-svort-med-turkis-eyru',
    matchedWork: null },
  { id: 'nattura-snyrtitaska-nature-cosmetics-bag', is: 'Náttúra snyrtitaska', en: 'Nature cosmetics bag', cat: 'toskur',
    price: 11900, variant: 'Zipper', image: '/asaja/shop/nattura-snyrtitaska-nature-cosmetics-bag.jpg', handle: 'nattura-snyrtitaska-nature-cosmetics-bag',
    matchedWork: null },
  { id: 'oliva-stor-taska-olive-beach-bag', is: 'Ólífa stór taska', en: 'Olive beach bag', cat: 'toskur',
    price: 23900, variant: 'Default Title', image: '/asaja/shop/oliva-stor-taska-olive-beach-bag.jpg', handle: 'oliva-stor-taska-olive-beach-bag',
    matchedWork: 'olifa' },
  { id: 'oliva-taska-olive-day-bag', is: 'Ólífa taska', en: 'Olive day bag', cat: 'toskur',
    price: 15500, variant: 'Default Title', image: '/asaja/shop/oliva-taska-olive-day-bag.jpg', handle: 'oliva-taska-olive-day-bag',
    matchedWork: 'olifa' },
  { id: 'oliva-viskustykki-olive-dishcloth', is: 'Ólíva viskustykki', en: 'Olive dishcloth', cat: 'heimili',
    price: 3900, variant: 'Default Title', image: '/asaja/shop/oliva-viskustykki-olive-dishcloth.jpg', handle: 'oliva-viskustykki-olive-dishcloth',
    matchedWork: null },
  { id: 'pastel-leaves', is: 'Pastel lauf', en: 'Pastel Leaves', cat: 'slaedur',
    price: 23900, variant: 'Default Title', image: '/asaja/shop/pastel-leaves.jpg', handle: 'pastel-leaves',
    matchedWork: null },
  { id: 'sandur-sand', is: 'Sandur', en: 'Sand', cat: 'slaedur',
    price: 23900, variant: '90x90cm', image: '/asaja/shop/sandur-sand.jpg', handle: 'sandur-sand',
    matchedWork: null },
  { id: 'sandur-taska-sand-beach-bag', is: 'Sandur taska', en: 'Sand beach bag', cat: 'toskur',
    price: 23900, variant: 'Default Title', image: '/asaja/shop/sandur-taska-sand-beach-bag.jpg', handle: 'sandur-taska-sand-beach-bag',
    matchedWork: null },
  { id: 'selir-seals', is: 'SELIR', en: 'SEALS', cat: 'toskur',
    price: 24900, variant: 'Default Title', image: '/asaja/shop/selir-seals.jpg', handle: 'selir-seals',
    matchedWork: null },
  { id: 'svort-mus-black-mouse', is: 'Svört mús', en: 'Black mouse', cat: 'mus',
    price: 3900, variant: 'Default Title', image: '/asaja/shop/svort-mus-black-mouse.jpg', handle: 'svort-mus-black-mouse',
    matchedWork: null },
  { id: 'svort-olifa-stor-taska-black-olive-beach-bag', is: 'Svört ólífa stór taska', en: 'Black olive beach bag', cat: 'toskur',
    price: 23900, variant: 'Multicolor', image: '/asaja/shop/svort-olifa-stor-taska-black-olive-beach-bag.jpg', handle: 'svort-olifa-stor-taska-black-olive-beach-bag',
    matchedWork: 'olifa' },
  { id: 'svort-olifa-taska-black-olive-day-bag', is: 'Svört ólífa taska', en: 'Black olive day bag', cat: 'toskur',
    price: 15500, variant: 'Multicolor', image: '/asaja/shop/svort-olifa-taska-black-olive-day-bag.jpg', handle: 'svort-olifa-taska-black-olive-day-bag',
    matchedWork: 'olifa' },
]
