import { useCallback, useEffect, useLayoutEffect, useMemo, useRef, useState } from 'react'
import type { FormEvent, ReactNode } from 'react'
import { Search, SlidersHorizontal, X, Sun, Moon, Monitor, Heart, Phone, MapPin, ArrowRight, ArrowLeft, ChevronLeft, ChevronRight, Check, Plus, Share2, Maximize2, Scale, Mail, Clock, Menu, CarFront, Fuel, Gauge, CalendarDays, CircleHelp } from 'lucide-react'
import Lenis from 'lenis'
import { Wordmark } from './Wordmark'
import { LoadingScreen } from './Motion'
import { useShowroomMotion } from './useShowroomMotion'
import { useOpeningReady } from './useOpeningReady'
import { asset, carTitle, cashURL, driveLabel, filterCars, filterNames, fuelLabel, keys, mileage, price, sellURL } from './data'
import type { Car, FilterKey } from './data'

const isTouch=()=>navigator.maxTouchPoints>0||'ontouchstart' in window
function readParams(){const p=new URLSearchParams(location.search);for(const k of ['min','max','yearMin','yearMax','kmMax','limit']){if(p.has(k)&&!/^\d{1,9}$/.test(p.get(k)||''))p.delete(k)}return p}
function readList(key:string):string[]{try{const v=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(v)?[...new Set(v.filter(x=>typeof x==='string'))].slice(0,key==='bm-compare'?3:1000):[]}catch{return []}}
function usePersistentList(key:string){const [list,setList]=useState(()=>readList(key));useEffect(()=>{try{localStorage.setItem(key,JSON.stringify(list))}catch{/* Storage is optional. */}},[key,list]);return [list,setList] as const}
function useTheme(){
 const [preference,setPreference]=useState(()=>{try{const p=localStorage.getItem('bm-theme');return p==='light'||p==='dark'||p==='system'?p:'light'}catch{return 'light'}})
 const [darkSystem,setDarkSystem]=useState(()=>matchMedia('(prefers-color-scheme: dark)').matches)
 const theme=preference==='system'?(darkSystem?'dark':'light'):preference
 useEffect(()=>{const m=matchMedia('(prefers-color-scheme: dark)');const fn=()=>setDarkSystem(m.matches);m.addEventListener('change',fn);const sync=(e:StorageEvent)=>{if(e.key==='bm-theme'||e.key===null)setPreference(e.newValue==='dark'||e.newValue==='light'||e.newValue==='system'?e.newValue:'light')};window.addEventListener('storage',sync);return()=>{m.removeEventListener('change',fn);window.removeEventListener('storage',sync)}},[])
 useLayoutEffect(()=>{document.documentElement.dataset.theme=theme;document.documentElement.style.colorScheme=theme;document.querySelector('meta[name="theme-color"]')?.setAttribute('content',theme==='dark'?'#0A0C10':'#FFFFFF')},[theme])
 function choose(p:string){setPreference(p);try{localStorage.setItem('bm-theme',p)}catch{/* Keep working without storage. */}}
 return {theme,preference,choose}
}
function Modal({title,children,onClose,wide=false}:{title:string;children:ReactNode;onClose:()=>void;wide?:boolean}){
 const ref=useRef<HTMLDialogElement>(null)
 const [confirmClose,setConfirmClose]=useState(false)
 const close=()=>{if(ref.current?.querySelector('[data-dirty="true"]')){setConfirmClose(true);return}onClose()}
 useLayoutEffect(()=>{
  const d=ref.current!;const before=document.activeElement as HTMLElement;const y=scrollY
  d.showModal();document.body.style.position='fixed';document.body.style.top=`-${y}px`;document.body.style.width='100%';document.documentElement.dataset.dialog='true'
  return()=>{d.close();document.body.style.position='';document.body.style.top='';document.body.style.width='';delete document.documentElement.dataset.dialog;window.scrollTo({top:y,behavior:'instant'});if(before?.isConnected)before.focus({preventScroll:true})}
 },[])
 return <dialog ref={ref} className={`bm-dialog ${wide?'bm-dialog-wide':''}`} aria-label={title} onCancel={e=>{e.preventDefault();close()}} onClick={e=>{if(e.target===e.currentTarget)close()}}><div className="bm-dialog-inner"><div className="bm-dialog-head"><h2>{title}</h2><button className="bm-icon" aria-label="Loka glugga" onClick={close} autoFocus><X aria-hidden="true"/></button></div>{confirmClose&&<div className="bm-discard" role="alertdialog" aria-label="Sleppa ósendri beiðni?"><h3>Beiðnin hefur ekki verið send.</h3><p>Viltu halda áfram að fylla hana út eða loka og sleppa upplýsingunum?</p><button className="bm-button primary" autoFocus onClick={()=>setConfirmClose(false)}>Halda áfram</button><button className="bm-button" onClick={onClose}>Sleppa og loka</button></div>}<div hidden={confirmClose}>{children}</div></div></dialog>
}
function VehicleImage({src,alt,eager=false,className=''}:{src:string;alt:string;eager?:boolean;className?:string}){
 const [failed,setFailed]=useState(false)
 useEffect(()=>setFailed(false),[src])
 return failed?<div className={`bm-image-fallback ${className}`}><CarFront aria-hidden="true"/><span>Mynd ekki tiltæk</span></div>:<img className={className} src={asset(src)} alt={alt} width="1280" height="1024" loading={eager?'eager':'lazy'} fetchPriority={eager?'high':undefined} decoding="async" onError={()=>setFailed(true)}/>
}
function Snapshot(){return <p className="bm-snapshot"><span/>Frumgerð · Söluskrá frá 1. október 2026. Staðfestu verð og framboð hjá Bílamiðstöðinni.</p>}
function Facts({car}:{car:Car}){return <dl className="bm-facts"><div><dt><CalendarDays aria-hidden="true"/>Nýskráning</dt><dd>{car.year?car.registration:'Ekki tilgreint'}</dd></div><div><dt><Gauge aria-hidden="true"/>Akstur</dt><dd>{mileage(car)}</dd></div><div><dt><Fuel aria-hidden="true"/>Orkugjafi</dt><dd>{fuelLabel(car)}</dd></div><div><dt><CarFront aria-hidden="true"/>Skipting</dt><dd>{car.transmission||'Ekki tilgreint'}</dd></div></dl>}
function Price({car,large=false}:{car:Car;large?:boolean}){return <div className={`bm-price ${large?'bm-price-large':''}`}><strong>{car.price?price(car.price):'Hafðu samband um verð'}</strong>{car.priceNote&&<span>{car.priceNote}</span>}</div>}

export default function Page(){
 const [params,setParams]=useState(readParams)
 const [cars,setCars]=useState<Car[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState(false);const [attempt,setAttempt]=useState(0)
 const [saved,setSaved]=usePersistentList('bm-saved');const [compare,setCompare]=usePersistentList('bm-compare')
 const {theme,preference,choose}=useTheme();const [modal,setModal]=useState<'menu'|'filters'|'theme'|'enquiry'|'gallery'|null>(null)
 const [notice,setNotice]=useState('');const [galleryIndex,setGalleryIndex]=useState(0);const [heroIndex,setHeroIndex]=useState(0)
 const rootRef=useRef<HTMLDivElement>(null);const restoration=useRef<number|null>(null);const lenisRef=useRef<Lenis|null>(null)
 const view=params.get('view')||'home';const car=cars.find(c=>c.id===params.get('car'))
 const notify=useCallback((message:string)=>setNotice(message),[])
 useEffect(()=>{if(!notice)return;const id=setTimeout(()=>setNotice(''),4000);return()=>clearTimeout(id)},[notice])
 useEffect(()=>{const abort=new AbortController();let timedOut=false;const timeout=setTimeout(()=>{timedOut=true;abort.abort()},15000);setLoading(true);setError(false);fetch(asset('./inventory.json'),{signal:abort.signal}).then(r=>{if(!r.ok)throw Error('inventory');return r.json()}).then(data=>{if(!Array.isArray(data)||!data.length)throw Error('inventory');setCars(data);setLoading(false)}).catch(e=>{if(timedOut||e.name!=='AbortError'){setError(true);setLoading(false)}}).finally(()=>clearTimeout(timeout));return()=>{clearTimeout(timeout);abort.abort()}},[attempt])
 useEffect(()=>{const prev=history.scrollRestoration;history.scrollRestoration='manual';const onPop=()=>{restoration.current=history.state?.bmScroll||0;setParams(readParams());setModal(null)};window.addEventListener('popstate',onPop);return()=>{history.scrollRestoration=prev;window.removeEventListener('popstate',onPop)}},[])
 useLayoutEffect(()=>{if(restoration.current!==null&&!loading){const y=restoration.current;const id=requestAnimationFrame(()=>{lenisRef.current?.scrollTo(y,{immediate:true});window.scrollTo({top:y,behavior:'instant'});restoration.current=null});return()=>cancelAnimationFrame(id)}},[params,loading])
 useEffect(()=>{
  const media=matchMedia('(prefers-reduced-motion: reduce)');const pointer=matchMedia('(pointer: fine)')
  let frame=0
  const setup=()=>{cancelAnimationFrame(frame);lenisRef.current?.destroy();lenisRef.current=null;if(media.matches||isTouch()||!pointer.matches)return
   const lenis=isTouch()?null:new Lenis({lerp:.2,smoothWheel:true,anchors:true,prevent:node=>node.closest('dialog')!==null});if(!lenis)return;lenisRef.current=lenis
   const raf=(t:number)=>{lenis.raf(t);frame=requestAnimationFrame(raf)};frame=requestAnimationFrame(raf)
  };setup();media.addEventListener('change',setup);pointer.addEventListener('change',setup);return()=>{cancelAnimationFrame(frame);lenisRef.current?.destroy();lenisRef.current=null;media.removeEventListener('change',setup);pointer.removeEventListener('change',setup)}
 },[])
 useEffect(()=>{if(modal)lenisRef.current?.stop();else lenisRef.current?.start()},[modal])
 useEffect(()=>{const h=document.querySelector<HTMLElement>('#bm-main h1');if(h){h.tabIndex=-1;h.focus({preventScroll:true})}},[view,car?.id])
 useEffect(()=>{document.title=car?`${carTitle(car)} · ${car.price?price(car.price):'Hafðu samband um verð'} · Bílamiðstöðin`:'Bílamiðstöðin · Finndu næsta bíl';setGalleryIndex(0)},[car])
 function navigate(next:URLSearchParams,restoreY=0){if(document.querySelector('[data-dirty="true"]')&&!window.confirm('Upplýsingarnar hafa ekki verið sendar. Viltu halda áfram og sleppa þeim?'))return;history.replaceState({...history.state,bmScroll:scrollY},'',location.href);history.pushState({bmScroll:0},'',`${location.pathname}${next.size?'?'+next:''}`);restoration.current=restoreY;setParams(next);setModal(null)}
 function go(nextView:string){const p=new URLSearchParams();if(nextView!=='home')p.set('view',nextView);navigate(p)}
 function update(key:string,value:string){if(['min','max','yearMin','yearMax','kmMax'].includes(key)&&value&&!/^\d+$/.test(value))return;const p=new URLSearchParams(params);if(value)p.set(key,value);else p.delete(key);if(key==='make')p.delete('model');p.delete('limit');history.replaceState({...history.state},'',`${location.pathname}${p.size?'?'+p:''}`);setParams(p)}
 function reset(){const p=new URLSearchParams();if(view==='saved')p.set('view','saved');else if(view!=='home')p.set('view','cars');history.replaceState({},'',`${location.pathname}${p.size?'?'+p:''}`);setParams(p)}
 function openCar(c:Car){const p=new URLSearchParams(params);p.set('car',c.id);navigate(p)}
 function backToCars(){const origin=history.state?.bmOrigin;if(origin){navigate(new URLSearchParams(origin.search),origin.scroll);return}const p=new URLSearchParams(params);p.delete('car');p.set('view','cars');navigate(p)}
 function detail(c:Car){const origin=car?history.state?.bmOrigin:{search:location.search,scroll:scrollY};openCar(c);history.replaceState({...history.state,bmOrigin:origin},'',location.href)}
 function toggleSave(id:string){setSaved(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);notify(saved.includes(id)?'Bíll fjarlægður úr völdum bílum.':'Bíll vistaður í völdum bílum.')}
 function toggleCompare(id:string){if(compare.includes(id)){setCompare(v=>v.filter(x=>x!==id));return}if(compare.length>=3){notify('Þú getur borið saman allt að þrjá bíla. Fjarlægðu einn til að bæta öðrum við.');return}setCompare(v=>[...v,id])}
 async function share(){try{await navigator.clipboard.writeText(location.href);notify('Slóð afrituð. Leitin þín fylgir með.')}catch{notify('Ekki tókst að afrita. Þú getur afritað slóðina úr veffangastikunni.')}}
 const source=view==='saved'?cars.filter(c=>saved.includes(c.id)):cars
 const results=useMemo(()=>filterCars(source,params),[source,params])
 const active=keys.filter(k=>params.get(k));const compareCars=cars.filter(c=>compare.includes(c.id))
 const limit=Math.max(12,Math.min(cars.length,Number(params.get('limit'))||12))
 const heroCars=cars.filter(c=>['153689','407501','371481'].includes(c.id));const hero=heroCars[heroIndex%Math.max(1,heroCars.length)]
 const invalidRange=(params.get('min')&&params.get('max')&&Number(params.get('min'))>Number(params.get('max')))||(params.get('yearMin')&&params.get('yearMax')&&Number(params.get('yearMin'))>Number(params.get('yearMax')))
 const jumpInventory=()=>{const el=document.getElementById('bilar');if(el){if(lenisRef.current)lenisRef.current.scrollTo(el,{offset:-88});else el.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}else go('cars')}
 const openingImages=[asset('./logo.png'),...(car?[asset(car.photos[0])]:['home','cars','saved'].includes(view)?[...(view==='home'&&hero&&matchMedia('(min-width:641px)').matches?[asset(hero.photos[0])]:[]),...results.slice(0,2).map(c=>asset(c.photos[0]))]:[])]
 const openingReady=useOpeningReady(attempt,loading,openingImages)
 useShowroomMotion(rootRef,`${view}:${car?.id||''}`,results.slice(0,limit).map(c=>c.id).join(','),!loading&&openingReady)
 const InventoryHeading=view==='home'?'h2':'h1'
 const filters=(advanced=false)=> <Filters cars={cars} params={params} update={update} advanced={advanced}/>
 if(loading||!openingReady)return <LoadingScreen/>
 return <div className="bm-app" ref={rootRef}>
  <a className="bm-skip" href="#bm-main">Fara í efni</a><div className="bm-awning" aria-hidden="true"/>
  <header className="bm-header"><div className="bm-header-inner">
   <a className="bm-logo" href="?" aria-label="Bílamiðstöðin, forsíða" onClick={e=>{if(e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;e.preventDefault();go('home')}}><Wordmark/></a>
   <nav aria-label="Aðalvalmynd" className="bm-desktop-nav"><a href="?view=cars" aria-current={view==='cars'?'page':undefined} onClick={e=>{if(e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;e.preventDefault();go('cars')}}>Bílar til sölu</a><a href="?view=cash" onClick={e=>{if(e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;e.preventDefault();go('cash')}}>Kaupum bíla</a><a href="?view=sell" onClick={e=>{if(e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;e.preventDefault();go('sell')}}>Selja bíl</a><a href="?view=finance" onClick={e=>{if(e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;e.preventDefault();go('finance')}}>Fjármögnun</a><a href="?view=about" onClick={e=>{if(e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;e.preventDefault();go('about')}}>Um okkur</a></nav>
   <div className="bm-header-actions"><button className="bm-icon bm-saved-nav" onClick={()=>go('saved')} aria-label={`Valdir bílar, ${saved.length}`}><Heart aria-hidden="true"/>{saved.length>0&&<b>{saved.length}</b>}</button><button className="bm-theme-switch" role="switch" aria-checked={theme==='dark'} aria-label="Dökkt útlit" title={theme==='dark'?'Skipta í ljóst útlit':'Skipta í dökkt útlit'} onClick={()=>choose(theme==='dark'?'light':'dark')}><span className="bm-theme-track"><Sun aria-hidden="true"/><Moon aria-hidden="true"/><span className="bm-theme-thumb"/></span></button><a className="bm-header-phone" href="tel:+3545174500"><Phone aria-hidden="true" size={16}/>517 4500</a><button className="bm-icon bm-menu-trigger" aria-label="Opna valmynd" onClick={()=>setModal('menu')}><Menu aria-hidden="true"/></button></div>
  </div></header>
  <main id="bm-main">
  {error?<section className="bm-empty bm-container"><h1>Söluskráin hlóðst ekki.</h1><p>Athugaðu nettenginguna og reyndu aftur.</p><button className="bm-button primary" onClick={()=>setAttempt(x=>x+1)}>Reyna aftur</button><a href="https://www.bilamidstodin.is/">Opna söluskrá Bílamiðstöðvarinnar</a></section>:car?<>
   <div className="bm-container bm-detail-top"><button className="bm-text-button" onClick={backToCars}><ArrowLeft aria-hidden="true"/>Til baka í leit</button><button className="bm-text-button" onClick={share}><Share2 aria-hidden="true"/>Deila bíl</button></div>
   <section className="bm-container bm-detail">
    <div className="bm-gallery"><div className="bm-gallery-main"><button className="bm-gallery-expand" aria-label="Stækka mynd" onClick={()=>setModal('gallery')}><VehicleImage src={car.photos[galleryIndex]} alt={`${carTitle(car)}, mynd ${galleryIndex+1}`} eager/></button><div className="bm-photo-tools"><button className="bm-icon" aria-label="Fyrri mynd" onClick={()=>setGalleryIndex(i=>(i-1+car.photos.length)%car.photos.length)}><ChevronLeft aria-hidden="true"/></button><span>{galleryIndex+1} / {car.photos.length}</span><button className="bm-icon" aria-label="Næsta mynd" onClick={()=>setGalleryIndex(i=>(i+1)%car.photos.length)}><ChevronRight aria-hidden="true"/></button><button className="bm-icon" aria-label="Stækka myndasafn" onClick={()=>setModal('gallery')}><Maximize2 aria-hidden="true"/></button></div></div><div className="bm-thumbnails" aria-label="Myndir bíls">{car.photos.slice(0,6).map((src,i)=><button key={src} aria-label={`Sýna mynd ${i+1}`} aria-pressed={galleryIndex===i} onClick={()=>setGalleryIndex(i)}><VehicleImage src={src} alt=""/></button>)}{car.photos.length>6&&<button onClick={()=>setModal('gallery')}>Allar {car.photos.length}</button>}</div></div>
    <div className="bm-detail-summary"><div className="bm-topline"><span>{car.type} · Raðnúmer {car.id}</span>{car.offer&&<span className="bm-offer">Tilboð</span>}</div><h1>{carTitle(car)}</h1><p className="bm-trim">{car.trim}</p><Price car={car} large/><Facts car={car}/><div className="bm-inline-facts"><span>{driveLabel(car)}</span><span>{car.seats?`${car.seats} sæti`:'Sæti ekki tilgreind'}</span></div><p className="bm-location"><MapPin aria-hidden="true" size={17}/>{car.location||'Staðsetning ekki tilgreind. Hafðu samband áður en þú kemur.'}</p><button className="bm-button primary" onClick={()=>setModal('enquiry')}><Mail aria-hidden="true"/>Fyrirspurn um þennan bíl</button><div className="bm-detail-actions"><a className="bm-button" href="tel:+3545174500"><Phone aria-hidden="true" size={17}/>517 4500</a><button className="bm-button" aria-pressed={saved.includes(car.id)} onClick={()=>toggleSave(car.id)}><Heart aria-hidden="true" fill={saved.includes(car.id)?'currentColor':'none'}/>{saved.includes(car.id)?'Vistaður':'Vista bíl'}</button></div><button className="bm-text-button" aria-pressed={compare.includes(car.id)} onClick={()=>toggleCompare(car.id)}><Scale aria-hidden="true"/>{compare.includes(car.id)?'Fjarlægja úr samanburði':'Bæta í samanburð'}</button><Snapshot/></div>
   </section>
   <section className="bm-container bm-detail-content"><div><h2>Það sem fylgir bílnum</h2>{car.notes.length>0?<div className="bm-seller-notes"><h3>Upplýsingar frá seljanda</h3>{car.notes.map(n=><p key={n}>{n}</p>)}</div>:<p>Frekari lýsing seljanda er ekki tilgreind.</p>}<Equipment car={car}/></div><aside><h2>Nánari upplýsingar</h2><dl className="bm-specs">{Object.entries(car.specs).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v||'Ekki tilgreint'}</dd></div>)}</dl><p className="bm-help"><CircleHelp aria-hidden="true"/>Láttu skoða ástand ökutækisins fyrir kaup. Staðfestu búnað og ástand áður en gengið er frá viðskiptum.</p><a href={car.source} target="_blank" rel="noreferrer" className="bm-text-button">Sjá upprunalega auglýsingu <ArrowRight aria-hidden="true"/></a></aside></section>
   <section className="bm-container bm-related"><h2>Fleiri bílar til að skoða</h2><div className="bm-results">{cars.filter(c=>c.id!==car.id&&c.type===car.type).sort((a,b)=>Math.abs(a.price-car.price)-Math.abs(b.price-car.price)).slice(0,2).map(c=><VehicleCard key={c.id} car={c} saved={saved.includes(c.id)} comparing={compare.includes(c.id)} onOpen={()=>detail(c)} onSave={()=>toggleSave(c.id)} onCompare={()=>toggleCompare(c.id)}/>)}</div></section>
  </>:params.get('car')?<section className="bm-empty bm-container"><h1>Bíllinn fannst ekki.</h1><p>Þessi bíll er ekki í söluskrá frumgerðarinnar.</p><button className="bm-button primary" onClick={()=>go('cars')}>Skoða alla bíla</button></section>:view==='cash'||view==='sell'?<SellPage key={view} kind={view}/>:view==='finance'?<Finance/>:view==='about'?<About/>:view==='compare'?<Compare cars={compareCars} onEnquire={()=>setModal('enquiry')} onRemove={toggleCompare} onOpen={detail} goCars={()=>go('cars')}/>:<>
  {view==='home'&&hero&&<section className="bm-hero"><div className="bm-hero-copy"><div className="bm-hero-location"><MapPin aria-hidden="true" size={16}/>Krókhálsi 7 · Reykjavík</div><h1>ÞÍN LEIÐ.<br/><span>ÞINN BÍLL.</span></h1><p>Veldu eftir þínum þörfum.<br/>Skoðaðu úrvalið, berðu saman og finndu þinn bíl.</p><button className="bm-button primary" onClick={jumpInventory}>Skoða bílana <ArrowRight aria-hidden="true"/></button><div className="bm-hero-hours"><Clock aria-hidden="true" size={16}/>Mánudaga til föstudaga · 10–18</div></div><div className="bm-hero-showroom"><div className="bm-hero-media"><VehicleImage src={hero.photos[0]} alt={carTitle(hero)} eager/></div><div className="bm-hero-caption"><button onClick={()=>detail(hero)}><span>{carTitle(hero)}</span><strong>{hero.price?price(hero.price):'Verð eftir samkomulagi'}</strong><ArrowRight aria-hidden="true"/></button><div className="bm-hero-controls"><button className="bm-icon" aria-label="Fyrri bíll" onClick={()=>setHeroIndex(i=>(i-1+heroCars.length)%heroCars.length)}><ChevronLeft aria-hidden="true"/></button><span>0{heroIndex%heroCars.length+1} / 0{heroCars.length}</span><button className="bm-icon" aria-label="Næsti bíll" onClick={()=>setHeroIndex(i=>(i+1)%heroCars.length)}><ChevronRight aria-hidden="true"/></button></div></div></div></section>}
  <section id="bilar" className={`bm-inventory bm-container ${view!=='home'?'bm-inventory-page':''}`}>
   <div className="bm-section-head"><div><InventoryHeading className="bm-inventory-title">{view==='saved'?'VALDIR BÍLAR':'FINNDU ÞINN BÍL.'}</InventoryHeading><p>{view==='saved'?'Bílarnir sem þú hefur vistað í þessum vafra.':'Leitaðu, veldu og berðu saman.'}</p></div><button className="bm-text-button" onClick={share}><Share2 aria-hidden="true"/>Deila leit</button></div>
   <div className="bm-needs" aria-label="Leita eftir þörfum">{[["max","2000000","Allt að 2 milljónum"],["seats","7","Fyrir stærri fjölskyldu"],["type","Sendibílar","Fyrir vinnuna"],["fuel","Rafmagn","Á rafmagni"]].map(([key,value,label])=><button key={label} aria-pressed={params.get(key)===value} onClick={()=>{const p=new URLSearchParams();p.set(key,value);p.set("view",view==="saved"?"saved":"cars");navigate(p)}}><span>{label}</span><small>{filterCars(source,new URLSearchParams([[key,value]])).length} í söluskrá</small><ArrowRight aria-hidden="true" size={17}/></button>)}</div><div className="bm-search-sticky"><div className="bm-search-input"><Search aria-hidden="true"/><input aria-label="Leita í söluskrá" placeholder="T.d. jeppi, 7 sæta, rafmagn undir 5 milljónum" value={params.get('q')||''} onChange={e=>update('q',e.target.value)} type="search" name="q" autoComplete="off"/>{params.get('q')&&<button className="bm-icon" onClick={()=>update('q','')} aria-label="Hreinsa leitarorð"><X aria-hidden="true"/></button>}</div><button className="bm-button bm-filter-trigger" onClick={()=>setModal('filters')}><SlidersHorizontal aria-hidden="true"/>Síur{active.length>0&&<b>{active.length}</b>}</button></div>
   <div className="bm-quick" aria-label="Flýtival">{[['','Allt'],['Jeppar','Jeppar'],['Rafmagn','Rafmagn'],['Tengiltvinn','Tengiltvinn'],['7','7+ sæta'],['Sendibílar','Sendibílar'],['Pallbílar','Pallbílar'],['Ferðatæki','Ferðatæki'],['Bifhjól','Bifhjól'],['Annað','Annað'],['offer','Tilboð']].map(([value,label])=>{const k=value==='Rafmagn'||value==='Tengiltvinn'?'fuel':value==='7'?'seats':value==='Fjórhjóladrif'?'drive':value==='offer'?'offer':'type';const v=value==='offer'?'1':value;const checked=value?params.get(k)===v:!active.length;const test=new URLSearchParams();if(value)test.set(k,v);return <button key={label} aria-pressed={checked} onClick={()=>value?update(k,checked?'':v):reset()}>{label}<span>{filterCars(source,test).length}</span></button>})}</div>
   <div className="bm-desktop-filters">{filters()}<details><summary><SlidersHorizontal aria-hidden="true" size={16}/>Fleiri síur</summary>{filters(true)}</details></div>
   {active.length>0&&<div className="bm-active-filters">{active.map(k=><button key={k} onClick={()=>update(k,'')} aria-label={`Fjarlægja síu: ${filterNames[k]}`}><span>{filterNames[k]}{!['offer','tow','site'].includes(k)?`: ${['min','max'].includes(k)?price(Number(params.get(k))):params.get(k)}`:''}</span><X aria-hidden="true" size={14}/></button>)}<button className="bm-clear" onClick={reset}>Hreinsa allt</button></div>}
   {invalidRange&&<p className="bm-error" role="alert">Lágmark þarf að vera lægra en hámark. Breyttu verðbili eða árgerð.</p>}
   <p className="bm-dated">Söluskrá 01.10.2026 · Frumgerð</p><div className="bm-result-toolbar"><p aria-live="polite" aria-atomic="true"><strong>{results.length}</strong> {results.length===1?'ökutæki':'ökutæki'}{active.length?(results.length===1?' passar við leitina':' passa við leitina'):''}</p><label>Raða eftir<select aria-label="Raða bílum" value={params.get('sort')||'default'} onChange={e=>update('sort',e.target.value)}><option value="default">Röðun söluskrár</option><option value="price-up">Lægsta verði</option><option value="price-down">Hæsta verði</option><option value="year">Nýjustu árgerð</option><option value="km">Minnstum akstri</option></select></label></div>
   {results.length?<div className="bm-results">{results.slice(0,limit).map((c,i)=><VehicleCard key={c.id} car={c} saved={saved.includes(c.id)} comparing={compare.includes(c.id)} onOpen={()=>detail(c)} onSave={()=>toggleSave(c.id)} onCompare={()=>toggleCompare(c.id)} eager={i<2}/>)}</div>:<div className="bm-empty"><Search aria-hidden="true"/><h2>{view==='saved'&&!saved.length?'Engir bílar vistaðir enn.':'Enginn bíll passar við þessa leit.'}</h2><p>{view==='saved'&&!saved.length?'Ýttu á hjartað við bíl til að eiga hann hér.':'Prófaðu að víkka verðbilið eða fjarlægja eina síu.'}</p><button className="bm-button primary" onClick={()=>view==='saved'&&!saved.length?go('cars'):reset()}>{view==='saved'&&!saved.length?'Skoða bílana':'Hreinsa leit og síur'}</button><a className="bm-text-button" href="tel:+3545174500">Hafðu samband · 517 4500</a></div>}
   {limit<results.length&&<div className="bm-loadmore"><p>Sýni {Math.min(limit,results.length)} af {results.length} ökutækjum</p><button className="bm-button" onClick={()=>{const p=new URLSearchParams(params);p.set('limit',String(limit+12));history.replaceState(history.state,'',`${location.pathname}?${p}`);setParams(p)}}>Sýna fleiri bíla <Plus aria-hidden="true"/></button></div>}
   <Snapshot/>
  </section>
  {view==='home'&&<section className="bm-sell-band"><div className="bm-container"><h2>HVAÐ VILTU<br/>GERA VIÐ ÞINN?</h2><div className="bm-sell-options"><a href="?view=cash" onClick={e=>{if(e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;e.preventDefault();go('cash')}}><span>Fá staðgreiðslutilboð</span><p>Sendu upplýsingar um bílinn. Allar tegundir, árgerðir og ástand koma til skoðunar.</p><ArrowRight aria-hidden="true"/></a><a href="?view=sell" onClick={e=>{if(e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;e.preventDefault();go('sell')}}><span>Setja bíl í sölu</span><p>Skráðu ökutækið og fáðu aðstoð við söluna.</p><ArrowRight aria-hidden="true"/></a></div></div></section>}
  </>}
  </main>
  <footer className="bm-footer bm-container"><div className="bm-footer-main"><div><a className="bm-logo" href="?" onClick={e=>{if(e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;e.preventDefault();go('home')}}><Wordmark/></a><p>Bíll fyrir þína leið.</p><a href="https://www.google.com/maps/search/?api=1&query=Kr%C3%B3kh%C3%A1ls+7+Reykjav%C3%ADk" target="_blank" rel="noreferrer"><MapPin aria-hidden="true" size={16}/>Krókhálsi 7, 110 Reykjavík</a></div><div><h3>Hafðu samband</h3><a href="tel:+3545174500">517 4500</a><a href="mailto:aegir@bilamidstodin.is">aegir@bilamidstodin.is</a><p>Mánudaga til föstudaga<br/>10:00–18:00</p></div><div><h3>Bílamiðstöðin</h3><a href="?view=about" onClick={e=>{if(e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;e.preventDefault();go('about')}}>Um okkur og verðskrá</a><a href="?view=sell" onClick={e=>{if(e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;e.preventDefault();go('sell')}}>Setja bíl í sölu</a><button className="bm-text-button" onClick={()=>setModal('theme')}>{theme==='dark'?<Moon aria-hidden="true"/>:<Sun aria-hidden="true"/>}Útlit: {preference==='system'?'Fylgir tæki':theme==='dark'?'Dökkt':'Ljóst'}</button></div></div><div className="bm-footer-bottom"><span>Bílamiðstöðin ehf. · Kt. 490316-2480</span><span>Designed by <a href="https://sndrstudio.is" target="_blank" rel="noreferrer">SNDR Studio</a></span><span>Frumgerð · ekki tengd lifandi söluskrá</span></div></footer>
  {compareCars.length>0&&!['compare','cash','sell','finance','about'].includes(view)&&<div className="bm-compare-tray"><div><Scale aria-hidden="true"/><span><strong>{compareCars.length} valdir</strong><small>{compareCars.length<2?'Veldu annan bíl til að bera saman':compareCars.map(c=>carTitle(c)).join(' · ')}</small></span><button className="bm-button primary" disabled={compareCars.length<2} onClick={()=>go('compare')}>Bera saman</button><button className="bm-icon" aria-label="Hreinsa samanburð" onClick={()=>setCompare([])}><X aria-hidden="true"/></button></div></div>}
  {notice&&<div className="bm-toast" role="status">{notice}<button className="bm-icon" aria-label="Loka tilkynningu" onClick={()=>setNotice('')}><X aria-hidden="true" size={16}/></button></div>}
  {modal==='menu'&&<Modal title="Valmynd" onClose={()=>setModal(null)}><nav className="bm-mobile-nav">{[['cars','Bílar til sölu'],['saved',`Valdir bílar (${saved.length})`],['cash','Fá staðgreiðslutilboð'],['sell','Setja bíl í sölu'],['finance','Fjármögnun'],['about','Um okkur og verðskrá']].map(([v,l])=><a key={v} href={`?view=${v}`} onClick={e=>{if(e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;e.preventDefault();go(v)}}>{l}<ArrowRight aria-hidden="true"/></a>)}</nav><ThemeOptions preference={preference} choose={choose}/><a className="bm-button primary" href="tel:+3545174500"><Phone aria-hidden="true"/>Hringja í 517 4500</a></Modal>}
  {modal==='theme'&&<Modal title="Útlit síðunnar" onClose={()=>setModal(null)}><ThemeOptions preference={preference} choose={choose}/><p>Valið þitt er geymt í þessum vafra. Veldu „Fylgja tæki“ til að nota útlitsstillingu símans eða tölvunnar.</p></Modal>}
  {modal==='filters'&&<Modal title="Finndu þinn bíl" onClose={()=>setModal(null)}><div className="bm-modal-filters">{filters()}<details className="bm-filter-more" open={["type","gear","drive","yearMin","yearMax","kmMax","seats","offer","tow","site"].some(key=>params.has(key))}><summary>Fleiri síur <span>Árgerð, akstur, drif og búnaður</span><Plus aria-hidden="true" size={18}/></summary>{filters(true)}</details></div>{invalidRange&&<p className="bm-error">Lágmark þarf að vera lægra en hámark.</p>}<div className="bm-dialog-foot"><button className="bm-text-button" onClick={reset}>Hreinsa síur</button><button className="bm-button primary" onClick={()=>setModal(null)}>Sjá {results.length} ökutæki</button></div></Modal>}
  {modal==='enquiry'&&(car||compareCars.length>0)&&<Modal title={car?"Fyrirspurn um bíl":"Fyrirspurn um valda bíla"} onClose={()=>setModal(null)}>{car&&<div className="bm-enquiry-car"><VehicleImage src={car.photos[0]} alt=""/><div><h3>{carTitle(car)}</h3><p>{car.registration} · {mileage(car)}</p><Price car={car}/></div></div>}<RequestForm car={car} selection={car?undefined:compareCars}/></Modal>}
  {modal==='gallery'&&car&&<Modal title={`${carTitle(car)} · ${galleryIndex+1} / ${car.photos.length}`} onClose={()=>setModal(null)} wide><div className="bm-lightbox" onKeyDown={e=>{if(e.key==='ArrowRight')setGalleryIndex(i=>(i+1)%car.photos.length);if(e.key==='ArrowLeft')setGalleryIndex(i=>(i-1+car.photos.length)%car.photos.length)}}><VehicleImage src={car.photos[galleryIndex]} alt={`${carTitle(car)}, mynd ${galleryIndex+1}`} eager/><div className="bm-lightbox-controls"><button className="bm-button" onClick={()=>setGalleryIndex(i=>(i-1+car.photos.length)%car.photos.length)}><ChevronLeft aria-hidden="true"/>Fyrri</button><span>{galleryIndex+1} / {car.photos.length}</span><button className="bm-button" onClick={()=>setGalleryIndex(i=>(i+1)%car.photos.length)}>Næsta<ChevronRight aria-hidden="true"/></button></div></div></Modal>}
 </div>
}

function ThemeOptions({preference,choose}:{preference:string;choose:(p:string)=>void}){return <fieldset className="bm-theme-options"><legend>Útlit</legend>{[['light','Ljóst',Sun],['dark','Dökkt',Moon],['system','Fylgja tæki',Monitor]].map(([v,l,Icon])=>{const I=Icon as typeof Sun;return <label key={v as string}><input type="radio" name="theme" checked={preference===v} onChange={()=>choose(v as string)}/><I aria-hidden="true" size={18}/>{l as string}</label>})}</fieldset>}
function Filters({cars,params,update,advanced}:{cars:Car[];params:URLSearchParams;update:(k:string,v:string)=>void;advanced:boolean}){
 const select=(key:FilterKey,label:string,values:string[])=> <label>{label}<select name={key} value={params.get(key)||''} onChange={e=>update(key,e.target.value)}><option value="">{key==='make'?'Allar tegundir':key==='model'?'Allar gerðir':'Allt'}</option>{[...new Set(values.filter(Boolean))].sort((a,b)=>a.localeCompare(b,'is')).map(v=><option key={v}>{v}</option>)}</select></label>
 const numeric=(key:FilterKey,label:string,placeholder:string,max=99999999)=><label>{label}<input name={key} type="number" inputMode="numeric" min="0" max={max} step="1" placeholder={placeholder} value={params.get(key)||''} onChange={e=>update(key,e.target.value)}/></label>
 return <div className={`bm-filter-grid ${advanced?'advanced':''}`}>{advanced?<>{select('type','Flokkur',cars.flatMap(c=>c.categories))}{select('gear','Skipting',cars.map(c=>c.transmission))}{select('drive','Drif',cars.map(c=>c.specs.Drif))}{numeric('yearMin','Árgerð frá','T.d. 2018',2027)}{numeric('yearMax','Árgerð til','T.d. 2026',2027)}{numeric('kmMax','Hámarksakstur (km)','T.d. 100000',1000000)}<label>Sætafjöldi<select name="seats" value={params.get('seats')||''} onChange={e=>update('seats',e.target.value)}><option value="">Allur sætafjöldi</option><option value="5">5 eða fleiri</option><option value="7">7 eða fleiri</option><option value="9">9 eða fleiri</option></select></label><div className="bm-checkboxes">{[['offer','Aðeins tilboð'],['tow','Með dráttarkrók'],['site','Skráð á staðnum']].map(([k,l])=><label key={k}><input type="checkbox" checked={params.get(k)==='1'} onChange={e=>update(k,e.target.checked?'1':'')}/>{l}</label>)}</div></>:<>{select('make','Tegund',cars.map(c=>c.make))}{select('model','Gerð',cars.filter(c=>!params.get('make')||c.make===params.get('make')).map(c=>c.name))}{select('fuel','Orkugjafi',cars.map(fuelLabel))}{numeric('min','Verð frá (kr.)','Ekkert lágmark')}{numeric('max','Verð að (kr.)','Ekkert hámark')}</>}</div>
}
function VehicleCard({car,saved,comparing,onOpen,onSave,onCompare,eager=false}:{car:Car;saved:boolean;comparing:boolean;onOpen:()=>void;onSave:()=>void;onCompare:()=>void;eager?:boolean}){
 return <article className="bm-car"><div className="bm-car-photo"><a href={`?car=${car.id}`} onClick={e=>{if(e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;e.preventDefault();onOpen()}} tabIndex={-1} aria-hidden="true"><VehicleImage src={car.photos[0]} alt={carTitle(car)} eager={eager}/></a>{car.offer&&<span className="bm-offer">Tilboð</span>}<button className="bm-icon bm-save" aria-label={`${saved?'Fjarlægja':'Vista'} ${carTitle(car)}`} aria-pressed={saved} onClick={onSave}><Heart aria-hidden="true" fill={saved?'currentColor':'none'}/></button><span className="bm-photo-count">{car.photos.length} myndir</span></div><div className="bm-car-body"><div className="bm-car-identity"><h2><a href={`?car=${car.id}`} onClick={e=>{if(e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;e.preventDefault();onOpen()}}>{carTitle(car)}</a></h2><p>{car.trim||car.type}</p></div><Price car={car}/><Facts car={car}/><div className="bm-card-extra"><span>{car.specs.Drif==='Fjórhjóladrif'?'4×4':car.type}</span>{car.seats>0&&<span>{car.seats} sæti</span>}{car.highlight&&<span>{car.highlight}</span>}</div><div className="bm-card-foot"><button className="bm-text-button" aria-pressed={comparing} onClick={onCompare}>{comparing?<Check aria-hidden="true" size={17}/>:<Plus aria-hidden="true" size={17}/>}Bera saman</button><button className="bm-text-button" onClick={onOpen}>Skoða bíl <ArrowRight aria-hidden="true" size={17}/></button></div></div></article>
}
function Equipment({car}:{car:Car}){
 const all=[...new Set(car.groups.flat())]
 const categories=[['Saga og viðhald',/Tímareim|Þjónustu|Smurbók|Reyklaust/],['Dráttur og burður',/Dráttar|eftirvagn|tengibúnað/],['Orka og afköst',/rafhlöð|hleðsl|eyðsla|CO 2|Innspýting|Túrbína|Intercooler/],['Öryggi og akstursaðstoð',/ABS|hemla|loftpúð|Akrein|Blindsvæð|myndavél|nálgun|spól|stöðug|Brekk|hraðastill|að leggja/i],['Skjáir og tengingar',/CarPlay|Android|Bluetooth|hljóð|símateng|USB|AUX|leiðsögu|Navi|skjá|tölva/i],['Hjól og ytra byrði',/dekk|felgur|ljós|lýsing|þakbog|Brettakant/i],['Þægindi og annar búnaður',/./]] as const
 const used=new Set<string>()
 return <div className="bm-equipment">{categories.map(([title,pattern],i)=>{const list=all.filter(x=>!used.has(x)&&pattern.test(x));list.forEach(x=>used.add(x));if(!list.length)return null;return <details key={title} open={i===0||i===1}><summary>{title}<span>{list.length}<Plus aria-hidden="true" size={18}/></span></summary><ul>{list.map(x=><li key={x}><Check aria-hidden="true" size={15}/>{x}</li>)}</ul></details>})}</div>
}
function SelectionSummary({cars}:{cars?:Car[]}){return cars?.length?<div className="bm-selected-enquiry"><h3>Valdir bílar</h3>{cars.map(c=><div className="bm-enquiry-car" key={c.id}><VehicleImage src={c.photos[0]} alt=""/><div><strong>{carTitle(c)}</strong><p>Raðnúmer {c.id}</p><Price car={c}/></div></div>)}</div>:null}
function RequestForm({car,kind,selection}:{car?:Car;kind?:'cash'|'sell';selection?:Car[]}){
 const [review,setReview]=useState<Record<string,string>|null>(null);const [copied,setCopied]=useState(false);const draft=useRef<Record<string,string>>({});const dirty=useRef(false);const reviewRef=useRef<HTMLDivElement>(null);const formRef=useRef<HTMLFormElement>(null)
 useEffect(()=>{if(review)reviewRef.current?.focus();else if(Object.keys(draft.current).length)formRef.current?.querySelector<HTMLInputElement>('input')?.focus()},[review])
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty.current){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[])
 const subject=selection?.length?'Fyrirspurn um valda bíla':car?`Fyrirspurn: ${carTitle(car)} (${car.id})`:kind==='cash'?'Ósk um staðgreiðslutilboð':'Ósk um söluskráningu'
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();draft.current=Object.fromEntries([...new FormData(e.currentTarget).entries()].map(([k,v])=>[k,String(v)]));setReview(draft.current)}
 const body=review?`${subject}\n${car?car.source+'\n':selection?.map(c=>carTitle(c)+' · '+c.source).join('\n')||''}\n${Object.entries(review).map(([k,v])=>`${k}: ${v}`).join('\n')}`:''
 if(review)return <div className="bm-review" data-dirty={dirty.current?"true":undefined} ref={reviewRef} tabIndex={-1}><Check aria-hidden="true"/><h3>Beiðnin er tilbúin til yfirferðar.</h3><p>Hún hefur ekki verið send. Opnaðu tölvupóstinn þinn og sendu hana þaðan.</p><SelectionSummary cars={selection}/><dl>{Object.entries(review).filter(([,v])=>v).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><a className="bm-button primary" onClick={()=>{dirty.current=false}} href={`mailto:aegir@bilamidstodin.is?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`}><Mail aria-hidden="true"/>Opna tölvupóst</a><button className="bm-button" onClick={async()=>{try{await navigator.clipboard.writeText(body);setCopied(true)}catch{setCopied(false)}}}>{copied?'Afritað':'Afrita beiðni'}</button><button className="bm-text-button" onClick={()=>setReview(null)}>Breyta upplýsingum</button></div>
 return <form ref={formRef} onSubmit={submit} onChange={e=>{dirty.current=true;e.currentTarget.dataset.dirty="true"}} className="bm-request-form" data-dirty={dirty.current?"true":undefined}><SelectionSummary cars={selection}/><p className="bm-form-note">Frumgerð: þú ferð yfir beiðnina áður en þú opnar hana í tölvupósti. Ekkert er sent sjálfkrafa.</p>{!car&&!selection&&<div className="bm-form-row"><label>Skráningarnúmer<input name="Skráningarnúmer" defaultValue={draft.current["Skráningarnúmer"]} autoComplete="off" required maxLength={12} autoCapitalize="characters" spellCheck={false} placeholder="AB 123"/></label><label>Akstur (km)<input name="Akstur (km)" defaultValue={draft.current["Akstur (km)"]} autoComplete="off" type="number" inputMode="numeric" min="0" max="2000000" required placeholder="85000"/></label></div>}{(car||selection)&&<><label>Hvernig getum við aðstoðað?<select name="Ósk" defaultValue={draft.current.Ósk||"Skoða / reynsluaka"}><option>Skoða / reynsluaka</option><option>Fá nánari upplýsingar</option><option>Ræða fjármögnun</option><option>Ræða uppítöku</option></select></label><label>Bíll í uppítöku (ef við á)<input name="Uppítaka" defaultValue={draft.current.Uppítaka} placeholder="Tegund, árgerð, akstur og skráningarnúmer…" maxLength={300}/></label></>}<label>Nafn<input name="Nafn" defaultValue={draft.current.Nafn} autoComplete="name" required maxLength={120}/></label><div className="bm-form-row bm-contact-row"><label>Sími<input name="Sími" defaultValue={draft.current.Sími} type="tel" inputMode="tel" autoComplete="tel" required pattern="[+0-9 ()-]{7,20}" title="Sláðu inn símanúmer, að lágmarki 7 stafi."/></label><label>Netfang<input name="Netfang" defaultValue={draft.current.Netfang} spellCheck={false} type="email" autoComplete="email" required maxLength={160}/></label></div><label>{car||selection?'Hvað viltu vita?':'Upplýsingar um bílinn'}<textarea name="Skilaboð" rows={4} maxLength={4000} defaultValue={draft.current.Skilaboð??(car?`Ég hef áhuga á ${carTitle(car)}. Er bíllinn enn til sölu og hvenær væri hægt að skoða hann?`:'')} placeholder={car||selection?'Fyrirspurn, reynsluakstur eða skipti…':'Tegund, árgerð, ástand, þjónustusaga og annað sem skiptir máli.'}/></label><button className="bm-button primary" type="submit">Yfirfara beiðni <ArrowRight aria-hidden="true"/></button><p className="bm-small">Upplýsingarnar eru aðeins á þessari síðu þar til þú sendir tölvupóst. Þær eru ekki vistaðar af frumgerðinni.</p><a className="bm-text-button" href={car?.inquiry||(selection?'https://www.bilamidstodin.is/um-okkur':kind==='cash'?cashURL:sellURL)} target="_blank" rel="noreferrer">{selection?"Hafa samband við Bílamiðstöðina":"Nota núverandi eyðublað Bílamiðstöðvarinnar"} <ArrowRight aria-hidden="true" size={16}/></a></form>
}
function SellPage({kind}:{kind:'cash'|'sell'}){return <section className="bm-container bm-service-page"><div className="bm-service-intro"><span className="bm-service-label">{kind==='cash'?'Kaupum ökutæki':'Aðstoð við sölu'}</span><h1>{kind==='cash'?'SELJA BEINT.':'SETJA Í SÖLU.'}</h1><p className="bm-lead">{kind==='cash'?'Við skoðum kaup á þínu ökutæki gegn staðgreiðslu. Allar tegundir, árgerðir og ástand koma til greina.':'Skráðu ökutækið þitt. Sölumaður fer yfir upplýsingarnar áður en auglýsingin birtist.'}</p></div><div className="bm-form-panel"><h2>{kind==='cash'?'Óska eftir tilboði':'Óska eftir söluskráningu'}</h2><RequestForm key={kind} kind={kind}/></div><div className="bm-service-details"><ol className="bm-steps"><li><span>1</span><div><h2>Segðu okkur frá ökutækinu</h2><p>Skráningarnúmer, akstur, ástand og þjónustusaga.</p></div></li><li><span>2</span><div><h2>Við förum yfir upplýsingarnar</h2><p>{kind==='cash'?'Við metum hvort kaup komi til greina.':'Verð, búnaður og skilmálar eru staðfestir með þér.'}</p></div></li><li><span>3</span><div><h2>Þú tekur ákvörðun</h2><p>{kind==='cash'?'Þú færð tilboð ef kaup koma til greina.':'Skráningin birtist þegar sölumaður hefur yfirfarið hana.'}</p></div></li></ol>{kind==='sell'?<div className="bm-fee"><h2>Birt söluþóknun</h2><strong>4,2% <small>af söluverði, auk vsk.</small></strong><p>Fyrir bifreiðar að 1.570.000 kr. eru birt sölulaun 89.900 kr. Viðbótargjöld koma fram í verðskrá. Staðfestu heildarkostnað og skattameðferð við skráningu.</p><a href="?view=about">Sjá verðskrá og skilmála</a></div>:<p className="bm-help">Bílamiðstöðin áskilur sér rétt til að meta ökutækið og gera aðeins tilboð ef áhugi er á kaupum.</p>}<a className="bm-text-button" href="tel:+3545174500"><Phone aria-hidden="true"/>Frekar í síma? 517 4500</a></div></section>}
function Finance(){return <section className="bm-container bm-about"><span className="bm-service-label">Fjármögnun</span><h1>NÆSTA SKREF.<br/>Á ÞÍNUM FORSENDUM.</h1><p className="bm-lead">Veldu fyrst bílinn. Sölumaður hjálpar þér að kanna greiðslumöguleika sem henta þér.</p><div className="bm-about-grid"><div><h2>Gott að hafa tilbúið</h2><ol className="bm-finance-list"><li>Hvaða bíll eða bílar vekja áhuga?</li><li>Hvað viltu leggja út sjálfur?</li><li>Viltu ræða uppítöku á núverandi bíl?</li><li>Hvaða greiðslubyrði hentar þér?</li></ol><p>Veldu „Ræða fjármögnun“ í fyrirspurn um bíl. Upplýsingar um bílinn fylgja beiðninni.</p><a className="bm-button primary" href="?view=cars">Finna bíl <ArrowRight aria-hidden="true"/></a></div><div><h2>Fáðu skilmálana áður en þú ákveður</h2><p>Bankar og fjármögnunarfyrirtæki bjóða mismunandi leiðir. Lánshæfismat, vextir, gjöld og heildarkostnaður eru staðfest hjá viðkomandi lánveitanda.</p><p>Engin lánveiting eða áætluð mánaðargreiðsla er lofað í þessari frumgerð.</p><a className="bm-text-button" href="https://www.bilamidstodin.is/fjarmognun" target="_blank" rel="noreferrer">Sjá birtar fjármögnunarleiðir <ArrowRight aria-hidden="true"/></a><a className="bm-text-button" href="tel:+3545174500"><Phone aria-hidden="true"/>Ræða við sölumann · 517 4500</a></div></div></section>}
function About(){const staff=[['Ægir Þór Ægisson','aegir'],['Ragnar Þór Ægisson','ragnar'],['Ólafur Ægir Jökulsson','olafur'],['Birnir Liljuson','birnir'],['Þór Sigurðsson','thor']];return <section className="bm-container bm-about"><h1>BÍLAMIÐSTÖÐIN.<br/>KRÓKHÁLSI 7.</h1><p className="bm-lead">Bílar til sölu, staðgreiðslukaup og aðstoð við að selja þitt ökutæki.</p><div className="bm-about-grid"><div><h2>Komdu við</h2><p>Krókhálsi 7, 110 Reykjavík.</p><dl className="bm-specs"><div><dt>Mánudaga–föstudaga</dt><dd>10:00–18:00</dd></div><div><dt>Laugardaga</dt><dd>12:00–15:00</dd></div><div><dt>Sunnudaga</dt><dd>Lokað</dd></div></dl><p>Lokað á laugardögum í júlí og desember.</p><a className="bm-button primary" href="https://www.google.com/maps/search/?api=1&query=Kr%C3%B3kh%C3%A1ls+7+Reykjav%C3%ADk" target="_blank" rel="noreferrer"><MapPin aria-hidden="true"/>Fá leiðarlýsingu</a></div><div><h2>Hafðu samband</h2><a className="bm-text-button" href="tel:+3545174500"><Phone aria-hidden="true"/>517 4500</a><div className="bm-staff">{staff.map(([name,email])=><a href={'mailto:'+email+'@bilamidstodin.is'} key={email}><span>{name}</span><small>{email}@bilamidstodin.is</small><Mail aria-hidden="true" size={17}/></a>)}</div></div></div><div className="bm-about-grid"><div><h2>Birt verðskrá</h2><dl className="bm-specs">{[['Sölulaun að 1.570.000 kr.','89.900 kr.'],['Sölulaun frá 1.570.000 kr.','4,2% auk vsk.'],['Eigendaskipti','2.990 kr.'],['Ferilskrá / veðbók','4.089 kr.'],['Skjalafrágangur, pr. tæki','39.900 kr.'],['Umsýslugjald kaupanda','25.000 kr.'],['Upplýsingaöflun vegna innheimtukrafna','2.990 kr.'],['Greiðsla með debet- eða kreditkorti','2,5%']].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><p>Samantekt úr birtri verðskrá. Staðfestu hvaða gjöld eiga við, heildarkostnað og hvort vsk. sé innifalinn áður en viðskipti eru staðfest.</p></div><div><h2>Áður en þú kemur</h2><p>Hafðu samband til að staðfesta að ökutækið sé til sýnis og semdu við sölumann um tíma og skilmála reynsluaksturs.</p><p>Samkvæmt birtum skilmálum eru ökutæki og lausamunir á útisvæði á ábyrgð eigenda. Farðu yfir skilmála og ástand áður en þú gengur frá viðskiptum.</p><a href="https://www.bilamidstodin.is/um-okkur" target="_blank" rel="noreferrer" className="bm-text-button">Upprunaleg verðskrá og allir skilmálar <ArrowRight aria-hidden="true"/></a><a href="https://www.bilamidstodin.is/notkunarskilmalar" target="_blank" rel="noreferrer" className="bm-text-button">Notkunarskilmálar og persónuvernd <ArrowRight aria-hidden="true"/></a></div></div></section>}
function Compare({cars,onRemove,onOpen,goCars,onEnquire}:{cars:Car[];onEnquire:()=>void;onRemove:(id:string)=>void;onOpen:(c:Car)=>void;goCars:()=>void}){
 const rows:[string,(c:Car)=>string][]=[['Verð',c=>(c.price?price(c.price):'Verð ekki tilgreint')+(c.priceNote?` · ${c.priceNote}`:'')],['Nýskráning',c=>c.registration||'Ekki tilgreint'],['Akstur',mileage],['Orkugjafi',fuelLabel],['Skipting',c=>c.transmission||'Ekki tilgreint'],['Drif',driveLabel],['Sæti',c=>c.seats?String(c.seats):'Ekki tilgreint'],['Hestöfl',c=>c.specs.Hestöfl||'Ekki tilgreint'],['Næsta skoðun',c=>c.specs['Næsta skoðun']||'Ekki tilgreint'],['Dráttargeta, hemlað',c=>c.groups.flat().find(x=>x.startsWith('Þyngd hemlaðs'))?.replace('Þyngd hemlaðs eftirvagns ','')||'Ekki tilgreint']]
 return <section className="bm-container bm-comparison"><button className="bm-text-button" onClick={goCars}><ArrowLeft aria-hidden="true"/>Velja fleiri bíla</button><h1>BERÐU SAMAN.</h1><p>Verð, búnaður og helstu upplýsingar hlið við hlið.</p>{cars.length<2?<div className="bm-empty"><Scale aria-hidden="true"/><h2>Veldu tvo eða þrjá bíla.</h2><p>Notaðu „Bera saman“ við þá bíla sem vekja áhuga þinn.</p><button className="bm-button primary" onClick={goCars}>Skoða bílana</button>{cars.map(c=><button key={c.id} className="bm-text-button" onClick={()=>onRemove(c.id)}>Fjarlægja {carTitle(c)} <X aria-hidden="true"/></button>)}</div>:<><p className="bm-mobile-hint">Strjúktu til hliðar til að sjá allan samanburðinn.</p><div className="bm-compare-scroll" tabIndex={0} role="region" aria-label="Samanburður bíla"><table><thead><tr><th scope="col">Upplýsingar</th>{cars.map(c=><th scope="col" key={c.id}><button className="bm-icon" aria-label={`Fjarlægja ${carTitle(c)} úr samanburði`} onClick={()=>onRemove(c.id)}><X aria-hidden="true"/></button><VehicleImage src={c.photos[0]} alt={carTitle(c)}/><button className="bm-text-button" onClick={()=>onOpen(c)}>{carTitle(c)}<ArrowRight aria-hidden="true"/></button><p>{c.trim}</p></th>)}</tr></thead><tbody>{rows.map(([label,value])=><tr key={label}><th scope="row">{label}</th>{cars.map(c=><td key={c.id}>{value(c)}</td>)}</tr>)}</tbody></table></div><button className="bm-button primary" onClick={onEnquire}><Mail aria-hidden="true"/>Fyrirspurn um þessa {cars.length} bíla</button><Snapshot/></>}</section>
}
