/**
 * Day-by-day itineraries of the long tours and the schematic region map.
 *
 * EN and DE day texts are the company's own, word for word from polarhestar.is
 * (read 2026-10-09; the site has no Icelandic pages, so IS is our translation,
 * condensed, written to the same facts). The CMS carries an `itinerary` field;
 * these are the seed and the offline fallback. "Back to the Roots" has no
 * itinerary published, so it has none here either.
 *
 * The map is SCHEMATIC: places are projected from their real latitude and
 * longitude onto one flat frame (no coastline survey), enough to show where a
 * day goes, never a hiking map. Coordinates: viewBox 0 0 1000 700.
 */
import type { L3 } from './schedule'

export interface ItineraryDay {
  n: number
  /** Arrival / departure days carry a title; riding days are just "Day n". */
  kind?: 'arrival' | 'departure'
  body: L3
  /** Map place ids the day touches, in order. */
  places: string[]
}
export interface Itinerary {
  days: ItineraryDay[]
}

export const DAY_TITLE: Record<NonNullable<ItineraryDay['kind']>, L3> = {
  arrival: { is: 'Koma', en: 'Arrival', de: 'Ankunft' },
  departure: { is: 'Brottför', en: 'Departure', de: 'Abreise' },
}

export interface MapPlace { id: string; x: number; y: number; label: string }
export const MAP_PLACES: MapPlace[] = [
  { id: "akureyri", x: 229, y: 444, label: "Akureyri" },
  { id: "grytubakki", x: 196, y: 246, label: "Grýtubakki" },
  { id: "grenivik", x: 174, y: 228, label: "Grenivík" },
  { id: "laufas", x: 229, y: 270, label: "Laufás" },
  { id: "hofdi", x: 157, y: 190, label: "Höfði" },
  { id: "latrastrond", x: 130, y: 150, label: "Látraströnd" },
  { id: "svinarnes", x: 124, y: 126, label: "Svínárnes" },
  { id: "hrisey", x: 63, y: 190, label: "Hrísey" },
  { id: "gljufura", x: 218, y: 234, label: "Gljúfurá" },
  { id: "fnjoskadalur", x: 295, y: 334, label: "Fnjóskadalur" },
  { id: "thvera", x: 318, y: 294, label: "Þverá" },
  { id: "fjordur", x: 240, y: 94, label: "Fjörður" },
  { id: "leirdalsheidi", x: 224, y: 158, label: "Leirdalsheiði" },
  { id: "trolladalur", x: 262, y: 134, label: "Trölladalur" },
  { id: "gil", x: 279, y: 118, label: "Gil" },
  { id: "thorgeirsfjordur", x: 290, y: 86, label: "Þorgeirsfjörður" },
  { id: "thonglabakki", x: 304, y: 90, label: "Þönglabakki" },
  { id: "thorgeirshofdi", x: 318, y: 62, label: "Þorgeirshöfði" },
  { id: "flateyjardalur", x: 356, y: 166, label: "Flateyjardalur" },
  { id: "hof", x: 362, y: 126, label: "Hof" },
  { id: "godafoss", x: 528, y: 444, label: "Goðafoss" },
  { id: "fremstafell", x: 544, y: 414, label: "Fremstafell" },
  { id: "sandur", x: 533, y: 270, label: "Sandur" },
  { id: "nattfaravikur", x: 434, y: 174, label: "Náttfaravíkur" },
  { id: "heidarbot", x: 600, y: 286, label: "Heiðarbót" },
  { id: "laxa", x: 611, y: 318, label: "Laxá" },
  { id: "reykjadalur", x: 633, y: 382, label: "Reykjadalur" },
  { id: "vestmannsvatn", x: 600, y: 390, label: "Vestmannsvatn" },
  { id: "akrar", x: 644, y: 414, label: "Akrar" },
  { id: "masvatn", x: 710, y: 470, label: "Másvatn" },
  { id: "myvatn", x: 832, y: 510, label: "Mývatn" },
  { id: "skutustadir", x: 815, y: 534, label: "Skútustaðir" },
  { id: "dimmuborgir", x: 882, y: 518, label: "Dimmuborgir" },
  { id: "namaskard", x: 931, y: 478, label: "Námaskarð" },
  { id: "stong", x: 765, y: 486, label: "Stöng" },
  { id: "engidalur", x: 677, y: 574, label: "Engidalur" },
  { id: "odadahraun", x: 694, y: 654, label: "Ódáðahraun" },
  { id: "bardardalur", x: 566, y: 542, label: "Bárðardalur" },
]
export const MAP_PLACE = Object.fromEntries(MAP_PLACES.map((p) => [p.id, p])) as Record<string, MapPlace>

export const ITINERARIES: Record<string, Itinerary> = {
  "midnightsun": {
    days: [
      { n: 1, kind: "arrival", places: ["akureyri", "grytubakki"], body: {
        is: "Gestir eru sóttir á Akureyri síðdegis, oftast milli kl. 16 og 18. Hálftíma akstur að Grýtubakka. Eftir kvöldmat er farið yfir dagskrá næstu daga. Gist á Grýtubakka.",
        en: "Our guests are picked up in Akureyri in the late afternoon (mostly between 4-6 pm). A thirty minutes’ drive will bring us to the farmhouse Grýtubakki. After dinner, details about the following days will be provided. Overnight stay at Grýtubakki.",
        de: "Am späteren Nachmittag holen wir unsere Gäste aus Akureyri ab. Nach dem Abendessen besprechen wir den Ablauf der nächsten Tage. Übernachtung auf Grýtubakki.",
      } },
      { n: 2, places: ["fnjoskadalur", "laufas"], body: {
        is: "Eftir morgunmat er lagt á fyrir fyrsta reiðtúrinn, inn í Fnjóskadal, dal lengstu bergvatnsár landsins. Riðið yfir gömlu brúna og inn dalinn, sem er þröngur en fjölbreyttur, með fuglalíf allt um kring. Hádegishlé á fallegum stað í dalnum, svo til baka að Grýtubakka í kaffi og kökur. Um fjórar til fimm stundir í hnakknum. Eftir kaffi er ekið að gamla bænum Laufási. Kvöldmatur og gisting á Grýtubakka.",
        en: "After breakfast, we saddle our horses for the first riding excursion, which takes us into the valley of Fnjóská, the longest freshwater river in Iceland. We cross the river over an old bridge and continue riding into the valley, which is rather narrow but offers a big variety of different landscapes. On the way, we enjoy the rushing water and watch the numberless birds being very busy with taking care of their young ones. After our lunch break at a beautiful place in the valley, we will turn back to Grýtubakki where we have coffee and cakes. Our riding time today is about four to five hours. After coffee, we drive to the well-known turf houses of Laufás, which provide an interesting inside into the life of Icelandic people in past times. Dinner and overnight stay at Grýtubakki.",
        de: "Nach einem ausgiebigen Frühstück satteln wir die Pferde und brechen zu unserem ersten Ritt auf, der uns in das Tal des Flusses Fnjóská führt. Dieses Tal ist geologisch sehr interessant, da hier vor über 10.000 Jahren ein großer Gletschersee von rund 40 Quadratkilometern Fläche gelegen haben soll. Die Ufer dieses ehemaligen Sees sind heute noch an den Hängen beidseits des Tales als horizontale Einkerbungen sichtbar. Über eine alte Brücke gelangen wir zum rechten Ufer des Flusses und setzen unseren Ritt weiter ins Tal hinein fort. Wir genießen die Mittagspause in der Nähe eines kleinen Wäldchens, lauschen dem Rauschen des Flusses und dem Zwitschern unzähliger Vögel, die zu dieser Zeit des Jahres intensiv mit der Aufzucht des Nachwuchses beschäftigt sind. Nach etwa vier bis fünf Stunden im Sattel reiten wir am frühen Nachmittag zurück zur Farm, wo wir von einer duftenden Kaffeetafel erwartet werden. Nach der Kaffeepause fahren wir zum alten Torfgehöft Laufás, welches heute zu einem Museum umfunktioniert wurde. Hier können unsere Gäste Einblick in das frühere Leben der Isländer erhalten. Es ist eine Reise in die Vergangenheit. Abendessen und Übernachtung auf Grýtubakki.",
      } },
      { n: 3, places: ["gljufura", "hofdi"], body: {
        is: "Riðið að Eyjafirði, lengsta firði landsins, meðfram Gljúfurá að Höfða, sem er riðið í kringum á fjögurra tíma túr. Útsýni í allar áttir og horft eftir hvölum í hléum; Eyjafjörður er einn besti staður landsins til að sjá hnúfubaka. Hrísey í sjónmáli. Þrjár til fjórar stundir. Eftir kaffi á Grýtubakka er lagt á aftur í stuttan túr í nágrenni bæjarins, allt að einn og hálfan tíma. Kvöldmatur og gisting á Grýtubakka.",
        en: "After breakfast, we ride towards the longest fjord of Iceland, Eyjafjörður. Riding along the river Gljúfurá we reach the hill Höfði, a remnant of the Ice Age, which we will circuit on our four-hour ride. We enjoy amazing views from different perspectives and look out for whales, during our breaks. The fjord Eyjafjörður is one of the best places to spot whales in Iceland, in particular the huge humpback whales, harbour porpoises, minke whales and northern bottlenose whales. On our way, we also see Hrísey, the second biggest island of Iceland, which gave the fjord its name: The fjord of the island. This ride is three to four hours. After our coffee break at Grýtubakki, we saddle the horses once again and enjoy a short ride in the vicinity of the farm. We will be on to one and a half hours in the saddle. Dinner and overnight stay at Grýtubakki.",
        de: "Heute reiten wir in Richtung des Fjordes Eyjafjörður. Entlang des Flussgebietes der Gljúfurá gelangen wir zum Hügel Höfði, den wir einmal umrunden werden. Während des Rittes zeigt sich die Schönheit des Fjordes aus den verschiedensten Blickwinkeln und fasziniert immer wieder aufs Neue. Wir genießen den Ausblick während der Pausen und mit ein bisschen Glück können wir dem ein oder anderen Wal bei seinem Spiel im klaren Wasser zusehen. Der längste Fjord Islands ist in den letzten Jahren für Wale immer attraktiver geworden - sehr zur Freude unserer Gäste. In der Mitte des Fjordes sehen wir Hrísey, Islands zweitgrößte Insel, welche dem Fjord seinen Namen gegeben hat: Inselfjord. Im Anschluss an den drei- bis vierstündigen Ritt genießen wir auf Grýtubakki bei Kaffee und Kuchen unsere Nachmittagspause. Ausgeruht und satt schwingen wir uns nochmals auf die Pferde und lassen uns überraschen, wohin sie uns tragen werden. Der Ritt dauert 1 1/2 bis 2 Stunden. Abendessen und Übernachtung auf Grýtubakki.",
      } },
      { n: 4, places: ["latrastrond", "svinarnes", "grenivik"], body: {
        is: "Fimm til sex tíma dagsferð út á Látraströnd. Riðið ofan við há björg, yfir tærar lækjarsprænur og um græna dali. Hádegishlé við rústir eyðibýlisins Svínárness, sem var í byggð fram á miðja síðustu öld. Útsýni til Hríseyjar, yfir Eyjafjörð og út á haf; ef til vill hvalir eða selir. Eftir kaffi er ekið í sundlaugina á Grenivík. Kvöldmatur og gisting á Grýtubakka.",
        en: "Today we will go for a five to six hours lasting day ride out to the coast Látrastönd. We ride above steep cliffs, across clear brooks and through wonderful green valleys. We spend our lunch break close to the ruins of the old farmhouse Svínarnes. Inhabited until the middle of the last century, they are witnesses of former life. We enjoy the amazing view to the island Hrísey, over the fjord Eyjafjörður and the open sea. Maybe we get another chance to see some whales or even a few of the shy seals living there. After coffee at Grýtubakki, we drive to the swimming pool of Grenivík. Enjoying the warm water, we have a wonderful view over the fjord and the surrounding mountains. Dinner and overnight stay at Grýtubakki.",
        de: "Heute steht ein vier- bis fünfstündiger Tagesritt auf dem Programm. Wir reiten hinaus zur Küste Látrarströnd – oberhalb steiler Klippen, über gurgelnde Bäche und durch liebliche, tiefgrüne Täler. Die Mittagspause verbringen wir bei Svínarnes, den Ruinen eines alten Farmhauses, welches noch bis Mitte des letzten Jahrhunderts bewohnt war. Von hier aus haben wir einen wunderbaren Blick hinüber zur Insel Hrísey, über den Fjord Eyjafjörður und das offene Meer. Vielleicht können wir auch hier einige Wale oder sogar ein paar scheue Seehunde beobachten. Nach der Kaffeepause auf Grýtubakki fahren wir zum Schwimmbad nach Grenivík. Auch aus dem heißen Wasser des Hotpot haben wir einen wunderschönen Ausblick über den Fjord. Abendessen und Übernachtung auf Grýtubakki.",
      } },
      { n: 5, places: ["skutustadir", "dimmuborgir", "namaskard", "godafoss"], body: {
        is: "Skoðunarferð að Mývatni: gervigígarnir við Skútustaði, Dimmuborgir og hverirnir í Námaskarði. Á heimleið er stoppað við Goðafoss. Eftir kvöldmat á Grýtubakka er lagt á og riðið tvo til þrjá tíma í nágrenni bæjarins; um miðnætti er numið staðar á fallegum stað og miðsumarnóttin notið í félagsskap hestanna. Gist á Grýtubakka.",
        en: "Today we go sightseeing. Today‘s destination is the famous area of the lake Mývatn. We visit the pseudo craters of Skútustaðir, the bizarre lava formations of Dimmuborgir and the bubbling mud pools of Námaskarð. On the way back home, we will have a look at the historical waterfall Goðafoss, which played an important role during Christianisation of Iceland around the year 1000. After dinner at Grýtubakki, we saddle our horses and go for a two to three-hour ride in the surroundings of our farm. Around midnight, we will find a beautiful place to enjoy the midsummer night in company of our horses. Overnight stay at Grýtubakki.",
        de: "Das berühmte Gebiet des Mückensees Mývatn ist heute unser Ziel. Mit dem Bus besuchen wir die Pseudokrater von Skútustaðir, die bizarren Lavaformationen von Dimmuborgir und die brodelnden Schlammkessel von Námskarð. Auf dem Rückweg halten wir noch am Goðafoss, dem geschichtsträchtigen Wasserfall, welcher zur Zeit der Christianisierung eine wichtige Rolle gespielt hat. Nach dem Abendessen auf Grýtubakki satteln wir unsere Pferde und brechen zu einem zwei- bis dreistündigen Ritt in die nähere Umgebung auf. Rund um Mitternacht genießen wir die Sommersonnenwende in Begleitung der Pferde an einem ausgewählten Plätzchen. Übernachtung auf Grýtubakki.",
      } },
      { n: 6, places: ["leirdalsheidi", "fjordur"], body: {
        is: "Riðið til fjalla og inn í Fjörður, eyðibyggð þar sem um 2.500 fjár ganga á sumrin ásamt tröllum og álfum, sbr. örnefnin Trölladal og Álfaborgir. Af Leirdalsheiði er útsýni yfir Eyjafjörð, Grenivík og sveitina. Riðið um græna dali, meðfram ám og yfir grýtta stíga. Komið aftur að Grýtubakka síðdegis eftir fjóra til fimm tíma í hnakknum. Eftir kaffi er tími til að ganga um og kveðja. Kvöldmatur og gisting á Grýtubakka.",
        en: "Today we will ride up to the mountains and into the wild valley Fjörður. Fjörður is a mysterious and deserted countryside. About 2500 sheep spend the summertime here every year, together with the trolls and elves. Names like Trölladalur, the valley of the trolls, and Álfaborgir, the cities of the elves, remind us of the existence of these invisible beings. From the rise of Leirdalsheiði, we have a wonderful view over the fjord Eyjafjörður, the fishing village Grenivík and the surrounding farms. We ride through lush green valleys, along rushing rivers and over stony paths. Extinct volcanoes, silent glaciers and hidden waterfalls accompany us on our ride. In the late afternoon, after about four to five hours in the saddle, we will arrive at Grýtubakki again. After coffee, there is time to go for a walk in the surroundings of our farm and say goodbye. Dinner and overnight stay at Grýtubakki.",
        de: "Nach dem Frühstück starten wir zu einem vier- bis fünfstündigen Tagesritt hinauf in die Berge. Unser heutiges Ziel ist das wilde Tal Fjörður, welches bis zum Ende des 2. Weltkrieges bewohnt war. Heute bevölkern außer den Elfen und Trollen nur noch rund 4.000 Schafe das Gebiet. Die Mutterschafe mit ihren Lämmern werden gegen Mitte Juni hinauf in die Berge getrieben und werden bis Anfang September die Freiheit in dieser einzigartigen Landschaft genießen. Von der Anhöhe Leirdalsheiði aus haben wir einen wunderschönen Blick über den gesamten Eyjafjörður, das Fischerdorf Grenivík und die umliegenden Farmen. Wir reiten durch saftig grüne Täler, abwechslungsreiche Flusslandschaften und über steinige Wege. Erloschene Vulkane, schweigende Gletscher und versteckte Wasserfälle begleiten uns. Nach der Kaffeepause mit selbstgebackenem Kuchen lädt der späte Nachmittag zu einem Spaziergang in der Umgebung der Farm ein. Es ist Zeit, Abschied zu nehmen. Ein letztes gemeinsames Abendessen auf der Farm erwartet uns. Übernachtung auf Grýtubakki.",
      } },
      { n: 7, kind: "departure", places: ["akureyri"], body: {
        is: "Eftir morgunmat er ekið með gesti aftur til Akureyrar.",
        en: "After breakfast, we will bring our guests back to Akureyri.",
        de: "Nach dem Frühstück bringen wir unsere Gäste zurück nach Akureyri.",
      } },
    ],
  },
  "fascinating-north": {
    days: [
      { n: 1, kind: "arrival", places: ["akureyri", "grytubakki"], body: {
        is: "Síðdegis, oftast milli kl. 16 og 18, sækjum við þig á Akureyri og ökum að Grýtubakka. Gist í litlu gestahúsunum okkar með sameiginlegu baði. Við kynnumst yfir kvöldmat og endum daginn á að fara yfir ferðina í smáatriðum.",
        en: "In the late afternoon (mostly between 4 pm and 6 pm), we will pick you up from Akureyri and bring you to our farm Grýtubakki. There, you will be lodged at our little guesthouses with a shared bathroom. We will get to know each other during dinner and we will end the day with a detailed description of the tour.",
        de: "Am späten Nachmittag (meist zwischen 16 und 18 Uhr) holen wir Sie in Akureyri ab und bringen Sie zu unserer Farm Grýtubakki. Dort werden Sie in unseren kleinen Gästehäusern mit Gemeinschaftsbad untergebracht. Beim Abendessen lernen wir uns kennen und beenden den Tag mit einer detaillierten Beschreibung der Tour.",
      } },
      { n: 2, places: ["godafoss", "fremstafell", "sandur"], body: {
        is: "Eftir morgunmat er ekið að Goðafossi. Hestarnir bíða aðeins ofar, við Fremstafell. Riðið norður um Fellsskóg, meðfram Skjálfandafljóti og fram hjá fossunum Ullarfossi og Barnafossi. Hádegishlé á árbakkanum áður en áin er riðin og fylgt norður að Sandi, eftir sandstígum í jaðri Aðaldalshrauns, sem er vaxið lágu birki og kjarri. Kvöldmatur og gisting í uppábúnum rúmum í gistihúsinu á Sandi.",
        en: "After breakfast, we take the bus to Goðafoss. Here you can enjoy this breathtaking waterfall, which has played a significant role during Christianization in Iceland. Our horses are waiting a little bit further on at farmhouse Fremstafell for us. We start to ride north, through the forest Fellskógur, alongside the river Skjálfandafljót and by the waterfalls Ullarfoss and Barnafoss. We will have our lunch break at the bank of the river before crossing it and following the river further north to Sandur. We will be riding on sandy paths on the edge of Aðaldalshraun, which is a lava field covered with low birch and bushes. Dinner and overnight at Sandur guesthouse in made – up beds.",
        de: "Nach dem Frühstück fahren wir mit dem Bus nach Goðafoss. Hier können Sie diesen atemberaubenden Wasserfall bewundern, der während der Christianisierung Islands eine bedeutende Rolle gespielt hat. Unsere Pferde warten etwas weiter entfernt auf dem Bauernhof Fremstafell auf uns. Wir reiten in Richtung Norden, durch den Wald Fellskógur, entlang des Flusses Skjálfandafljót und vorbei an den Wasserfällen Ullarfoss und Barnafoss. Wir machen unsere Mittagspause am Ufer des Flusses, bevor wir ihn überqueren und dem Fluss weiter nach Norden bis nach Sandur folgen. Wir reiten auf sandigen Pfaden am Rande von Aðaldalshraun, einem Lavafeld, das mit niedrigen Birken und Büschen bewachsen ist. Abendessen und Übernachtung im Gästehaus Sandur in gemachten Betten.",
      } },
      { n: 3, places: ["nattfaravikur", "heidarbot"], body: {
        is: "Morgunreið án lausa stóðsins, meðfram sandströndinni við ósa Skjálfandafljóts, skammt frá Náttfaravíkum þar sem Náttfari, þræll Garðars Svavarssonar, settist að. Eftir hádegi er riðið með stóðinu að Heiðarbót, meðfram Miklavatni og litlu ánni Mýrarkvísl. Eftir reiðina er farið í sund. Kvöldmatur og gisting á Sandi.",
        en: "Today we make a morning ride without the free-running herd. We ride alongside the sandy beach by the bay of Skjálfandafljót. We are close to Náttfaravíkur, where Náttfari settled - a slave from Garðar Svavarsson, which is said to be the second settler of Iceland. After lunch we will ride with the herd again and head towards Heiðarbót. We ride alongside a small lake called Miklavatn and follow the little river Mýrarkvísl. After the ride we will go swimming in a local swimming pool. Dinner and overnight at Sandur guesthouse in made-up beds.",
        de: "Am Vormittag machen wir einen Ausritt ohne Herde zum Meer. Der Ausritt führt uns entlang des Sandstrandes an der Bucht von Skjálfandafljót. Wir befinden uns in der Nähe von Náttfaravíkur, wo sich Náttfari niedergelassen hat – ein Sklave von Garðar Svavarsson, der als zweiter Siedler Islands gilt. Am Nachmittag reiten wir mit der Herde entlang eines kleinen Sees namens Miklavatn, Richtung Heiðarbót. Dort lassen wir die Herde und fahren ins Schwimmbad. Abendessen und Übernachtung im Sandur Guesthouse in gemachten Betten.",
      } },
      { n: 4, places: ["laxa", "reykjadalur", "vestmannsvatn"], body: {
        is: "Eftir góðan morgunmat sækjum við hestana. Eftir um þriggja tíma reið er riðið yfir Laxá, sem oft er kölluð drottning laxveiðiánna; áin er ekki djúp en það getur blotnað. Þá erum við komin í Reykjadal og höldum suður eftir skógivöxnum reiðstíg undir Vatnshlíð, með einstöku útsýni niður dalinn að Vestmannsvatni. Eftir fimm til sex tíma kveðjum við hestana, sem verða á stóru túni á Ökrum í Reykjadal. Ekið að Vestmannsvatni þar sem gist er næstu þrjár nætur í uppábúnum rúmum.",
        en: "After an extensive breakfast, we pick up our horses. After about three hours of riding, we will cross the river, which has often been called the queen of salmon rivers in Iceland. Even though the river is not really deep you might get wet – depending on the size of your horse😊After crossing the river Laxá, we have arrived in the valley of smoke - Reykjadalur. We are still making our way further south, riding alongside Vatnshlíð on a forested riding path. The view down into the valley Reykjadalur all the way to lake Vestmannsvatn is unique. After about five to six hours of riding, we bid our horses farewell. They will stay on a big field of farm Akrar, which is in the valley Reykjadalur. We drive to Vestmannsvatn, where we will spend the next 3 nights in made – up beds.",
        de: "Nach einem ausgiebigen Frühstück fahren wir zu unseren Pferden. Nach etwa drei Stunden Reiten überqueren wir den Fluss, der oft als die Königin der Lachsflüsse Islands bezeichnet wird. Auch wenn der Fluss nicht besonders tief ist, könnten Sie nass werden – je nach Größe Ihres Pferdes😊Nachdem wir den Fluss Laxá überquert haben, erreichen wir das Rauchtal – Reykjadalur. Wir reiten weiter in Richtung Süden, entlang Vatnshlíð auf einem bewaldeten Reitweg. Der Blick hinunter ins Tal Reykjadalur bis zum See Vestmannsvatn ist einzigartig. Nach etwa fünf bis sechs Stunden Reiten verabschieden wir uns von unseren Pferden. Sie bleiben auf einer großen Weide der Farm Akrar, die im Tal Reykjadalur liegt. Wir fahren nach Vestmannsvatn, wo wir die nächsten drei Nächte in gemachten Betten verbringen werden.",
      } },
      { n: 5, places: ["akrar", "masvatn", "myvatn", "stong"], body: {
        is: "Ekið til baka að hestunum, um tíu mínútur. Frá Ökrum er riðið suður í átt að Mývatnssveit. Hádegishlé við Másvatn, síðan suðvestur eftir gömlu Akureyrarleiðinni, sem Íslendingar fóru forðum milli landshluta. Fjölbreytt land og mjúkir reiðstígar, útsýni yfir Mývatn úr hnakknum. Komið að Stöng þar sem hestarnir fá stórt tún. Kvöldmatur og gisting á Vestmannsvatni.",
        en: "From Vestmannsvatn, we drive back to our horses and saddle them. The drive takes around 10 minutes. From Akrar, we ride further south towards the Mývatn area. At Másvatn, we will have our lunch break before heading south - west on an old “highway” called Akureyrarleiðin. Akureyrarleiðin is an old path that many Icelanders went in former times when going from the eastern part of the country to the western part or vice versa. A diverse landscape with soft riding tracks awaits us. We will have the chance to enjoy the panoramic view surrounding the lake Mývatn on our horses. Our destination is Stöng, where we will leave the horses on a big field with loads of grass for them. Dinner and overnight at Vestmannsvatn in made-up beds.",
        de: "Von Vestmannsvatn aus fahren wir zurück zu unseren Pferden und satteln sie. Die Fahrt dauert etwa 10 Minuten. Von Akrar aus reiten wir weiter südlich in Richtung Mývatn. In Másvatn machen wir Mittagspause, bevor wir auf einem alten Volksweg namens Akureyrarleiðin in Richtung Südwesten weiterreiten. Akureyrarleiðin ist ein alter Weg, den viele Isländer früher benutzten, um vom östlichen Teil des Landes in den westlichen Teil oder umgekehrt zu gelangen. Es erwartet uns eine abwechslungsreiche Landschaft mit sanften Reitwegen. Wir haben die Möglichkeit, auf unseren Pferden den Panoramablick rund um den See Mývatn zu genießen. Unser Ziel ist Stöng, wo wir die Pferde auf einer großen Wiese mit viel Gras für sie zurücklassen. Abendessen und Übernachtung in Vestmannsvatn in gemachten Betten.",
      } },
      { n: 6, places: ["engidalur", "odadahraun", "bardardalur"], body: {
        is: "Eftir morgunmat á Vestmannsvatni er haldið að hestunum á Stöng í Mývatnssveit. Riðið suður í átt að Engidal þar sem hádegishlé er tekið, þaðan eftir mjúkum stígum yfir í næsta dal vestar, skammt frá Ódáðahrauni, hinu mikla hrauni sem útilegumenn, álfar og tröll áttu að byggja. Síðdegis er komið í Bárðardal þar sem hestarnir gista. Kvöldmatur og gisting á Vestmannsvatni.",
        en: "After breakfast in Vestmannsvatn, we head to our horses at Stöng in Mývatnssveit. We continue our ride towards south direction Engidalur, where we will have our lunch break. From Engidalur we ride on soft paths into the next valley further west. Here we are very close to the entrance of Ódaðahraun, the enourmous lava field, believed to be the home of outlaws, elves and trolls in the old days. In the late afternoon we will arrive in Bárðardalur, where we will leave our horses for the night. Dinner and overnight in Vestmannsvatn in made-up beds.",
        de: "Nach dem Frühstück in Vestmannsvatn fahren wir zu unseren Pferden nach Stöng in Mývatnssveit. Von dort aus setzen wir unseren Ritt in südlicher Richtung nach Engidalur fort, wo wir eine Mittagspause einlegen. Von Engidalur aus reiten wir auf weichen Wegen in das nächste, weiter westlich gelegene Tal. Hier befinden wir uns ganz in der Nähe des Eingangs zum Ódaðahraun, dem grossen Lavafeld, das früher als Heimat von Gesetzlosen, Elfen und Trollen galt. Am späten Nachmittag erreichen wir Bárðardalur, wo wir unsere Pferde für die Nacht unterbringen. Abendessen und Übernachtung in Vestmannsvatn in gemachten Betten.",
      } },
      { n: 7, places: ["bardardalur", "fremstafell", "grytubakki"], body: {
        is: "Síðasti dagurinn í hnakknum. Eftir morgunmat er ekið að hestunum og riðið aftur að Fremstafelli, um Bárðardal meðfram Skjálfandafljóti sem rennur yfir Bárðardalshraun, komið alla leið frá Trölladyngju í Ódáðahrauni fyrir meira en 7.000 árum. Hádegishlé við ána. Við komuna er hestunum þakkað fyrir sig og ekið að Grýtubakka í kvöldmat og gistingu í uppábúnum rúmum.",
        en: "Today marks our final day in the saddle. After breakfast, we drive to our horses, saddle them and start our ride back to farmhouse Fremstafell. We ride through the Bardardalur valley, following the river Skjálfandafljót, which flows through the valley over the Bárðardalshraun lava field that came all over the way from Trölladyngja in Ódaðahraun north of Vatnajökull more than 7,000 years ago. We will pause for a well-earned lunch break by the riverside. Once we arrive, it is time to bid our horses farewell and drive back to Grýtubakki for dinner and overnight in made – up beds.",
        de: "Heute ist unser letzter Tag im Sattel. Nach dem Frühstück fahren wir zu unseren Pferden, satteln sie und beginnen unseren Ritt zurück zum Bauernhof Fremstafell. Wir reiten durch das Tal Bárðardalur und folgen dem Fluss Skjálfandafljót, der durch das Tal fließt und dabei das Lavafeld Bárðardalshraun durchquert. Dieses Lavafeld stammt ursprünglich von der Trölladyngja im Ódaðahraun, nördlich des Vatnajökull, und entstand vor mehr als 7.000 Jahren. Am Flussufer legen wir eine wohlverdiente Mittagspause ein. Nach unserer Ankunft heißt es, Abschied von unseren Pferden zu nehmen. Anschließend fahren wir zurück nach Grýtubakki, wo uns ein Abendessen und eine Übernachtung in gemachten Betten erwarten.",
      } },
      { n: 8, kind: "departure", places: ["akureyri"], body: {
        is: "Eftir morgunmat ökum við þér aftur til Akureyrar.",
        en: "After breakfast, we will drive you back to Akureyri.",
        de: "Nach dem Frühstück fahren wir Sie zurück nach Akureyri.",
      } },
    ],
  },
  "hidden-pearls": {
    days: [
      { n: 1, kind: "arrival", places: ["akureyri", "grytubakki"], body: {
        is: "Síðdegis, oftast milli kl. 16 og 18, sækjum við þig á Akureyri og ökum að Grýtubakka. Gist í litlu gestahúsunum okkar með sameiginlegu baði. Við kynnumst yfir kvöldmat og endum daginn á að fara yfir ferðina í smáatriðum.",
        en: "In the late afternoon (mostly between 4 pm and 6 pm), we will pick you up from Akureyri and bring you to our farm Grýtubakki. There, you will be lodged at our little guesthouses with a shared bathroom. We will get to know each other during dinner and we will end the day with a detailed description of the tour.",
        de: "Am späten Nachmittag (meist zwischen 16 und 18 Uhr) holen wir Sie in Akureyri ab und bringen Sie zu unserer Farm Grýtubakki. Dort werden Sie in unseren kleinen Gästehäusern mit Gemeinschaftsbad untergebracht. Beim Abendessen lernen wir uns kennen und beenden den Tag mit einer detaillierten Beschreibung der Tour.",
      } },
      { n: 2, places: ["fremstafell", "fnjoskadalur", "thvera"], body: {
        is: "Eftir morgunmat er ekið að Fremstafelli, skammt frá Goðafossi, þar sem hestarnir bíða. Ferðinni er heitið að Þverá í Fnjóskadal, meðfram Fnjóská og grónum bökkum hennar, um 35 km. Fyrsti dagur af fjórum með lausa stóðinu. Við komuna að Þverá eru hestarnir skildir eftir og ekið heim að Grýtubakka. Kvöldmatur og gisting í svefnpokaplássi á Grýtubakka.",
        en: "After breakfast, we drive to Fremstafell, near the Goðafoss waterfall, where we meet our horses. Our destination is the farm Þverá in Fnjóskárdalur. We follow the contours of the Fnjóská River, with its gentle banks lined by verdant vegetation. Covering approximately 35 km, the ride follows trails alongside the Fnjóská River. This is the first day of 4, where we ride with the free – running herd. The rhythm of hooves and the sweeping views of the valley offer a feeling of peace and adventure combined. When we have arrived in Þverá, we leave the horses and drive home to farm Grýtubakki. Dinner and overnight in sleeping bag accommodation at Grýtubakki.",
        de: "Nach dem Frühstück fahren wir nach Fremstafell in der Nähe des Wasserfalls Goðafoss, wo wir unsere Pferde treffen. Unser Ziel ist die Farm Þverá in Fnjóskárdalur. Die etwa 35 km lange Tour führt auf Pfaden entlang des Flusses Fnjóská, mit seinen sanften Ufern, die von üppiger Vegetation gesäumt sind.  Dies ist der erste von vier Tagen, an denen wir mit der frei laufenden Herde reiten. Der Rhythmus der Hufe und der weite Blick über das Tal vermitteln ein Gefühl von Ruhe und Abenteuer zugleich. In Þverá angekommen, lassen wir die Pferde zurück und fahren zurück zur Farm Grýtubakki. Abendessen und Übernachtung in Schlafsäcken in Grýtubakki.",
      } },
      { n: 3, places: ["thvera", "flateyjardalur", "hof"], body: {
        is: "Frá Þverá yfir afskekkta fjallaleið úr dalnum út að strönd, í Flateyjardal. Fyrst grösug tún, svo grófara og opnara land upp á hæsta punkt leiðarinnar; riðið með stóðinu og skipt um hest eftir þörfum. Svo niður í Flateyjardal, langan eyðidal sem opnast til hafs, fram hjá rústum eyðibýla þar til fjöllin mæta svörtum sandi. Um 30–35 km. Kvöldmatur og gisting í Hofi í Flateyjardal.",
        en: "The ride from Þverá to Flateyjardalur takes you over a remote mountain pass leading from the inland valley out to the coast. Leaving Þverá, the trail begins with grassy fields and gradually climbs into rougher, more open terrain. Again, you ride with the herd of free-running horses, switching horses as needed throughout the day. After reaching the highest point of the route, the trail begins to descend towards Flateyjardalur, a long, empty valley that stretches out towards the sea. The last part of the ride follows a track down the valley floor, passing old ruins and the remains of abandoned farms. The day ends near the ocean, where the mountains meet the black sand coastline. This route is around 30–35 km long. Dinner and overnight in Hof in Flateyjardalur.",
        de: "Der Ritt von Þverá nach Flateyjardalur führt über einen abgelegenen Bergpass, der vom Tal im Landesinneren zur Küste hinausgeht. Von Þverá beginnt der Weg mit grasbewachsenen Feldern und steigt allmählich in raueres, offeneres Gelände an. Auch hier reiten wir wieder mit einer Herde frei laufender Pferde und wechseln im Laufe des Tages nach Bedarf die Pferde. Nachdem Sie den höchsten Punkt der Route erreicht haben, beginnt der Weg in Richtung Flateyjardalur abzusteigen, einem langen Tal, das sich bis zum Meer erstreckt. Der letzte Teil des Rittes folgt einem Weg entlang des Talbodens, vorbei an alten Ruinen und den Überresten verlassener Bauernhöfe. Der Tag endet in der Nähe des Meeres, wo die Berge auf die Küste treffen. Diese Route ist etwa 30–35 km lang. Abendessen und Übernachtung in Hof in Flateyjardalur.",
      } },
      { n: 4, places: ["flateyjardalur", "thvera", "grenivik"], body: {
        is: "Eftir morgunmat í Hofi er riðið sömu leið til baka að Þverá, stóðið ræður hraðanum. Frá Þverá er ekið að Grýtubakka í kaffi og kökur. Síðdegis er farið í sund á Grenivík með útsýni inn Eyjafjörð. Kvöldmatur og gisting á Grýtubakka.",
        en: "After breakfast in Hof we head back from Flateyjardalur to Þverá. The herd sets the pace as usual. After we have arrived in Þverá, we drive to our farm Grýtubakki for coffee and cakes. In the late afternoon, we go for swimming in the pool in Grenivík, wich offers a nice view towards the end of Fjord Eyjafjörður. Dinner and overnight in Grýtubakki.",
        de: "Nach dem Frühstück in Hof reiten wir von Flateyjardalur zurück nach Þverá. Wie immer bestimmt die Herde das Tempo. Nach unserer Ankunft in Þverá fahren wir zu unserer Farm Grýtubakki, wo wir Kaffee und Kuchen genießen. Am späten Nachmittag gehen wir zu dem Schwimmbad in Grenivík, von wo aus man einen schönen Blick auf den Ausgang des Fjordes Eyjafjörður hat. Abendessen und Übernachtung in Grýtubakki.",
      } },
      { n: 5, places: ["thvera", "grytubakki"], body: {
        is: "Hestarnir reknir frá Þverá heim að Grýtubakka. Fyrir um 10.000 árum var stórt jökullón í dalnum og strandlínur þess sjást enn í hlíðunum beggja vegna. Við komuna heim er farinn eins og hálfs tíma túr í kringum bæinn, án stóðsins. Kvöldmatur og gisting á Grýtubakka.",
        en: "Today, we bring the horses back from Þverá home to the farm Grýtubakki. About 10.000 years ago there was a huge glacial lake in this valley and the shores of it are still visible at the slopes of the mountain on both sides. When we have arrived at the farm, we go for a 1,5 hour tour surrounding the farm without the herd. Dinner and overnight at Grýtubakki.",
        de: "Heute bringen wir die Pferde von Þverá zurück zur Farm Grýtubakki. Vor etwa 10.000 Jahren gab es in diesem Tal einen riesigen Gletschersee, dessen Ufer noch heute an den Hängen des Berges auf beiden Seiten zu sehen sind. Wenn wir auf der Farm angekommen sind, machen wir eine 1,5-stündige Tour in der Umgebung, ohne die Herde. Heute gehen wir alles etwas ruhiger an und bereiten uns auf die kommenden 3 Reittage in den Bergen vor. Abendessen und Übernachtung in Grýtubakki.",
      } },
      { n: 6, places: ["thorgeirsfjordur", "thonglabakki"], body: {
        is: "Fyrsti dagur þriggja daga ferðar um kyrrláta eyðibyggð Þorgeirsfjarðar, með einn trússhest. Riðið frá Grýtubakka út að strönd og inn í Þorgeirsfjörð, um land þar sem um 3.000 fjár ganga og óvíst hve margir álfar og tröll, sbr. Trölladal og Álfaborgir. Haldið á jöfnum hraða eftir opnum slóðum að eyðibýlinu Þönglabakka, þar sem gist er tvær nætur í einföldum fjallaskála.",
        en: "This is the first day of our 3 – day tour which takes you on horseback through the peaceful and remote landscapes of Þorgeirsfjörður. We travel with one pack horse, carrying supplies for the journey. We ride from Grýtubakki out towards the coast, heading into the quiet valley of Þorgeirsfjörður. We ride through a deserted countryside populated with around 3.000 sheep and who knows how many elves and trolls. Names like Trölladalur – valley of the trolls and Álfaborgir – cities of the elves, remind us of the existence of these invisible beings. They have chosen some of the best places for their homes. The pace is steady as we follow open trails, moving with our horses towards the old farm Þönglabakki, where we spend two nights in a simple mountain hut.",
        de: "Dies ist der erste Tag unserer dreitägigen Tour, die Sie zu Pferd durch die friedliche und abgelegene Landschaft von Þorgeirsfjörður führt. Wir reiten mit einem Packpferd, das die Vorräte für die kommenden Tage mit sich trägt. Wir reiten von Grýtubakki aus in Richtung Küste und gelangen in das ruhige Tal von Þorgeirsfjörður. Unser Weg führt uns durch eine menschenleere Landschaft, in der etwa 3.000 Schafe und wer weiß wie viele Elfen und Trolle leben. Namen wie Trölladalur – Tal der Trolle und Álfaborgir – Städte der Elfen erinnern uns an die Existenz dieser unsichtbaren Wesen. Sie haben sich einige der besten Orte für ihre Behausungen ausgesucht. Wir reiten in gleichmäßigem Tempo auf offenen Pfaden und bewegen uns mit unseren Pferden in Richtung der alten Farm Þönglabakki, wo wir zwei Nächte in einer einfachen Berghütte verbringen.",
      } },
      { n: 7, places: ["thorgeirshofdi", "thonglabakki"], body: {
        is: "Dagurinn fer í að skoða svæðið. Riðið að eyðibýlunum Botni og Hóli um græn engi og lágar hæðir, og áfram út á Þorgeirshöfða, sem lokar firðinum, með víðu útsýni yfir haf og fjöll. Rólegur dagur með tíma fyrir sögu og kyrrð. Kvöldmatur og gisting í skálanum á Þönglabakka.",
        en: "This day is dedicated to exploring the area. We ride to the abandoned farms Botn and Hóll, passing through green meadows and low hills that once supported isolated farming life. We continue to Þorgeirshöfði, the cape that marks the mouth of the fjord, with wide views over the ocean and surrounding mountains. The ride is relaxed, allowing time to take in the history and stillness of the area. Dinner and overnight in Þönglabakki mountain hut.",
        de: "Dieser Tag ist der Erkundung der Umgebung gewidmet. Wir reiten zu den verlassenen Bauernhöfen Botn und Hóll, vorbei an grünen Wiesen und sanften Hügeln, die einst das Leben isolierter Bauern prägten. Weiter geht es nach Þorgeirshöfði, dem Kap, das die Mündung des Fjordes markiert und einen weiten Blick über das Meer und die umliegenden Berge bietet. Der Ritt ist entspannt, sodass Zeit bleibt, die Geschichte und Stille der Gegend auf sich wirken zu lassen. Abendessen und Übernachtung in der Berghütte Þönglabakki.",
      } },
      { n: 8, places: ["grytubakki", "grenivik"], body: {
        is: "Pakkað saman og riðið til baka að Grýtubakka, svipaða leið um dalinn með trússhestinn í taumi og hafið að baki. Síðdegis í sund á Grenivík, gott fyrir vöðvana eftir sjö daga í hnakknum. Kvöldmatur og gisting á Grýtubakka.",
        en: "We pack up and ride back to Grýtubakki, following a similar route through the valley, with the pack horse in tow and the sea now behind us. In the late afternoon, we go to Grenivík for swimming. It is good to relax your muscles after 7 days of riding. Dinner and overnight at Grýtubakki.",
        de: "Wir packen unsere Sachen und reiten zurück nach Grýtubakki, wobei wir einer ähnlichen Route durch das Tal folgen, mit dem Packpferd im Schlepptau und dem Meer nun hinter uns. Am späten Nachmittag fahren wir zum Schwimmen nach Grenivík. Es tut gut, nach 7 Tagen Reiten die Muskeln zu entspannen. Abendessen und Übernachtung in Grýtubakki.",
      } },
      { n: 9, kind: "departure", places: ["akureyri"], body: {
        is: "Eftir morgunmat ökum við þér aftur til Akureyrar.",
        en: "After our breakfast, we will drive you back to Akureyri.",
        de: "Nach dem Frühstück fahren wir Sie zurück nach Akureyri.",
      } },
    ],
  },
  "autumn-northern-lights": {
    days: [
      { n: 1, kind: "arrival", places: ["akureyri", "grytubakki"], body: {
        is: "Gestir eru sóttir á Akureyri síðdegis. Hálftíma akstur að Grýtubakka með útsýni yfir Eyjafjörð á leiðinni. Eftir kvöldmat er farið yfir dagskrá næstu daga. Gist á Grýtubakka.",
        en: "Our guests are picked up in Akureyri in the late afternoon. A 30 minutes’ drive will bring us to the farmhouse Grýtubakki. On the way you may admire the beautiful view over the fjord Eyjafjörður. After dinner details about the next days will be provided. Overnight stay at Grýtubakki.",
        de: "Im Verlaufe des späteren Nachmittags holen wir unsere Gäste aus Akureyri ab. Nach einem gemeinsamen Abendessen werden sie mit dem Programm der nächsten Tage vertraut gemacht. Übernachtung auf unserer Farm Grýtubakki.",
      } },
      { n: 2, places: ["fjordur", "hofdi"], body: {
        is: "Eftir morgunmat eru hestarnir sóttir og lagt á. Riðið upp að mynni Fjarða og í kringum Höfða, með útsýni yfir Eyjafjörð, lengsta fjörð landsins; hvalir hafa sést í firðinum fram í október. Um fjórir tímar í hnakknum. Kaffi og kökur á bænum. Kvöldmatur og gisting á Grýtubakka.",
        en: "After breakfast we catch the horses and saddle up for a ride up to the entrance of the peninsula Fjörður and around mountain Höfði. We enjoy the breathtaking view over Eyjafjörður, the longest fjord in Iceland. Maybe we are lucky and see some whales. They have been spotted in the fjord until October. We are approximately 4 hours in saddle. Back at the farm, coffee and cakes are served. Dinner and overnight stay at Grýtubakki.",
        de: "Nach dem Frühstück reiten wir hinauf zum Eingang des Tales Fjörður, von wo aus wir einen fantastischen Blick über die gesamte Umgebung und den Fjord Eyjafjörður haben. Anschließend führt uns unser Weg um den Hügel Höfði herum. Wir genießen die Aussicht auf den Fjord und die Insel Hrisey, welche bis vor ein paar Jahren noch als Quarantänestation gedient hat. Vorbei geht es an Hrafnabjörg, den Rabenfelsen, und dem unter uns liegenden Tal der Kühe, zu welchem es eine interessante Geschichte zu erzählen gibt. An einem der vielen schönen Pausenplätze verbringen wir unsere Mittagspause. Mit ein bisschen Glück bekommen wir auch zu dieser Jahreszeit noch Wale zu Gesicht. Diese tummeln sich bis weit in den Oktober hinein im Fjord. Am Fluss Gljúfurá entlang geht es zurück zur Farm, wo wir mit Kaffee und Kuchen erwartet werden. Wir sind ungefähr 4 Stunden im Sattel. Abendessen und Übernachtung auf Grýtubakki.",
      } },
      { n: 3, places: ["grenivik", "latrastrond", "svinarnes"], body: {
        is: "Um morguninn er farið í hvalaskoðun frá Grenivík. Eftir kaffi er riðið að Grenivík og þaðan út Látraströnd, ofan við há björg, um gróin engi, tæra læki og tilkomumikla dali. Hlé við rústir Svínárness. Hér ganga trippi bændanna sumarlangt en halda brátt heim þegar haustlitirnir boða vetur. Sama leið til baka; fjórir tímar í hnakknum. Kvöldmatur og gisting á Grýtubakka.",
        en: "In the morning we will go for a whale watching trip from Grenivík. After coffee we ride towards the fishing village Grenivik and from there along the coast Látrarströnd. We ride above steep cliffs, through luxurious meadows, clear brooks and impressive valleys. We have our break close to the ruins of the farmhouse Svínarnes, which are witnesses of bygone times. In this area the young horses of the farmers are spending the summer, but soon they will turn back to their home meadows as the intensive autumn colours are early signs of the coming winter. We take the same way back to the farm. After four hours in the saddle we will reach Grýtubakki again. Dinner and overnight stay at Grýtubakki.",
        de: "Nach dem Frühstück starten wir mit einer Walbeobachtungstour. Am Nachmittag reiten wir an die Küste von Látrarströnd. Auf unserem Weg reiten wir an dem kleinen Fischerdörfchen Grenivík vorbei, welches rund 250 Einwohner hat. Wir reiten oberhalb steiler Klippen, durch sprudelnde Bäche und entlang bezaubernder, tiefgrüner Täler. In der abgeschiedenen isländischen Natur kreuzen oft Schafe unseren Weg. Die Mittagspause verbringen wir bei Svínarnes, den Ruinen eines alten Farmhauses, welches noch bis Mitte des letzten Jahrhunderts bewohnt war. Die Jungpferde der Farmer aus der Umgebung verbringen in diesem Küstengebiet den Sommer, lernen in der Natur zu überleben und trittsicher zu werden. Bald ist es aber an der Zeit, sie auf die Heimatwiesen zurück zu treiben, denn die intensiven Herbstfarben sind ein frühes Zeichen für den kommenden Winter. Abendessen und Übernachtung auf Grýtubakki.",
      } },
      { n: 4, places: ["fnjoskadalur", "godafoss"], body: {
        is: "Eftir morgunmat er riðið inn Fnjóskadal, með allt að 1.000 metra há fjöll beggja vegna. Riðið sunnan ár, fram hjá lækjum, mosavöxnum hæðum og litlum haustlituðum skógum; gæsahópar búa sig undir ferðina suður. Hádegishlé í dalnum, svo til baka að Grýtubakka. Eftir kaffi er ekið að Goðafossi. Kvöldmatur og gisting á Grýtubakka.",
        en: "After breakfast, we ride into the valley of the river Fnjóská. On both sides of the river there are mountains up to 1000 metres height. We ride along the southern side of the valley, by murmuring brooks, mossy hills and through little forests coloured by the autumn. Cackling geese are sitting in flocks at the bank of the river, preparing themselves for their journey to the south. They are going to spend the winter in warmer areas but are coming back to Iceland in spring when the sun starts to shine for longer hours again. After our lunch break in this valley we turn back to Grýtubakki. After coffee we will drive to the famous waterfall Goðafoss, which has played an important role during the Christianisation of Iceland. This waterfall is one of the most beautiful ones in Iceland. Dinner and overnight stay at Grýtubakki.",
        de: "Heute brechen wir zu einem vier- bis fünfstündigen Ritt in das Tal der Fnjóská, dem längsten Sammelfluss Islands, auf. Vor rund 10.000 Jahren staute sich in diesem Tal ein Gletschersee, dessen Ufer man noch heute an den Berghängen erkennen kann. Wir reiten von Grýtubakki aus gen Süden, vorbei an einem Elfenstein, über den es eine interessante Geschichte zu erzählen gibt, und über die alte Brücke weiter hinein ins Tal. Unser Weg führt flussaufwärts durch idyllische, abwechslungsreiche Landschaften. Oft sind auf dieser Strecke gackernde Gänse anzutreffen, die in Scharen an den Ufern des Flusses sitzen und sich auf den Flug in den Süden vorbereiten. Nach einer gemütlichen Mittagspause im Tal reiten wir zurück in Richtung der Farm. Auf dem Weg haben wir einen wunderschönen Blick auf das Sumpfgebiet und Delta des Flusses Fnjóská. Nach der Kaffeepause fahren wir mit dem Bus zum Goðafoss, dem geschichtsträchtigen Wasserfall, welcher zur Zeit der Christianisierung Islands eine große Rolle gespielt hat. Abendessen und Übernachtung auf Grýtubakki.",
      } },
      { n: 5, places: ["trolladalur", "gil", "leirdalsheidi"], body: {
        is: "Riðið til fjalla, að fjallaskálanum Gili innst í Trölladal. Af hæsta punkti, Leirdalsheiði, er útsýni yfir Hvalvatnsfjörð og út á Íshaf. Eftir kvöldmat er gengið undir stjörnum og vonandi sjást norðurljósin dansa, fjarri öllum ljósum byggðar. Kvöldmatur og gisting í skálanum Gili.",
        en: "Today we will ride up to the mountains. Our destination is the mountain hut Gil at the end of the valley Trölladalur. From the highest point at Leirðalsheiði we have a fantastic view over the fjord Hvalvatnsfjörður and the open polar sea. After dinner, there is time to go for a walk under the stars and hopefully see some of the dancing northern lights. A wonderful experience far away from civilisation and all the electric lights of the cities. Dinner and overnight stay at the mountain hut Gil.",
        de: "Unser heutiges Ziel ist das wilde Tal Fjörður, welches bis Ende des 2. Weltkrieges bewohnt war. Heute bevölkern außer den Elfen und Trollen nur noch rund 4.000 Schafe das Gebiet, welche jeden Sommer für einige Monate lang die Freiheit dieser einzigartigen Landschaft genießen. Von der Anhöhe Leirdalsheiði aus haben wir einen wunderschönen Blick über den gesamten Eyjafjörður, das Fischerdorf Grenivík und die umliegenden Farmen. Intensive Herbstfarben begleiten uns auf unserem Ritt. Am höchsten Punkt des Tales erwartet uns ein überwältigender Ausblick hinaus auf das Polarmeer. Von hier aus ist auch die Berghütte Gil am Ausgang des Tals der Trolle, in der wir die Nacht verbringen werden, bereits sichtbar. Wir sind vier bis fünf Stunden im Sattel. Nach dem Abendessen ist noch Zeit für einen Spaziergang unter den Sternen, in der Hoffnung, ein paar Nordlichter über den Himmel huschen zu sehen. Weit weg von der Zivilisation und den Lichtern der Stadt genießen wir den Abend in diesem abgelegenen Tal.",
      } },
      { n: 6, places: ["grytubakki"], body: {
        is: "Eftir morgunmat er lagt á og riðið heim að Grýtubakka. Á leiðinni sést eitthvað af þeim þúsundum fjár sem gengu á fjalli í sumar og eru nú á heimleið áður en snjóar. Fjórir til fimm tímar í hnakknum eins og daginn áður. Kaffi og kökur bíða á Grýtubakka. Síðasti kvöldmaturinn og gisting á Grýtubakka.",
        en: "After breakfast, we saddle up again and leave this beautiful place to ride home to our farmhouse Grýtubakki. On the way we will see some of the many thousands of sheep that have spent the summer months here up in the mountains. They are on their way back home, knowing that soon everything will be covered by snow. Like the day before we ride for about four to five hours. Coffee and cakes are waiting for us at Grýtubakki. A last dinner and overnight stay at Grytubakki.",
        de: "Nach dem Frühstück treten wir unseren Weg zurück nach Grýtubakki an. Unterwegs werden uns sicherlich noch einige Schafe begegnen, welche ebenfalls in Richtung des Tales unterwegs sind. Sie wissen, dass es nun Zeit ist, auf die Heimatwiesen zurückzukehren, denn bald werden die Bergwiesen unter einer dicken Schneedecke begraben sein. Nach etwa vier bis fünf Stunden im Sattel erreichen wir wieder unsere Farm, auf der wir von einer duftenden Kaffeetafel erwartet werden. Abendessen und Übernachtung auf Grýtubakki.",
      } },
      { n: 7, kind: "departure", places: ["akureyri"], body: {
        is: "Eftir morgunmat ökum við gestum aftur til Akureyrar.",
        en: "After breakfast, we drive our guests back to Akureyri.",
        de: "Nach einem letzten gemeinsamen Frühstück bringen wir unsere Gäste zurück nach Akureyri und verabschieden uns.",
      } },
    ],
  },
}
