/* Innihaldslýsingar og næringargildi í 100 g, eins og þau standa á isfugl.is/kjuklingur/innihaldslysingar
   og isfugl.is/kalkunn/innihaldslysingar (uppfært 2021). null = ekki gefið upp á vefnum. */
export type Vara = { n: string; fugl: 'kjuklingur' | 'kalkunn'; inn: string; kkal: number | null; kj: number | null; prot: number | null; fita: number | null; salt: number | null; kind: 'hreint' | 'kryddad' | 'fulleldad' | 'unnid'; mynd: string | null }
export const VORUR: Vara[] = [
 {
  "n": "Heill kjúklingur",
  "fugl": "kjuklingur",
  "inn": "Kjúklingur",
  "kkal": 184,
  "kj": 768,
  "prot": 18,
  "fita": 12,
  "salt": 0.2,
  "kind": "hreint",
  "mynd": "heill-kjuklingur"
 },
 {
  "n": "Kjúklingabringur 100%",
  "fugl": "kjuklingur",
  "inn": "Kjúklingabringur án skinns",
  "kkal": 105,
  "kj": 447,
  "prot": 23,
  "fita": 1.2,
  "salt": 0.1,
  "kind": "hreint",
  "mynd": "kjuklingabringur"
 },
 {
  "n": "Kjúklingalæri",
  "fugl": "kjuklingur",
  "inn": "Kjúklingalæri",
  "kkal": 156,
  "kj": 654,
  "prot": 19,
  "fita": 8.9,
  "salt": 0.2,
  "kind": "hreint",
  "mynd": "kjuklingalaeri"
 },
 {
  "n": "Kjúklingaleggir",
  "fugl": "kjuklingur",
  "inn": "Kjúklingaleggir",
  "kkal": 155,
  "kj": 650,
  "prot": 19,
  "fita": 8.7,
  "salt": 0.2,
  "kind": "hreint",
  "mynd": "kjuklingaleggir"
 },
 {
  "n": "Kjúklingavængir",
  "fugl": "kjuklingur",
  "inn": "Kjúklingavængir",
  "kkal": 183,
  "kj": 778,
  "prot": 19,
  "fita": 12,
  "salt": 0.2,
  "kind": "hreint",
  "mynd": "kjuklingavaengir"
 },
 {
  "n": "Kjúklingabringur, skinnlausar",
  "fugl": "kjuklingur",
  "inn": "Kjúklingabringur (91%), vatn, salt, glúkósasíróp, sýrustillir(E500), rotvarnarefni (E262),  bragðefni.",
  "kkal": 98,
  "kj": 409,
  "prot": 22,
  "fita": 1,
  "salt": 0.4,
  "kind": "unnid",
  "mynd": "kjuklingabringur"
 },
 {
  "n": "Kjúklingalundir",
  "fugl": "kjuklingur",
  "inn": "Kjúklingabringur (91%), vatn, salt, glúkósasíróp, sýrustillir(E500), rotvarnarefni (E262),  bragðefni.",
  "kkal": 98,
  "kj": 409,
  "prot": 22,
  "fita": 1,
  "salt": 0.4,
  "kind": "unnid",
  "mynd": "kjuklingalundir"
 },
 {
  "n": "Kjúklingabringur með vængbeini",
  "fugl": "kjuklingur",
  "inn": "Kjúklingur (92%), vatn, salt, glúkósasíróp, sýrustillir (E500), rotvarnarefni (E262), bragðefni.",
  "kkal": 137,
  "kj": 573,
  "prot": 20,
  "fita": 6.3,
  "salt": 0.5,
  "kind": "unnid",
  "mynd": "kjuklingabringur-skinn"
 },
 {
  "n": "Kjúklingabringur með skinni",
  "fugl": "kjuklingur",
  "inn": "Kjúklingur (91%), vatn, salt, glúkósasíróp, sýrustillir (E500), rotvarnarefni (E262), bragðefni.",
  "kkal": 136,
  "kj": 568,
  "prot": 20,
  "fita": 6.3,
  "salt": 0.6,
  "kind": "unnid",
  "mynd": "kjuklingabringur-skinn"
 },
 {
  "n": "Kjúklingalæri, úrbeinuð, skinnlaus",
  "fugl": "kjuklingur",
  "inn": "Kjúklingur (91%), vatn, salt, glúkósasíróp, sýrustillir (E50), rotvarnarefni (E262), bragðefni.",
  "kkal": 142,
  "kj": 595,
  "prot": 17,
  "fita": 8.1,
  "salt": 0.6,
  "kind": "unnid",
  "mynd": "kjuklingalaeri-urbeinud"
 },
 {
  "n": "Kjúklingaleggir, Mexico",
  "fugl": "kjuklingur",
  "inn": "Kjúklingur (kjúklingaleggir (86%), vatn, salt, glúkósasíróp, sýrustillir (E500), rotvarnarefni (E262) bragðefni, krydd), sósa (vatn, sólblómaolía, dextrósi, krydd (sinnep) , hvítlauksduft, paprika, vínedik, salt, sterkja, bragðefni, litarefni (E160c), rotvarnarefni (E202, E211)).",
  "kkal": 147,
  "kj": 616,
  "prot": 17,
  "fita": 8.4,
  "salt": 0.7,
  "kind": "kryddad",
  "mynd": "leggir-mexico"
 },
 {
  "n": "Kjúklingaleggir, BBQ",
  "fugl": "kjuklingur",
  "inn": "Kjúklingur (kjúklingaleggir (84%), vatn, salt, glúkósasíróp, sýrustillir (E500), rotvarnarefni (E262), bragðefni, krydd), BBQ sósa (vatn, tómatpaste, laukduft, hvítlauksduft, sykur, mólassi, edik, salt, krydd og kryddjurtir (sinnep) , sterkja, reykbragðefni)",
  "kkal": 147,
  "kj": 617,
  "prot": 16,
  "fita": 7.4,
  "salt": 0.7,
  "kind": "kryddad",
  "mynd": "leggir-bbq"
 },
 {
  "n": "Kjúklingur, kryddaður í ofn",
  "fugl": "kjuklingur",
  "inn": "Kjúklingur, salt, krydd, sykur.",
  "kkal": 183,
  "kj": 768,
  "prot": 18,
  "fita": 12,
  "salt": 1.3,
  "kind": "kryddad",
  "mynd": "kryddadur-kjuklingur"
 },
 {
  "n": "Vængir, fulleldaðir, Tex Mex kryddaðir",
  "fugl": "kjuklingur",
  "inn": "Kjúklingur (kjúklingavængir (86%), vatn, salt, glúkósasíróp, sýrustillir (E500), rotvarnarefni (E262), bragðefni, krydd, sósa (vatn, sólblómaolía, dextrósi, krydd (sinnep) , hvítlauksduft, paprika, vínedik, salt, sterkja, bragðefni, litarefni (E160c), rotvarnarefni (E202, E211)).",
  "kkal": 228,
  "kj": 956,
  "prot": 22,
  "fita": 15,
  "salt": 0.9,
  "kind": "fulleldad",
  "mynd": "vaengir-tex-mex"
 },
 {
  "n": "Leggir, fulleldaðir, Mexicokryddaðir",
  "fugl": "kjuklingur",
  "inn": "Kjúklingaleggir (86%), vatn, salt, glúkósasíróp, sýrustillir (E500), rotvarnarefni (E262) bragðefni, krydd, sósa (vatn, sólblómaolía, dextrósi, krydd (sinnep) , hvítlauksduft, paprika, vínedik, salt, sterkja, bragðefni, litarefni (E160c), rotvarnarefni (E202, E211)).",
  "kkal": 195,
  "kj": 815,
  "prot": 22,
  "fita": 11,
  "salt": 0.8,
  "kind": "fulleldad",
  "mynd": "leggir-mexico"
 },
 {
  "n": "Kalkúnabringur",
  "fugl": "kalkunn",
  "inn": "Kalkúnabringa (91%), vatn, salt, glúkósasíróp, sýrustillir (E500), rotvarnarefni (E262), bragðefni.",
  "kkal": 115,
  "kj": 483,
  "prot": 18,
  "fita": 5.6,
  "salt": 0.6,
  "kind": "unnid",
  "mynd": "kalkunabringur"
 },
 {
  "n": "Kalkúnalæri, úrbeinuð, fersk",
  "fugl": "kalkunn",
  "inn": "Kalkúnalæri",
  "kkal": 104,
  "kj": 439,
  "prot": 20,
  "fita": 2.5,
  "salt": 0.2,
  "kind": "hreint",
  "mynd": "kalkunalaeri-urbeinud"
 },
 {
  "n": "Kalkúnastrimlar",
  "fugl": "kalkunn",
  "inn": "Kalkúnalæri",
  "kkal": 104,
  "kj": 439,
  "prot": 20,
  "fita": 2.5,
  "salt": 0.2,
  "kind": "hreint",
  "mynd": "kalkunastrimlar"
 },
 {
  "n": "Kalkúnagrillsneiðar",
  "fugl": "kalkunn",
  "inn": "Íslenskt kalkúnakjöt 89%, vatn, salt, glúkósasíróp, sýrustillir (E500), rotvarnarefni (E262), bragðefni, krydd, jurtaprótein.",
  "kkal": 102,
  "kj": 427,
  "prot": 18,
  "fita": 2,
  "salt": 1.6,
  "kind": "kryddad",
  "mynd": "kalkunagrillsneidar"
 },
 {
  "n": "Kalkúnahakk 100%",
  "fugl": "kalkunn",
  "inn": "Kalkúnakjöt",
  "kkal": 111,
  "kj": 468,
  "prot": 21,
  "fita": 3,
  "salt": 0.2,
  "kind": "hreint",
  "mynd": "kalkunahakk"
 },
 {
  "n": "Kalkúnalundir",
  "fugl": "kalkunn",
  "inn": "Kalkúnalundir (91%), vatn glúkósasíróp, sýrustillir (E500), rotvarnarefni (E262), bragðefni",
  "kkal": 101,
  "kj": 428,
  "prot": 23,
  "fita": 1,
  "salt": 0.2,
  "kind": "unnid",
  "mynd": "kalkunalundir"
 },
 {
  "n": "Kalkúnapepperóní",
  "fugl": "kalkunn",
  "inn": "kalkúnakjöt",
  "kkal": null,
  "kj": null,
  "prot": null,
  "fita": null,
  "salt": null,
  "kind": "hreint",
  "mynd": "kalkunapepperoni"
 },
 {
  "n": "Kalkúnabringa með ostafyllingu",
  "fugl": "kalkunn",
  "inn": "Kalkúnabringa (80%), vatn, rjómaostur (mjólk), sveppir, beikon, epli, hveiti, repjuolía,salt, ger, sykur, glúkósasíróp, laukur, sellerí, heslihnetur, smjör, krydd, birkifræ, sesamfræ, rotvarnarefni (E262), þráavarnarefni (E331), lyftiefni (E500), bragðefni.",
  "kkal": 111,
  "kj": 468,
  "prot": 20,
  "fita": 3,
  "salt": 0.3,
  "kind": "kryddad",
  "mynd": "kalkunabringa-ostafylling"
 },
 {
  "n": "Kalkúnabringa með amerískri fyllingu",
  "fugl": "kalkunn",
  "inn": "Kalkúnn (84%), hert jurtafita, vatn, salt, glúkósasíróp, sykur, kryddjurtir, laukur, bragðefni,rotvarnarefni (E262), þráarvarnarefni (E331), lyftiefni (E500).",
  "kkal": 160,
  "kj": 670,
  "prot": 20,
  "fita": 8,
  "salt": 1.5,
  "kind": "kryddad",
  "mynd": "kalkunabringa-fylling"
 },
 {
  "n": "Kalkúnaskip, smjörsprautað",
  "fugl": "kalkunn",
  "inn": "Kalkúnn (kalkúnakjöt (85%), vatn, salt, glúkósasíróp, sýrustillir (E500), rotvarnarefni (E262), bragðefni), smjörsósa (raps- og pálmaolía, smjör , salt, sykur, kryddjurtir, laukur, bragðefni).",
  "kkal": 149,
  "kj": 623,
  "prot": 17,
  "fita": 8.6,
  "salt": 1.3,
  "kind": "kryddad",
  "mynd": "kalkunaskip"
 },
 {
  "n": "French Garden Marineruð Kalkúnalæri",
  "fugl": "kalkunn",
  "inn": "Íslenskt kalkúnakjöt 91%, vatn, salt, glúkósasíróp, sýrustillir (E500), rotvarnarefni (E262), bragðefni, hert repjuolía, kryddbragðefni, vatnsrofin repjuprótein.",
  "kkal": 108,
  "kj": 454,
  "prot": 18,
  "fita": 4,
  "salt": 0.6,
  "kind": "kryddad",
  "mynd": "kalkunalaeri-urbeinud"
 }
]
