/* Every word a guest reads, in Icelandic and English. Titles use "|" for a line
   break and *…* for italic words. Facts: _docs/BJARKALUNDUR-FACTS-2026-09-26.md;
   drive times measured 2026-09-26 with two open routers (OSRM, Valhalla), see
   _docs/BJARKALUNDUR-SEO-GEO-AEO-2026-09-26.md. The FAQ answers the questions
   people type about Bjarkalundur (Google Suggest harvest, same doc): opening
   hours, restaurant, campsite, distance, fishing, the road. Icelandic went through
   the Codex copy pass; English is written as English, not translated word for word. */
import type { Lang } from './paths'
import { PHONE_DISPLAY, PHONE_INTL } from './data'
import type { ImgKey } from './data'
import type { PageKey, SectionKey } from './paths'

const is = {
  meta: {
    home: {
      title: 'Hótel Bjarkalundur | Hótel og gisting á Vestfjörðum',
      description: 'Elsta sumarhótel landsins, við Vestfjarðaveg undir Vaðalfjöllum. Herbergi, sumarhús, veitingastaður og tjaldsvæði, 214 km frá Reykjavík.',
    },
    rooms: {
      title: 'Herbergi og sumarhús | Hótel Bjarkalundur',
      description: 'Átta tegundir gistingar í Bjarkalundi: herbergi með og án sérbaðs í aðalhúsinu og sumarhús á lóðinni, sum með eldhúskrók. Bókaðu beint hjá hótelinu.',
    },
    reviews: {
      title: 'Umsagnir gesta | Hótel Bjarkalundur',
      description: 'Það sem gestir hafa skrifað um Hótel Bjarkalund síðan það opnaði á ný í apríl 2026, orðrétt og undir nafni.',
    },
    campsite: {
      title: 'Tjaldsvæðið í Bjarkalundi | Tjaldað á Vestfjörðum',
      description: 'Tjaldsvæði á grasflöt við lækinn við Hótel Bjarkalund: þjónustuhús með salernum og sturtum, rafmagn og leiksvæði. 1.500 kr. á mann, frítt fyrir börn 12 ára og yngri.',
    },
  },
  nav: [
    { label: 'Gisting', page: 'rooms' },
    { label: 'Veitingar', section: 'food' },
    { label: 'Umhverfið', section: 'surroundings' },
    { label: 'Tjaldsvæðið', page: 'campsite' },
    { label: 'Sagan', section: 'history' },
    { label: 'Umsagnir', page: 'reviews' },
    { label: 'Spurt og svarað', section: 'faq' },
    { label: 'Hafa samband', section: 'contact' },
  ] as { label: string; page?: PageKey; section?: SectionKey }[],
  ui: {
    home: 'Forsíða',
    menu: 'Valmynd',
    close: 'Loka',
    skip: 'Fara beint í efnið',
    quick: 'Flýtileiðir',
    call: 'Hringja',
    book: 'Bóka',
    bookStay: 'Bóka gistingu',
    back: 'Til baka',
    backAria: 'Til baka á fyrri stað',
    langLabel: 'Tungumál',
    langAria: { is: 'Íslenska', en: 'English' },
    phone: 'Sími',
    pages: 'Síður',
    hotel: 'Hótelið',
    contact: 'Hafa samband',
    bookingPage: 'Bókunarsíða hótelsins',
    since: 'Hótel · síðan 1947',
    markAria: 'Hótel Bjarkalundur, forsíða',
    driftPause: 'Stöðva hreyfinguna',
    driftPlay: 'Halda hreyfingunni áfram',
    mapTitle: 'Kort: Hótel Bjarkalundur við Vestfjarðaveg',
    mapLink: 'Opna í Google Maps',
    directions: 'Leiðarlýsing',
    email: 'Tölvupóstur',
    photoComing: 'Mynd væntanleg',
    noPhoto: (name: string, size: number) => `${name}, ${size} fermetrar. Engin mynd enn.`,
    pictures: (name: string) => `Myndir: ${name}`,
    picture: (i: number, n: number) => `Mynd ${i} af ${n}`,
    filterAria: 'Sía herbergi',
    showing: (label: string) => `Sýni ${label}`,
    copyright: '© Hótel Bjarkalundur',
    starsLabel: (n: number) => `${n} af 5 stjörnum`,
  },
  hero: {
    name: 'Bjarkalundur',
    h1: 'Hótel Bjarkalundur',
    sub: 'Elsta sumarhótel landsins, við rætur Vaðalfjalla á Vestfjörðum.',
    rooms: 'Öll herbergin',
  },
  intro: {
    eyebrow: 'Síðan 1947',
    title: 'Sumarhótel|*við veginn vestur*',
    body: [
      'Hótel Bjarkalundur var reist á árunum 1945 til 1947 og er elsta sumarhótel landsins. Það stendur við Vestfjarðaveg, 214 kílómetra frá Reykjavík, beint neðan við Vaðalfjöll.',
      'Hér eru herbergi og sumarhús, matsalur með grænum veggjum og tjaldsvæði við lækinn.',
    ],
    link: 'Saga hússins',
  },
  experience: {
    title: 'Vaðalfjöll|*og vatnið*',
    sub: 'Tveir gígtappar úr blágrýti beint norðan við hótelið og Berufjarðarvatn í sjö mínútna göngufæri. Það er auðvelt að ganga að Vaðalfjöllum og upp á tindana.',
    card: { title: 'Kajak á vatninu', text: 'Á Berufjarðarvatni er róið á kajak og rennt fyrir fisk.' },
    road: 'Bjarkalundur er þar sem Vestfjarðavegur kemur inn á Vestfirði: góður staður fyrir fyrstu eða síðustu nóttina á ferð um firðina.',
  },
  stay: {
    eyebrow: 'Gisting',
    title: 'Herbergi|*og sumarhús*',
    features: ['19 herbergi', 'Sumarhús', 'Sérbað í boði', 'Þráðlaust net'],
    strip: ['Lómur', 'Sumarhús', 'Fyrir einn', 'Eldhúskrókur'],
    cta: 'Öll herbergin',
  },
  cottages: {
    title: 'Sumarhúsin|*á lóðinni*',
    body: 'Viðarklædd hús með palli, sum með eldhúskrók og eigin baðherbergi. Ný sumarhús eru í smíðum og bætast við.',
    link: 'Skoða gistingu',
  },
  owners: {
    eyebrow: 'Nýir eigendur',
    title: 'Diddi og Evelyn|*opnuðu á ný*',
    body: [
      'Bjarkalundur stóð lokaður í þrjú ár. Árið 2025 tóku hjónin Sigurður Friðriksson, Diddi, og Evelyn Rojas Tagalog við staðnum og 1. apríl 2026 var hótelið opnað aftur.',
      'Diddi var lengst af skipstjóri og hefur rekið hótel frá árinu 2004. Nú er opið frá klukkan sjö á morgnana, morgunmatur í boði og eldhúsið opið fram á kvöld, alla daga.',
      'Ný sumarhús eru í smíðum á lóðinni. Hótelið er lokað hluta vetrar og opnar aftur í mars.',
    ],
    link: 'Saga hússins',
    archivalCaption: 'Bjarkalundur á árum áður.',
  },
  food: {
    eyebrow: 'Veitingar',
    title: 'Matur|*með útsýni*',
    cards: [
      { h: 'Morgunmatur', t: 'Frá klukkan sjö á morgnana, alla daga.' },
      { h: 'Græna stofan', t: 'Píanó, hægindastólar og blómaveggfóður.' },
      { h: 'Hádegi og kvöld', t: 'Eldhúsið er opið fram á kvöld, alla daga.' },
    ],
    guests: 'Allir eru velkomnir í mat, líka þeir sem gista ekki.',
  },
  reviewsTeaser: {
    title: 'Það sem gestir|*segja*',
    sub: 'Frá því hótelið opnaði á ný í apríl 2026.',
    cta: 'Allar umsagnir',
  },
  history: {
    title: 'Saga|*hússins*',
    years: [
      { y: '1947', h: 'Hótelið rís', pic: 'archival', t: 'Hótelið var reist á árunum 1945 til 1947 undir Vaðalfjöllum. Jörðin Bjarkalundur er um 55 hektarar og Berufjarðarvatn allt er innan hennar. Í dag er þetta elsta sumarhótel landsins.' },
      { y: '2008', h: 'Dagvaktin', pic: 'facade', t: 'Haustið 2008 voru gamanþættirnir Dagvaktin teknir upp í Bjarkalundi, með Jóni Gnarr, Jörundi Ragnarssyni, Pétri Jóhanni Sigfússyni og Ólafíu Hrönn Jónsdóttur í aðalhlutverkum. Eftir þættina þekkti öll þjóðin hótelið.' },
      { y: '2021', h: 'Brúarsmiðir', pic: 'window', t: 'Á meðan Þorskafjörður var brúaður gistu brúarsmiðir Suðurverks í Bjarkalundi, sem þá var rekinn sem vinnubúðir. Nýi vegurinn liggur nú yfir fjörðinn norðan við hótelið.' },
      { y: '2023', h: 'Lokað', pic: 'peaks', t: 'Hótelið lokaði og stóð lokað í þrjú ár á meðan staðurinn var á söluskrá.' },
      { y: '2025', h: 'Nýir eigendur', pic: 'sign', t: 'Í september 2025 tóku Diddi og Evelyn við staðnum. Diddi var lengst af skipstjóri og hefur rekið hótel frá árinu 2004. Veturinn fór í að undirbúa opnunina.' },
      { y: '2026', h: 'Opnað á ný', pic: 'lounge', t: 'Hótelið var opnað aftur 1. apríl 2026 eftir þriggja ára lokun. Nú er opið frá klukkan sjö alla daga og ný sumarhús eru í smíðum á lóðinni.' },
    ] as { y: string; h: string; pic: ImgKey; t: string }[],
  },
  faq: {
    eyebrow: 'Gott að vita',
    title: 'Spurt|*og svarað*',
    items: [
      { id: 'fjarlaegd', q: 'Hvað er langt til Bjarkalundar?', a: 'Frá Reykjavík eru 214 kílómetrar, um þriggja tíma akstur um Borgarnes og Búðardal. Frá hótelinu eru 15 km til Reykhóla, 45 km til Hólmavíkur og 62 km til Búðardals. Til Brjánslækjar, þar sem ferjan Baldur leggst að, eru um 117 km.' },
      { id: 'opid', q: 'Er hótelið opið allt árið?', a: 'Nei. Hótelið er lokað hluta vetrar og opnar aftur í mars. Á meðan opið er tekur veitingastaðurinn á móti gestum frá klukkan sjö á morgnana og fram á kvöld, alla daga.' },
      { id: 'innritun', q: 'Hvenær er innritun og útritun?', a: 'Innritun er frá klukkan 15 og útritun til klukkan 11.' },
      { id: 'matur', q: 'Er hægt að fá morgunmat og kvöldmat?', a: 'Já. Morgunmatur er ekki innifalinn í verði gistingar en fæst í matsalnum frá klukkan sjö. Boðið er upp á hádegismat og kvöldmat alla daga og eldhúsið er opið fram á kvöld. Gestir sem gista ekki eru líka velkomnir í mat.' },
      { id: 'serbad', q: 'Eru herbergin með sérbaðherbergi?', a: 'Sum. Herbergin með sérbaði í aðalhúsinu og tvö af sumarhúsunum hafa eigið baðherbergi. Gestir í herbergjum með vaski nota salerni og sturtur frammi á gangi og gestir í minni sumarhúsunum nota salerni og sturtur inni í hótelinu.' },
      { id: 'eldhus', q: 'Er hægt að elda í sumarhúsunum?', a: 'Í tveimur sumarhúsum er eldhúskrókur með litlum ísskáp og aðstöðu til að laga te og kaffi: sumarhúsinu með eldhúskrók og baði og stóra sumarhúsinu. Önnur hús eru án eldhúss en veitingastaðurinn er opinn alla daga.' },
      { id: 'rafbilar', q: 'Er hleðslustöð fyrir rafbíla?', a: 'Já. Við hótelið er bensínstöð og hleðslustöð fyrir rafbíla. Bílastæði og þráðlaust net fylgja gistingunni.' },
      { id: 'tjald', q: 'Hvað kostar á tjaldsvæðinu?', a: 'Gisting á tjaldsvæðinu kostar 1.500 kr. á mann og rafmagn 1.000 kr. nóttin. Sturtan kostar 100 kr. mínútan og börn 12 ára og yngri tjalda frítt. Á svæðinu er þjónustuhús með salernum og sturtum og leiksvæði fyrir börn.' },
      { id: 'veidi', q: 'Má veiða í Berufjarðarvatni?', a: 'Já. Í vatninu er mest af urriða en líka talsvert af bleikju. Berufjarðarvatn er á Veiðikortinu og handhafar kortsins skrá sig á hótelinu áður en þeir veiða. Veitt er frá 15. maí til 15. september, klukkan 7 til 23, og á vatninu er líka róið á kajak.' },
      { id: 'ganga', q: 'Er hægt að ganga á Vaðalfjöll?', a: 'Já. Vaðalfjöll eru tveir gígtappar úr blágrýti, 508 metra háir, beint norðan við hótelið. Auðvelt er að ganga að fjöllunum og upp á tindana og gönguleiðin er í Wapp, göngu­appinu.' },
      { id: 'nagrenni', q: 'Hvað er hægt að gera í nágrenninu?', a: 'Á Reykhólum, 15 mínútna akstur frá hótelinu, er sundlaugin Grettislaug með heitum pottum. Við hótelið er róið á kajak, veitt í vatninu og gengið á Vaðalfjöll. Til Dynjanda eru um tveir tímar og til Ísafjarðar um þrír.' },
      { id: 'faerd', q: 'Hvernig er færðin á leiðinni?', a: 'Hótelið stendur við Vestfjarðaveg (60). Nýjustu upplýsingar um færð og veður eru á umferdin.is og vedur.is og það borgar sig að skoða þær áður en lagt er af stað utan sumartímans.' },
      { id: 'boka', q: 'Hvernig bóka ég?', a: `Þú bókar beint hjá hótelinu á bókunarsíðunni. Þar sérðu verð og laus herbergi þá daga sem þú vilt gista. Einnig má hringja í síma ${PHONE_DISPLAY} eða senda tölvupóst.` },
    ],
    roadsLink: 'Færð á umferdin.is',
    weatherLink: 'Veðrið á vedur.is',
    fishingLink: 'Berufjarðarvatn á Veiðikortinu',
  },
  contact: {
    title: 'Hafa|*samband*',
    rows: [
      { k: 'Heimilisfang', v: 'Bjarkalundi, 381 Reykhólahreppur' },
      { k: 'Vegur', v: 'Vestfjarðavegur (60)' },
      { k: 'Innritun', v: 'Frá klukkan 15' },
      { k: 'Útritun', v: 'Til klukkan 11' },
    ],
  },
  closing: {
    title: 'Gistu við rætur|*Vaðalfjalla*',
    call: 'Hringja',
  },
  booking: {
    eyebrow: 'Bóka',
    title: 'Veldu|*dagsetningar*',
    lede: 'Veldu komu- og brottfarardag og fjölda gesta. Bókunin klárast á bókunarsíðu hótelsins, þar sem verð og laus herbergi sjást.',
    adults: 'Fullorðnir',
    children: 'Börn',
    fewer: (label: string) => `Færri: ${label}`,
    more: (label: string) => `Fleiri: ${label}`,
    night: 'nótt',
    nights: 'nætur',
    checkIn: 'Koma',
    checkOut: 'Brottför',
    pickDate: 'Veldu dag',
    afterCheckIn: 'Eftir komudag',
    clearDates: 'Hreinsa dagsetningar',
    chooseCheckout: 'Veldu brottfarardag',
    go: 'Sjá laus herbergi',
    goNoDates: 'Opna bókunarsíðuna',
    pricesNext: 'Í næsta skrefi sérðu verð og hvaða herbergi eru laus dagana sem þú valdir.',
    season: 'Hótelið er lokað hluta vetrar og opnar aftur í mars.',
    prevMonth: 'Fyrri mánuður',
    nextMonth: 'Næsti mánuður',
    months: ['janúar', 'febrúar', 'mars', 'apríl', 'maí', 'júní', 'júlí', 'ágúst', 'september', 'október', 'nóvember', 'desember'],
    weekdaysShort: ['mán', 'þri', 'mið', 'fim', 'fös', 'lau', 'sun'],
    weekdayInitials: ['M', 'Þ', 'M', 'F', 'F', 'L', 'S'],
    roomFor: (name: string) => `Bóka: ${name}`,
  },
  rooms: {
    thaegindi: { name: 'Herbergi með sérbaði', guests: '3 að hámarki', beds: 'Tvö einbreið rúm og sófi í sumum herbergjum', bath: 'Sérbaðherbergi', text: 'Stærstu herbergin í aðalhúsinu, hvert með sínu baðherbergi.' },
    vaskur: { name: 'Herbergi með vaski', guests: '2', beds: 'Tvö einbreið rúm', bath: 'Salerni og sturtur á ganginum', text: 'Vaskur inni á herberginu, salerni og sturtur frammi á gangi. Herbergin bera fuglanöfn, eins og Lómur og Himbrimi.' },
    einn: { name: 'Eins manns herbergi', guests: '1', beds: 'Eitt einbreitt rúm', bath: 'Sameiginlegt baðherbergi', text: 'Lítið og hagkvæmt herbergi fyrir þann sem ferðast einn.' },
    'hus-eldhus': { name: 'Sumarhús með eldhúskrók og baði', guests: '2', beds: 'Tvö einbreið rúm', bath: 'Sérbaðherbergi með sturtu', text: 'Eldhúskrókur með litlum ísskáp, aðstaða til að laga te og kaffi og pallur fyrir framan.' },
    'hus-bad': { name: 'Sumarhús með baði', guests: '3 að hámarki', beds: 'Tvö einbreið rúm', bath: 'Sérbaðherbergi með sturtu', text: 'Viðarklætt sumarhús með eigin baðherbergi og palli.' },
    'hus-stort': { name: 'Stórt sumarhús með eldhúskrók', guests: '4 fullorðnir og 1 barn að hámarki', beds: 'Rúm fyrir fjóra', bath: 'Eigið salerni, sturtur í hótelinu', text: 'Stærsta sumarhúsið, með eldhúskrók, aðstöðu til að laga te og kaffi og eigin palli.' },
    'hus-litid': { name: 'Lítið sumarhús', guests: '2', beds: 'Rúm fyrir tvo', bath: 'Salerni og sturtur í hótelinu', text: 'Einfalt hús fyrir tvo. Salerni og sturtur eru inni í hótelinu.' },
    'hus-tveggja': { name: 'Tveggja manna smáhýsi', guests: '2', beds: 'Tvö einbreið rúm', bath: 'Salerni og sturtur í hótelinu', text: 'Minnsta húsið á lóðinni, með tveimur einbreiðum rúmum.' },
  } as Record<string, { name: string; guests: string; beds: string; bath: string; text: string }>,
  noPower: 'Án rafmagns í bili.',
  roomsPage: {
    title: 'Gisting|*í Bjarkalundi*',
    sub: 'Herbergi í aðalhúsinu og sumarhús á lóðinni. Þú bókar beint hjá hótelinu.',
    filters: [
      { id: 'allt', label: 'Allt' },
      { id: 'hotel', label: 'Í hótelinu' },
      { id: 'sumarhus', label: 'Sumarhús' },
      { id: 'bad', label: 'Með sérbaði' },
      { id: 'eldhus', label: 'Með eldhúskrók' },
    ],
    groups: { hotel: 'Í hótelinu', sumarhus: 'Sumarhúsin' },
    count: (n: number) => (n === 1 ? '1 tegund' : `${n} tegundir`),
    labels: { size: 'Stærð', guests: 'Gestir', beds: 'Rúm', bath: 'Bað' },
    book: 'Bóka',
    included: 'Þráðlaust net og bílastæði fylgja öllum herbergjum. Morgunmatur fæst í matsalnum gegn gjaldi.',
    newCottages: 'Ný sumarhús eru í smíðum á lóðinni og bætast við síðar.',
    prices: 'Verð og laus herbergi sjást á bókunarsíðunni.',
    empty: 'Ekkert herbergi uppfyllir þessi skilyrði.',
    reset: 'Sýna allt',
  },
  reviewsPage: {
    title: 'Umsagnir|*gesta*',
    sub: 'Það sem gestir hafa skrifað síðan Bjarkalundur opnaði á ný í apríl 2026. Hver umsögn birtist orðrétt, undir nafni þess sem skrifaði.',
    translate: 'Á íslensku',
    original: 'Frumtexti',
    more: 'Fleiri umsagnir',
    google: 'Á Google',
    tripadvisor: 'Á Tripadvisor',
    photoNote: 'Myndirnar eru frá hótelinu og sýna það sem umsögnin fjallar um.',
  },
  campsite: {
    eyebrow: 'Tjaldsvæði',
    title: 'Tjaldsvæðið|*við lækinn*',
    sub: 'Grasflöt við lækinn rétt við hótelið, nokkur skref frá veitingastaðnum.',
    introTitle: 'Tjaldað|*undir Vaðalfjöllum*',
    body: [
      'Tjaldsvæðið í Bjarkalundi er á grasflöt við lækinn, rétt við hótelið. Þar er þjónustuhús með salernum og sturtum, rafmagn og leiksvæði fyrir börn.',
      'Frá tjaldinu er stutt í matsalinn, gönguleiðina á Vaðalfjöll og veiðina í Berufjarðarvatni. Við hótelið er líka bensínstöð og hleðslustöð fyrir rafbíla.',
    ],
    pricesTitle: 'Verð',
    prices: [
      { k: 'Á mann, nóttin', v: '1.500 kr.' },
      { k: 'Rafmagn, nóttin', v: '1.000 kr.' },
      { k: 'Sturta, mínútan', v: '100 kr.' },
      { k: 'Börn 12 ára og yngri', v: 'Frítt' },
    ],
    facilitiesTitle: 'Á svæðinu',
    facilities: ['Þjónustuhús með salernum og sturtum', 'Rafmagn', 'Leiksvæði fyrir börn', 'Veitingastaður í hótelinu', 'Bensínstöð og hleðsla fyrir rafbíla', 'Veiði í Berufjarðarvatni'],
    questions: 'Spurningar um tjaldsvæðið?',
    season: 'Hótelið og tjaldsvæðið eru lokuð hluta vetrar.',
  },
  footer: {
    tagline: 'Elsta sumarhótel landsins, við rætur Vaðalfjalla.',
    season: 'Lokað hluta vetrar. Opnar aftur í mars.',
  },
}

export type Copy = typeof is

const en: Copy = {
  meta: {
    home: {
      title: 'Hotel Bjarkalundur | Hotel in the Westfjords, Iceland',
      description: "Iceland's oldest summer hotel, on Route 60 below the Vaðalfjöll peaks. Rooms, cottages, a restaurant and a campsite, 214 km from Reykjavík.",
    },
    rooms: {
      title: 'Rooms and cottages | Hotel Bjarkalundur',
      description: 'Eight kinds of accommodation at Bjarkalundur: rooms with and without a private bathroom in the main house and cottages on the grounds, some with a kitchenette.',
    },
    reviews: {
      title: 'Guest reviews | Hotel Bjarkalundur',
      description: 'What guests have written about Hotel Bjarkalundur since it reopened in April 2026, quoted word for word under their own names.',
    },
    campsite: {
      title: 'Bjarkalundur campsite | Camping in the Westfjords',
      description: 'A grass campsite by the stream at Hotel Bjarkalundur, with toilets, showers, electricity and a playground. ISK 1,500 per person, children 12 and under free.',
    },
  },
  nav: [
    { label: 'Rooms', page: 'rooms' },
    { label: 'Restaurant', section: 'food' },
    { label: 'Surroundings', section: 'surroundings' },
    { label: 'Campsite', page: 'campsite' },
    { label: 'History', section: 'history' },
    { label: 'Reviews', page: 'reviews' },
    { label: 'Good to know', section: 'faq' },
    { label: 'Contact', section: 'contact' },
  ],
  ui: {
    home: 'Home',
    menu: 'Menu',
    close: 'Close',
    skip: 'Skip to content',
    quick: 'Quick links',
    call: 'Call',
    book: 'Book',
    bookStay: 'Book a stay',
    back: 'Back',
    backAria: 'Back to where you were',
    langLabel: 'Language',
    langAria: { is: 'Íslenska', en: 'English' },
    phone: 'Phone',
    pages: 'Pages',
    hotel: 'The hotel',
    contact: 'Contact',
    bookingPage: "The hotel's booking page",
    since: 'Hotel · since 1947',
    markAria: 'Hotel Bjarkalundur, home',
    driftPause: 'Pause the reviews',
    driftPlay: 'Play the reviews',
    mapTitle: 'Map: Hotel Bjarkalundur on Route 60',
    mapLink: 'Open in Google Maps',
    directions: 'Directions',
    email: 'Email',
    photoComing: 'Photo coming',
    noPhoto: (name: string, size: number) => `${name}, ${size} square metres. No photo yet.`,
    pictures: (name: string) => `Photos: ${name}`,
    picture: (i: number, n: number) => `Photo ${i} of ${n}`,
    filterAria: 'Filter rooms',
    showing: (label: string) => `Showing ${label}`,
    copyright: '© Hotel Bjarkalundur',
    starsLabel: (n: number) => `${n} out of 5 stars`,
  },
  hero: {
    name: 'Bjarkalundur',
    h1: 'Hotel Bjarkalundur',
    sub: "Iceland's oldest summer hotel, at the foot of Vaðalfjöll in the Westfjords.",
    rooms: 'All rooms',
  },
  intro: {
    eyebrow: 'Since 1947',
    title: 'A summer hotel|*on the road west*',
    body: [
      'Hotel Bjarkalundur was built between 1945 and 1947 and is the oldest summer hotel in Iceland. It stands on Route 60, the Westfjords road, 214 kilometres from Reykjavík and right below the Vaðalfjöll peaks.',
      'There are rooms and cottages, a dining room with green walls and a campsite by the stream.',
    ],
    link: 'History of the house',
  },
  experience: {
    title: 'Vaðalfjöll|*and the lake*',
    sub: 'Two basalt volcanic plugs rise just north of the hotel, and Berufjarðarvatn lake is a seven-minute walk away. It is an easy walk to Vaðalfjöll and up to the peaks.',
    card: { title: 'Kayaks on the lake', text: 'On Berufjarðarvatn you can paddle a kayak or cast a line.' },
    road: 'Bjarkalundur is where Route 60 enters the Westfjords: a good place for the first or the last night of a trip around the fjords.',
  },
  stay: {
    eyebrow: 'Stay',
    title: 'Rooms|*and cottages*',
    features: ['19 rooms', 'Cottages', 'Private bathrooms available', 'Wi-Fi'],
    strip: ['Lómur', 'Cottage', 'Single room', 'Kitchenette'],
    cta: 'All rooms',
  },
  cottages: {
    title: 'The cottages|*on the grounds*',
    body: 'Timber-clad cottages with a deck, some with a kitchenette and their own bathroom. New cottages are being built and will be added.',
    link: 'See the rooms',
  },
  owners: {
    eyebrow: 'New owners',
    title: 'Diddi and Evelyn|*reopened the hotel*',
    body: [
      'Bjarkalundur was closed for three years. In 2025 Sigurður Friðriksson, known as Diddi, and his wife Evelyn Rojas Tagalog took over the hotel, and it reopened on 1 April 2026.',
      'Diddi spent most of his working life as a ship’s captain and has run hotels since 2004. The hotel now opens at seven every morning for breakfast, and the kitchen stays open into the evening.',
      'New cottages are being built on the grounds. The hotel closes for part of the winter and reopens in March.',
    ],
    link: 'History of the house',
    archivalCaption: 'Bjarkalundur in earlier years.',
  },
  food: {
    eyebrow: 'Restaurant',
    title: 'Food|*with a view*',
    cards: [
      { h: 'Breakfast', t: 'From seven in the morning, every day.' },
      { h: 'The green lounge', t: 'A piano, armchairs and floral wallpaper.' },
      { h: 'Lunch and dinner', t: 'The kitchen is open into the evening, every day.' },
    ],
    guests: 'Everyone is welcome to eat here, not only hotel guests.',
  },
  reviewsTeaser: {
    title: 'What guests|*say*',
    sub: 'Since the hotel reopened in April 2026.',
    cta: 'All reviews',
  },
  history: {
    title: 'The story|*of the house*',
    years: [
      { y: '1947', h: 'The hotel is built', pic: 'archival', t: 'The hotel was built between 1945 and 1947 below Vaðalfjöll. The Bjarkalundur estate covers about 55 hectares, with the whole of Berufjarðarvatn lake inside it. Today it is the oldest summer hotel in Iceland.' },
      { y: '2008', h: 'Dagvaktin', pic: 'facade', t: 'In autumn 2008 the Icelandic comedy series Dagvaktin (The Day Shift) was filmed at Bjarkalundur, starring Jón Gnarr, Jörundur Ragnarsson, Pétur Jóhann Sigfússon and Ólafía Hrönn Jónsdóttir. After the series, the whole country knew the hotel.' },
      { y: '2021', h: 'The bridge builders', pic: 'window', t: 'While the new bridge over Þorskafjörður was being built, crews working for the contractor Suðurverk lived at Bjarkalundur, which served as their work camp. The new road now crosses the fjord just north of the hotel.' },
      { y: '2023', h: 'Closed', pic: 'peaks', t: 'The hotel closed and stayed closed for three years while the property was for sale.' },
      { y: '2025', h: 'New owners', pic: 'sign', t: 'In September 2025 Diddi and Evelyn took over. Diddi spent most of his working life as a ship’s captain and has run hotels since 2004. They spent the winter preparing to reopen.' },
      { y: '2026', h: 'Open again', pic: 'lounge', t: 'The hotel reopened on 1 April 2026 after three years closed. It now opens at seven every morning, and new cottages are being built on the grounds.' },
    ],
  },
  faq: {
    eyebrow: 'Good to know',
    title: 'Questions|*and answers*',
    items: [
      { id: 'distance', q: 'How far is Bjarkalundur from Reykjavík?', a: 'It is 214 kilometres from Reykjavík, about three hours by car via Borgarnes and Búðardalur. From the hotel it is 15 km to Reykhólar, 45 km to Hólmavík and 62 km to Búðardalur. Brjánslækur, where the Baldur ferry docks, is about 117 km away.' },
      { id: 'open', q: 'Is the hotel open all year?', a: 'No. The hotel closes for part of the winter and reopens in March. While it is open, the restaurant welcomes guests from seven in the morning into the evening, every day.' },
      { id: 'checkin', q: 'When are check-in and check-out?', a: 'Check-in is from 15:00 and check-out is by 11:00.' },
      { id: 'food', q: 'Can I get breakfast and dinner?', a: 'Yes. Breakfast is served in the dining room from seven, at an extra charge, and the kitchen is open into the evening for lunch and dinner, every day. You are welcome to eat here even if you are not staying.' },
      { id: 'bathroom', q: 'Do the rooms have a private bathroom?', a: 'Some do. Some rooms in the main house and two of the cottages have private bathrooms. The rooms with a washbasin share toilets and showers in the corridor, and the smaller cottages use the toilets and showers inside the hotel.' },
      { id: 'kitchen', q: 'Can I cook in the cottages?', a: 'Two cottages have a kitchenette with a small fridge and tea and coffee facilities: the cottage with kitchenette and bathroom, and the large cottage. The others have no kitchen, but the restaurant is open every day.' },
      { id: 'ev', q: 'Can I charge an electric car?', a: 'Yes. There is a fuel station and an EV charging station at the hotel. Parking and Wi-Fi are included with every stay.' },
      { id: 'camping', q: 'How much does the campsite cost?', a: 'Camping costs ISK 1,500 per person per night and electricity ISK 1,000 per night. Showers are ISK 100 a minute and children aged 12 and under stay free. There is a toilet and shower block and a playground for children.' },
      { id: 'fishing', q: 'Can I fish in Berufjarðarvatn?', a: 'Yes. The lake has mostly brown trout and a good number of Arctic char. Berufjarðarvatn is covered by the Veiðikortið fishing card, and card holders register at the hotel before fishing. The season runs from 15 May to 15 September, 07:00 to 23:00, and you can also paddle a kayak on the lake.' },
      { id: 'hiking', q: 'Can I hike up Vaðalfjöll?', a: 'Yes. Vaðalfjöll are two basalt volcanic plugs, 508 metres high, just north of the hotel. It is an easy walk to the tops, and the route is in Wapp, the Icelandic hiking app.' },
      { id: 'nearby', q: 'What is there to do nearby?', a: 'In Reykhólar, 15 minutes by car, the Grettislaug pool has hot tubs. At the hotel you can kayak and fish on the lake or hike up Vaðalfjöll. Dynjandi waterfall is about two hours away and Ísafjörður about three.' },
      { id: 'roads', q: 'What are the roads like?', a: 'The hotel is on Route 60, the Westfjords road. Check road conditions on umferdin.is and the forecast on vedur.is before you set off, especially outside the summer months.' },
      { id: 'book', q: 'How do I book?', a: `Book directly with the hotel on its booking page, where you can see prices and available rooms for your dates. Your booking then goes straight to the hotel. You can also call ${PHONE_INTL} or send an email.` },
    ],
    roadsLink: 'Road conditions on umferdin.is',
    weatherLink: 'Weather on vedur.is',
    fishingLink: 'Berufjarðarvatn on the fishing card site',
  },
  contact: {
    title: 'Get|*in touch*',
    rows: [
      { k: 'Address', v: 'Bjarkalundi, 381 Reykhólahreppur, Iceland' },
      { k: 'Road', v: 'Route 60 (Vestfjarðavegur)' },
      { k: 'Check-in', v: 'From 15:00' },
      { k: 'Check-out', v: 'By 11:00' },
    ],
  },
  closing: {
    title: 'Stay at the foot|*of Vaðalfjöll*',
    call: 'Call',
  },
  booking: {
    eyebrow: 'Book',
    title: 'Choose|*your dates*',
    lede: 'Choose your arrival and departure dates and the number of guests. Complete your booking on the hotel’s booking page, where you can see prices and available rooms.',
    adults: 'Adults',
    children: 'Children',
    fewer: (label: string) => `One fewer: ${label}`,
    more: (label: string) => `One more: ${label}`,
    night: 'night',
    nights: 'nights',
    checkIn: 'Arrival',
    checkOut: 'Departure',
    pickDate: 'Choose a date',
    afterCheckIn: 'After arrival',
    clearDates: 'Clear dates',
    chooseCheckout: 'Choose your departure',
    go: 'See available rooms',
    goNoDates: 'Open the booking page',
    pricesNext: 'Prices and available rooms for your dates are shown in the next step.',
    season: 'The hotel closes for part of the winter and reopens in March.',
    prevMonth: 'Previous month',
    nextMonth: 'Next month',
    months: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
    weekdaysShort: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    weekdayInitials: ['M', 'T', 'W', 'T', 'F', 'S', 'S'],
    roomFor: (name: string) => `Book: ${name}`,
  },
  rooms: {
    thaegindi: { name: 'Comfort room with private bathroom', guests: '3 at most', beds: 'Two single beds. Some rooms also have a sofa.', bath: 'Private bathroom', text: 'The largest rooms in the main house, each with its own bathroom.' },
    vaskur: { name: 'Standard room with washbasin', guests: '2', beds: 'Two single beds', bath: 'Toilets and showers in the corridor', text: 'A washbasin in the room, with toilets and showers along the corridor. The rooms are named after birds, such as Lómur (red-throated diver) and Himbrimi (great northern diver).' },
    einn: { name: 'Budget single room', guests: '1', beds: 'One single bed', bath: 'Shared bathroom', text: 'A small, good-value room for someone travelling alone.' },
    'hus-eldhus': { name: 'Cottage with kitchenette and bathroom', guests: '2', beds: 'Two single beds', bath: 'Private bathroom with shower', text: 'A cottage with a kitchenette, a small fridge, tea and coffee facilities and a deck at the front.' },
    'hus-bad': { name: 'Cottage with private bathroom', guests: '3 at most', beds: 'Two single beds', bath: 'Private bathroom with shower', text: 'A timber-clad cottage with its own bathroom and a deck.' },
    'hus-stort': { name: 'Large cottage with kitchenette', guests: '4 adults and 1 child at most', beds: 'Beds for four', bath: 'Own toilet, showers in the hotel', text: 'The largest cottage, with a kitchenette, tea and coffee facilities and its own deck.' },
    'hus-litid': { name: 'Small cottage', guests: '2', beds: 'Beds for two', bath: 'Toilets and showers in the hotel', text: 'A simple cottage for two. Toilets and showers are inside the hotel.' },
    'hus-tveggja': { name: 'Small twin cottage', guests: '2', beds: 'Two single beds', bath: 'Toilets and showers in the hotel', text: 'The smallest cottage on the grounds, with two single beds.' },
  },
  noPower: 'No electricity for now.',
  roomsPage: {
    title: 'Stay|*at Bjarkalundur*',
    sub: 'Rooms in the main house and cottages on the grounds. You book directly with the hotel.',
    filters: [
      { id: 'allt', label: 'All' },
      { id: 'hotel', label: 'In the hotel' },
      { id: 'sumarhus', label: 'Cottages' },
      { id: 'bad', label: 'Private bathroom' },
      { id: 'eldhus', label: 'Kitchenette' },
    ],
    groups: { hotel: 'In the hotel', sumarhus: 'The cottages' },
    count: (n: number) => (n === 1 ? '1 type' : `${n} types`),
    labels: { size: 'Size', guests: 'Guests', beds: 'Beds', bath: 'Bathroom' },
    book: 'Book',
    included: 'Wi-Fi and parking are included with every room. Breakfast is served in the dining room at an extra charge.',
    newCottages: 'New cottages are being built on the grounds and will be added later.',
    prices: 'Prices and available rooms are shown on the booking page.',
    empty: 'No room matches these filters.',
    reset: 'Show all',
  },
  reviewsPage: {
    title: 'Guest|*reviews*',
    sub: 'What guests have written since Bjarkalundur reopened in April 2026. Each review is quoted word for word, under the name of the person who wrote it.',
    translate: 'In English',
    original: 'Original',
    more: 'More reviews',
    google: 'On Google',
    tripadvisor: 'On Tripadvisor',
    photoNote: 'The photos are from the hotel and show what each review talks about.',
  },
  campsite: {
    eyebrow: 'Campsite',
    title: 'The campsite|*by the stream*',
    sub: 'A grass field by the stream right next to the hotel, a few steps from the restaurant.',
    introTitle: 'Camping|*below Vaðalfjöll*',
    body: [
      'The Bjarkalundur campsite is a grass field by the stream, right next to the hotel. Facilities include a building with toilets and showers, electricity and a playground for children.',
      'From your tent it is a short walk to the dining room, the path up Vaðalfjöll and the fishing on Berufjarðarvatn. The hotel also has a fuel station and an EV charging station.',
    ],
    pricesTitle: 'Prices',
    prices: [
      { k: 'Per person, per night', v: 'ISK 1,500' },
      { k: 'Electricity, per night', v: 'ISK 1,000' },
      { k: 'Shower, per minute', v: 'ISK 100' },
      { k: 'Children 12 and under', v: 'Free' },
    ],
    facilitiesTitle: 'On site',
    facilities: ['Toilet and shower block', 'Electricity', 'Playground for children', 'Restaurant in the hotel', 'Fuel and EV charging', 'Fishing in Berufjarðarvatn'],
    questions: 'Questions about the campsite?',
    season: 'The hotel and the campsite close for part of the winter.',
  },
  footer: {
    tagline: "Iceland's oldest summer hotel, at the foot of Vaðalfjöll.",
    season: 'Closed for part of the winter. Reopens in March.',
  },
}

export const COPY: Record<Lang, Copy> = { is, en }
export type NavItem = Copy['nav'][number]
