/**
 * Katrín Ísfeld — the "litheim" colour map.
 *
 * Her own homepage copy claims the site's colours are "ekki valdir úr
 * litakorti heldur teknar beint úr verkefnunum sjálfum" (not picked from a
 * palette, taken directly from the projects themselves). This script makes
 * that literally true: one average colour per photo, sampled from the real
 * source JPEG via ImageMagick's resize-to-1×1 trick, not invented.
 *
 *   node tools/katrin-colors.mjs
 */
import { readdirSync, writeFileSync } from 'node:fs'
import { execFileSync } from 'node:child_process'
import { join } from 'node:path'

const SRC = 'public/katrinisfeld'
const OUT_FILE = 'src/preview/katrinisfeld/photo-colors.ts'

const bySlug = new Map()
for (const f of readdirSync(SRC)) {
  const m = /^(.+)-(960|1920|2400)\.jpg$/.exec(f)
  if (!m) continue
  // prefer the largest source for sampling accuracy
  const rank = { '960': 0, '1920': 1, '2400': 2 }
  const prev = bySlug.get(m[1])
  if (!prev || rank[m[2]] > rank[prev.tier]) bySlug.set(m[1], { file: f, tier: m[2] })
}

/** HSL saturation + lightness, 0-1, from an 0-255 RGB triple. */
function hsl(r, g, b) {
  r /= 255; g /= 255; b /= 255
  const max = Math.max(r, g, b), min = Math.min(r, g, b)
  const l = (max + min) / 2
  if (max === min) return { s: 0, l }
  const d = max - min
  const s = l > 0.5 ? d / (2 - max - min) : d / (max + min)
  return { s, l }
}

const slugs = [...bySlug.keys()].sort()
const colors = {}
for (const slug of slugs) {
  // A flat average reads as mud (real rooms are mostly neutral surfaces).
  // Quantize to a small palette instead and pick the most SATURATED cluster
  // in a sane lightness range: that is the accent her own copy describes
  // ("vínrautt og kopar"), not the wall colour behind it.
  const out = execFileSync('magick', [
    join(SRC, bySlug.get(slug).file), '-resize', '300x300', '+dither', '-colors', '6', '-unique-colors', 'txt:-',
  ], { encoding: 'utf8' })
  const candidates = [...out.matchAll(/\((\d+),(\d+),(\d+)\)\s+#([0-9A-Fa-f]{6})/g)]
    .map((m) => ({ r: +m[1], g: +m[2], b: +m[3], hex: `#${m[4]}` }))
  let best = null
  for (const c of candidates) {
    const { s, l } = hsl(c.r, c.g, c.b)
    if (l < 0.12 || l > 0.88) continue // near-black/near-white, not an accent
    if (!best || s > best.s) best = { ...c, s }
  }
  if (!best) best = candidates[candidates.length - 1] // fallback: lightest cluster
  colors[slug] = best.hex
}

const body = `/* GENERATED by tools/katrin-colors.mjs — do not edit by hand.
 * The dominant ACCENT colour of each photo's real source file: quantized to
 * six clusters via ImageMagick, then the most saturated cluster in a sane
 * lightness range is kept (a flat pixel average reads as mud, since most of
 * any real room is neutral wall/floor/ceiling). This is the "litheim" data
 * referenced on the home page: the colour each project's own photography
 * actually is, not invented. */
export const PHOTO_COLORS: Record<string, string> = {
${slugs.map((s) => `  '${s}': '${colors[s]}',`).join('\n')}
}
`
writeFileSync(OUT_FILE, body)
console.log(`katrin-colors: ${slugs.length} photos sampled -> ${OUT_FILE}`)
