/**
 * Katrín Ísfeld — the responsive image pipeline.
 *
 * Her harvested portfolio arrived as 72 JPEGs (16 MB) in two arbitrary sizes
 * whose FILENAMES claim 1920/960 while the files are actually 1500/900. This
 * script stops guessing: it reads the real pixel dimensions out of each JPEG's
 * SOF marker, writes them into a checked-in map, and encodes AVIF + WebP at
 * three real widths from the largest source available.
 *
 * Why a dimension map at all: a srcset width descriptor is a PROMISE about how
 * much resolution a candidate holds, and img.naturalWidth reports the
 * DESCRIPTOR's view rather than the file's — so measuring in the browser
 * confirms a lie instead of catching it. The only honest read is the file.
 *
 *   node tools/katrin-images.mjs            # encode everything missing
 *   node tools/katrin-images.mjs --force    # re-encode from scratch
 */
import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync } from 'node:fs'
import { execFileSync } from 'node:child_process'
import { join } from 'node:path'

const SRC = 'public/katrinisfeld'
const OUT = 'public/katrinisfeld/rs'
const FORCE = process.argv.includes('--force')
const WIDTHS = [480, 900, 1500]

/** Real [width, height] from the JPEG SOF marker — no image library needed. */
function jpegSize(buf) {
  let i = 2
  while (i < buf.length) {
    if (buf[i] !== 0xff) { i++; continue }
    const marker = buf[i + 1]
    // SOF0..SOF15 except DHT(c4), JPG(c8), DAC(cc)
    if (marker >= 0xc0 && marker <= 0xcf && marker !== 0xc4 && marker !== 0xc8 && marker !== 0xcc) {
      return [buf.readUInt16BE(i + 7), buf.readUInt16BE(i + 5)]
    }
    i += 2 + buf.readUInt16BE(i + 2)
  }
  throw new Error('no SOF marker')
}

mkdirSync(OUT, { recursive: true })

/* Group the two derivatives of each photo and keep the larger as the source. */
const bySlug = new Map()
for (const f of readdirSync(SRC)) {
  const m = /^(.+)-(960|1920)\.jpg$/.exec(f)
  if (!m) continue
  const [w, h] = jpegSize(readFileSync(join(SRC, f)))
  const prev = bySlug.get(m[1])
  if (!prev || w > prev.w) bySlug.set(m[1], { file: f, w, h })
}

const slugs = [...bySlug.keys()].sort()
console.log(`katrin-images: ${slugs.length} photos, ${WIDTHS.length} widths × avif+webp`)

const map = {}
let encoded = 0, skipped = 0
for (const slug of slugs) {
  const { file, w: sw, h: sh } = bySlug.get(slug)
  const src = join(SRC, file)
  // never upscale: a 900px-wide source gets no 1500 variant
  const widths = WIDTHS.filter((w) => w <= sw)
  if (!widths.includes(sw) && widths[widths.length - 1] !== sw && sw < Math.max(...WIDTHS)) widths.push(sw)
  const variants = []
  for (const w of widths) {
    const h = Math.round((sh / sw) * w)
    const stem = join(OUT, `${slug}-${w}`)
    if (FORCE || !existsSync(`${stem}.avif`)) {
      // resize once into a temp PNG, then encode both formats from it
      const tmp = join(OUT, `.tmp-${slug}-${w}.png`)
      execFileSync('magick', [src, '-resize', `${w}x`, '-strip', tmp])
      execFileSync('avifenc', ['-q', '58', '-s', '6', '--jobs', '4', tmp, `${stem}.avif`], { stdio: 'ignore' })
      execFileSync('cwebp', ['-q', '76', '-m', '5', '-quiet', tmp, '-o', `${stem}.webp`], { stdio: 'ignore' })
      execFileSync('rm', ['-f', tmp])
      encoded++
    } else skipped++
    variants.push([w, h])
  }
  map[slug] = { w: sw, h: sh, v: variants, jpg: file }
  process.stdout.write(`\r  ${slug.padEnd(24)} ${sw}×${sh} → ${variants.map((v) => v[0]).join('/')}          `)
}
process.stdout.write('\n')

const lines = Object.keys(map).sort().map((k) => {
  const r = map[k]
  return `  '${k}': { w: ${r.w}, h: ${r.h}, v: [${r.v.map(([a, b]) => `[${a}, ${b}]`).join(', ')}], jpg: '${r.jpg}' },`
})
writeFileSync(
  'src/preview/katrinisfeld/photo-dims.ts',
  `/* GENERATED by tools/katrin-images.mjs — do not edit by hand.\n` +
    ` * Real pixel dimensions read from each JPEG's SOF marker, plus the widths\n` +
    ` * actually encoded. A srcset descriptor is a promise about resolution; these\n` +
    ` * are the only honest numbers, because img.naturalWidth reports the\n` +
    ` * DESCRIPTOR's view of a file rather than the file's own. */\n` +
    `export interface PhotoDims { w: number; h: number; v: Array<[number, number]>; jpg: string }\n` +
    `export const PHOTO_DIMS: Record<string, PhotoDims> = {\n${lines.join('\n')}\n}\n`,
)

/* Report the saving, because "we added AVIF" is not a measurement. */
const bytes = (dir, re) =>
  readdirSync(dir).filter((f) => re.test(f)).reduce((s, f) => s + readFileSync(join(dir, f)).length, 0)
const mb = (n) => (n / 1024 / 1024).toFixed(2) + ' MB'
console.log(`katrin-images: encoded ${encoded}, skipped ${skipped}`)
console.log(`  jpeg (old): ${mb(bytes(SRC, /\.jpg$/))}`)
console.log(`  webp      : ${mb(bytes(OUT, /\.webp$/))}`)
console.log(`  avif      : ${mb(bytes(OUT, /\.avif$/))}`)
