/* GENERATED by tools/katrin-colors.mjs — do not edit by hand.
 * The dominant ACCENT colour of each photo's real source file: quantized to
 * six clusters via ImageMagick, then the most saturated cluster in a sane
 * lightness range is kept (a flat pixel average reads as mud, since most of
 * any real room is neutral wall/floor/ceiling). This is the "litheim" data
 * referenced on the home page: the colour each project's own photography
 * actually is, not invented. */
export const PHOTO_COLORS: Record<string, string> = {
  'f-bitar': '#8E7054',
  'f-eldhus': '#403426',
  'f-eyja': '#4A3527',
  'f-krokur': '#B79C70',
  'f-stofa': '#5B4731',
  'p-alfheimar-0': '#927D6C',
  'p-alfheimar-1': '#8B7F75',
  'p-badherbergi-0': '#D4E5E6',
  'p-badherbergi-1': '#A69075',
  'p-barnaherbergi-0': '#956643',
  'p-eldhusrymi-0': '#CBC2B8',
  'p-eldhusrymi-1': '#464139',
  'p-freyja-0': '#507090',
  'p-freyja-1': '#708BA8',
  'p-freyjalux-0': '#2D2822',
  'p-freyjalux-1': '#463631',
  'p-gardabaer-0': '#E0D5CD',
  'p-oldcharm-1': '#D09957',
  'p-skandinaviskt-0': '#8D7258',
  'p-skandinaviskt-1': '#4A392B',
  'p-skrifstofa-0': '#926F64',
  'p-skrifstofa-1': '#A88A71',
  'p-skuggahverfi-0': '#9B8363',
  'p-skuggahverfi-1': '#987C53',
  'p-solvallagata-1': '#514139',
  'p-studio-0': '#96876B',
  'p-studio-1': '#837D7D',
  'p-svala-0': '#3E3D2F',
  'p-tannlaeknar-0': '#4D3E2B',
  's-arinn': '#9D8371',
  's-bad': '#4B3529',
  's-eldhus-vitt': '#483833',
  's-eyja': '#9DBEC9',
  's-fot': '#5E86AE',
  's-skapur': '#917157',
  's-sturta': '#90845E',
}
