/* GENERATED by tools/katrin-images.mjs — do not edit by hand.
 * Real pixel dimensions read from each JPEG's SOF marker, plus the widths
 * actually encoded. A srcset descriptor is a promise about resolution; these
 * are the only honest numbers, because img.naturalWidth reports the
 * DESCRIPTOR's view of a file rather than the file's own. */
export interface PhotoDims { w: number; h: number; v: Array<[number, number]>; jpg: string }
export const PHOTO_DIMS: Record<string, PhotoDims> = {
  'f-bitar': { w: 1125, h: 1500, v: [[480, 640], [900, 1200], [1125, 1500]], jpg: 'f-bitar-1920.jpg' },
  'f-eldhus': { w: 1500, h: 1125, v: [[480, 360], [900, 675], [1500, 1125]], jpg: 'f-eldhus-1920.jpg' },
  'f-eyja': { w: 1500, h: 1125, v: [[480, 360], [900, 675], [1500, 1125]], jpg: 'f-eyja-1920.jpg' },
  'f-krokur': { w: 1500, h: 1125, v: [[480, 360], [900, 675], [1500, 1125]], jpg: 'f-krokur-1920.jpg' },
  'f-stofa': { w: 1125, h: 1500, v: [[480, 640], [900, 1200], [1125, 1500]], jpg: 'f-stofa-1920.jpg' },
  'p-alfheimar-0': { w: 1500, h: 1273, v: [[480, 407], [900, 764], [1500, 1273]], jpg: 'p-alfheimar-0-1920.jpg' },
  'p-alfheimar-1': { w: 1500, h: 844, v: [[480, 270], [900, 506], [1500, 844]], jpg: 'p-alfheimar-1-1920.jpg' },
  'p-badherbergi-0': { w: 1125, h: 1500, v: [[480, 640], [900, 1200], [1125, 1500]], jpg: 'p-badherbergi-0-1920.jpg' },
  'p-badherbergi-1': { w: 1125, h: 1500, v: [[480, 640], [900, 1200], [1125, 1500]], jpg: 'p-badherbergi-1-1920.jpg' },
  'p-barnaherbergi-0': { w: 1500, h: 972, v: [[480, 311], [900, 583], [1500, 972]], jpg: 'p-barnaherbergi-0-1920.jpg' },
  'p-eldhusrymi-0': { w: 1000, h: 1500, v: [[480, 720], [900, 1350], [1000, 1500]], jpg: 'p-eldhusrymi-0-1920.jpg' },
  'p-eldhusrymi-1': { w: 1000, h: 1500, v: [[480, 720], [900, 1350], [1000, 1500]], jpg: 'p-eldhusrymi-1-1920.jpg' },
  'p-freyja-0': { w: 1500, h: 1000, v: [[480, 320], [900, 600], [1500, 1000]], jpg: 'p-freyja-0-1920.jpg' },
  'p-freyja-1': { w: 1500, h: 1000, v: [[480, 320], [900, 600], [1500, 1000]], jpg: 'p-freyja-1-1920.jpg' },
  'p-freyjalux-0': { w: 1500, h: 1500, v: [[480, 480], [900, 900], [1500, 1500]], jpg: 'p-freyjalux-0-1920.jpg' },
  'p-freyjalux-1': { w: 1500, h: 1500, v: [[480, 480], [900, 900], [1500, 1500]], jpg: 'p-freyjalux-1-1920.jpg' },
  'p-gardabaer-0': { w: 1500, h: 843, v: [[480, 270], [900, 506], [1500, 843]], jpg: 'p-gardabaer-0-1920.jpg' },
  'p-oldcharm-1': { w: 1500, h: 1192, v: [[480, 381], [900, 715], [1500, 1192]], jpg: 'p-oldcharm-1-1920.jpg' },
  'p-skandinaviskt-0': { w: 1000, h: 1500, v: [[480, 720], [900, 1350], [1000, 1500]], jpg: 'p-skandinaviskt-0-1920.jpg' },
  'p-skandinaviskt-1': { w: 1000, h: 1500, v: [[480, 720], [900, 1350], [1000, 1500]], jpg: 'p-skandinaviskt-1-1920.jpg' },
  'p-skrifstofa-0': { w: 1500, h: 1000, v: [[480, 320], [900, 600], [1500, 1000]], jpg: 'p-skrifstofa-0-1920.jpg' },
  'p-skrifstofa-1': { w: 1500, h: 1053, v: [[480, 337], [900, 632], [1500, 1053]], jpg: 'p-skrifstofa-1-1920.jpg' },
  'p-skuggahverfi-0': { w: 1500, h: 1000, v: [[480, 320], [900, 600], [1500, 1000]], jpg: 'p-skuggahverfi-0-1920.jpg' },
  'p-skuggahverfi-1': { w: 1000, h: 1500, v: [[480, 720], [900, 1350], [1000, 1500]], jpg: 'p-skuggahverfi-1-1920.jpg' },
  'p-solvallagata-1': { w: 843, h: 1500, v: [[480, 854], [843, 1500]], jpg: 'p-solvallagata-1-1920.jpg' },
  'p-studio-0': { w: 1500, h: 843, v: [[480, 270], [900, 506], [1500, 843]], jpg: 'p-studio-0-1920.jpg' },
  'p-studio-1': { w: 1000, h: 1500, v: [[480, 720], [900, 1350], [1000, 1500]], jpg: 'p-studio-1-1920.jpg' },
  'p-svala-0': { w: 1500, h: 1500, v: [[480, 480], [900, 900], [1500, 1500]], jpg: 'p-svala-0-1920.jpg' },
  'p-tannlaeknar-0': { w: 1500, h: 848, v: [[480, 271], [900, 509], [1500, 848]], jpg: 'p-tannlaeknar-0-1920.jpg' },
  's-arinn': { w: 1500, h: 1146, v: [[480, 367], [900, 688], [1500, 1146]], jpg: 's-arinn-1920.jpg' },
  's-bad': { w: 1500, h: 1125, v: [[480, 360], [900, 675], [1500, 1125]], jpg: 's-bad-1920.jpg' },
  's-eldhus-vitt': { w: 1500, h: 1125, v: [[480, 360], [900, 675], [1500, 1125]], jpg: 's-eldhus-vitt-1920.jpg' },
  's-eyja': { w: 1500, h: 1125, v: [[480, 360], [900, 675], [1500, 1125]], jpg: 's-eyja-1920.jpg' },
  's-fot': { w: 1500, h: 1160, v: [[480, 371], [900, 696], [1500, 1160]], jpg: 's-fot-1920.jpg' },
  's-skapur': { w: 1500, h: 1125, v: [[480, 360], [900, 675], [1500, 1125]], jpg: 's-skapur-1920.jpg' },
  's-sturta': { w: 1500, h: 1125, v: [[480, 360], [900, 675], [1500, 1125]], jpg: 's-sturta-1920.jpg' },
}
