/* GENERATED by tools/katrin-images.mjs — do not edit by hand.
 * Real pixel dimensions read from each JPEG's SOF marker, plus the widths
 * actually encoded. A srcset descriptor is a promise about resolution; these
 * are the only honest numbers, because img.naturalWidth reports the
 * DESCRIPTOR's view of a file rather than the file's own. */
export interface PhotoDims { w: number; h: number; v: Array<[number, number]>; jpg: string }
export const PHOTO_DIMS: Record<string, PhotoDims> = {
  'f-bitar': { w: 1800, h: 2400, v: [[480, 640], [900, 1200], [1500, 2000], [1800, 2400]], jpg: 'f-bitar-2400.jpg' },
  'f-eldhus': { w: 2400, h: 1800, v: [[480, 360], [900, 675], [1500, 1125]], jpg: 'f-eldhus-2400.jpg' },
  'f-eyja': { w: 2400, h: 1800, v: [[480, 360], [900, 675], [1500, 1125]], jpg: 'f-eyja-2400.jpg' },
  'f-krokur': { w: 2400, h: 1800, v: [[480, 360], [900, 675], [1500, 1125]], jpg: 'f-krokur-2400.jpg' },
  'f-stofa': { w: 1800, h: 2400, v: [[480, 640], [900, 1200], [1500, 2000], [1800, 2400]], jpg: 'f-stofa-2400.jpg' },
  'p-alfheimar-0': { w: 2400, h: 2037, v: [[480, 407], [900, 764], [1500, 1273], [2400, 2037]], jpg: 'p-alfheimar-0-2400.jpg' },
  'p-alfheimar-1': { w: 2400, h: 1355, v: [[480, 271], [900, 508], [1500, 847]], jpg: 'p-alfheimar-1-2400.jpg' },
  'p-badherbergi-0': { w: 1800, h: 2400, v: [[480, 640], [900, 1200], [1500, 2000], [1800, 2400]], jpg: 'p-badherbergi-0-2400.jpg' },
  'p-badherbergi-1': { w: 1800, h: 2400, v: [[480, 640], [900, 1200], [1500, 2000], [1800, 2400]], jpg: 'p-badherbergi-1-2400.jpg' },
  'p-barnaherbergi-0': { w: 2400, h: 1557, v: [[480, 311], [900, 584], [1500, 973], [2400, 1557]], jpg: 'p-barnaherbergi-0-2400.jpg' },
  'p-eldhusrymi-0': { w: 1604, h: 2400, v: [[480, 718], [900, 1347], [1500, 2244], [1604, 2400]], jpg: 'p-eldhusrymi-0-2400.jpg' },
  'p-eldhusrymi-1': { w: 1604, h: 2400, v: [[480, 718], [900, 1347], [1500, 2244], [1604, 2400]], jpg: 'p-eldhusrymi-1-2400.jpg' },
  'p-freyja-0': { w: 2400, h: 1604, v: [[480, 321], [900, 602], [1500, 1003], [2400, 1604]], jpg: 'p-freyja-0-2400.jpg' },
  'p-freyja-1': { w: 2400, h: 1604, v: [[480, 321], [900, 602], [1500, 1003]], jpg: 'p-freyja-1-2400.jpg' },
  'p-freyjalux-0': { w: 2400, h: 2400, v: [[480, 480], [900, 900], [1500, 1500], [2400, 2400]], jpg: 'p-freyjalux-0-2400.jpg' },
  'p-freyjalux-1': { w: 2400, h: 2400, v: [[480, 480], [900, 900], [1500, 1500]], jpg: 'p-freyjalux-1-2400.jpg' },
  'p-gardabaer-0': { w: 2400, h: 1350, v: [[480, 270], [900, 506], [1500, 844], [2400, 1350]], jpg: 'p-gardabaer-0-2400.jpg' },
  'p-oldcharm-1': { w: 2400, h: 1917, v: [[480, 383], [900, 719], [1500, 1198], [2400, 1917]], jpg: 'p-oldcharm-1-2400.jpg' },
  'p-skandinaviskt-0': { w: 1604, h: 2400, v: [[480, 718], [900, 1347], [1500, 2244], [1604, 2400]], jpg: 'p-skandinaviskt-0-2400.jpg' },
  'p-skandinaviskt-1': { w: 1604, h: 2400, v: [[480, 718], [900, 1347], [1500, 2244], [1604, 2400]], jpg: 'p-skandinaviskt-1-2400.jpg' },
  'p-skrifstofa-0': { w: 2400, h: 1604, v: [[480, 321], [900, 602], [1500, 1003], [2400, 1604]], jpg: 'p-skrifstofa-0-2400.jpg' },
  'p-skrifstofa-1': { w: 2400, h: 1688, v: [[480, 338], [900, 633], [1500, 1055]], jpg: 'p-skrifstofa-1-2400.jpg' },
  'p-skuggahverfi-0': { w: 2400, h: 1604, v: [[480, 321], [900, 602], [1500, 1003], [2400, 1604]], jpg: 'p-skuggahverfi-0-2400.jpg' },
  'p-skuggahverfi-1': { w: 1604, h: 2400, v: [[480, 718], [900, 1347], [1500, 2244], [1604, 2400]], jpg: 'p-skuggahverfi-1-2400.jpg' },
  'p-solvallagata-1': { w: 1350, h: 2400, v: [[480, 853], [900, 1600], [1350, 2400]], jpg: 'p-solvallagata-1-2400.jpg' },
  'p-studio-0': { w: 2400, h: 1350, v: [[480, 270], [900, 506], [1500, 844]], jpg: 'p-studio-0-2400.jpg' },
  'p-studio-1': { w: 1604, h: 2400, v: [[480, 718], [900, 1347], [1500, 2244], [1604, 2400]], jpg: 'p-studio-1-2400.jpg' },
  'p-svala-0': { w: 2400, h: 2400, v: [[480, 480], [900, 900], [1500, 1500], [2400, 2400]], jpg: 'p-svala-0-2400.jpg' },
  'p-tannlaeknar-0': { w: 2400, h: 1361, v: [[480, 272], [900, 510], [1500, 851], [2400, 1361]], jpg: 'p-tannlaeknar-0-2400.jpg' },
  's-arinn': { w: 2400, h: 1840, v: [[480, 368], [900, 690], [1500, 1150]], jpg: 's-arinn-2400.jpg' },
  's-bad': { w: 2400, h: 1800, v: [[480, 360], [900, 675], [1500, 1125]], jpg: 's-bad-2400.jpg' },
  's-eldhus-vitt': { w: 2400, h: 1800, v: [[480, 360], [900, 675], [1500, 1125], [2400, 1800]], jpg: 's-eldhus-vitt-2400.jpg' },
  's-eyja': { w: 2400, h: 1800, v: [[480, 360], [900, 675], [1500, 1125]], jpg: 's-eyja-2400.jpg' },
  's-fot': { w: 2400, h: 1862, v: [[480, 372], [900, 698], [1500, 1164]], jpg: 's-fot-2400.jpg' },
  's-skapur': { w: 2400, h: 1800, v: [[480, 360], [900, 675], [1500, 1125]], jpg: 's-skapur-2400.jpg' },
  's-sturta': { w: 2400, h: 1800, v: [[480, 360], [900, 675], [1500, 1125], [2400, 1800]], jpg: 's-sturta-2400.jpg' },
}
