/* GENERATED by tools/katrin-colors.mjs — do not edit by hand.
 * The dominant ACCENT colour of each photo's real source file: quantized to
 * six clusters via ImageMagick, then the most saturated cluster in a sane
 * lightness range is kept (a flat pixel average reads as mud, since most of
 * any real room is neutral wall/floor/ceiling). This is the "litheim" data
 * referenced on the home page: the colour each project's own photography
 * actually is, not invented. */
export const PHOTO_COLORS: Record<string, string> = {
  'f-bitar': '#8E7054',
  'f-eldhus': '#57432F',
  'f-eyja': '#4A3527',
  'f-krokur': '#B89C70',
  'f-stofa': '#5B4631',
  'p-alfheimar-0': '#927D6C',
  'p-alfheimar-1': '#8C8075',
  'p-badherbergi-0': '#D3E5E6',
  'p-badherbergi-1': '#A79175',
  'p-barnaherbergi-0': '#946744',
  'p-eldhusrymi-0': '#CBC1B8',
  'p-eldhusrymi-1': '#464039',
  'p-freyja-0': '#517090',
  'p-freyja-1': '#708CA8',
  'p-freyjalux-0': '#2E2822',
  'p-freyjalux-1': '#463531',
  'p-gardabaer-0': '#E0D5CD',
  'p-oldcharm-1': '#D09957',
  'p-skandinaviskt-0': '#8D7258',
  'p-skandinaviskt-1': '#4A3A2C',
  'p-skrifstofa-0': '#936E64',
  'p-skrifstofa-1': '#A7896F',
  'p-skuggahverfi-0': '#9B8363',
  'p-skuggahverfi-1': '#987C54',
  'p-solvallagata-1': '#514139',
  'p-studio-0': '#97896B',
  'p-studio-1': '#837C7D',
  'p-svala-0': '#3E3D2F',
  'p-tannlaeknar-0': '#4D3D2B',
  's-arinn': '#9E8270',
  's-bad': '#4B3429',
  's-eldhus-vitt': '#483733',
  's-eyja': '#9CBDC9',
  's-fot': '#5D86AD',
  's-skapur': '#917259',
  's-sturta': '#90845E',
}
