/* generated by _docs/sambo-build-2026-10-03/tools/gen_assets.py: do not edit */
export interface AssetInfo { pack?: [number, number]; open?: [number, number]; macros: [number, number][]; ing?: [number, number]; nfEu?: [number, number]; nfUs?: [number, number]; tint?: string }
export const ASSETS: Record<string, AssetInfo> = {
 "bananastangir": {
  "pack": [
   786,
   1100
  ],
  "open": [
   803,
   1100
  ],
  "macros": [
   [
    1400,
    2100
   ],
   [
    1499,
    2100
   ]
  ],
  "tint": "#dcc305"
 },
 "froskar": {
  "pack": [
   752,
   1100
  ],
  "open": [
   808,
   1100
  ],
  "macros": [
   [
    1500,
    2099
   ],
   [
    1500,
    2099
   ],
   [
    1500,
    2099
   ]
  ],
  "ing": [
   1152,
   686
  ],
  "nfEu": [
   1100,
   691
  ],
  "nfUs": [
   900,
   1311
  ],
  "tint": "#a2bc0e"
 },
 "gammeldags-lakkris": {
  "pack": [
   858,
   1100
  ],
  "open": [
   660,
   1100
  ],
  "macros": [
   [
    1500,
    2099
   ],
   [
    1500,
    2100
   ],
   [
    1500,
    2099
   ]
  ],
  "nfEu": [
   1100,
   691
  ],
  "nfUs": [
   900,
   1311
  ],
  "tint": "#5b5e7a"
 },
 "kaerleikstre": {
  "pack": [
   735,
   1100
  ],
  "macros": [
   [
    1400,
    2100
   ]
  ],
  "tint": "#ba3325"
 },
 "kokosbollur": {
  "pack": [
   1000,
   532
  ],
  "macros": [
   [
    1500,
    1249
   ]
  ],
  "ing": [
   1156,
   648
  ],
  "nfEu": [
   1100,
   691
  ],
  "nfUs": [
   900,
   1311
  ],
  "tint": "#ead301"
 },
 "kremrulla": {
  "pack": [
   1000,
   1370
  ],
  "macros": [
   [
    1400,
    2100
   ],
   [
    1500,
    2099
   ],
   [
    1500,
    2099
   ]
  ],
  "ing": [
   1154,
   686
  ],
  "nfEu": [
   1100,
   691
  ],
  "nfUs": [
   900,
   1311
  ],
  "tint": "#c85275"
 },
 "kulusukk": {
  "pack": [
   816,
   1100
  ],
  "open": [
   697,
   1100
  ],
  "macros": [
   [
    1500,
    2099
   ],
   [
    1500,
    2099
   ],
   [
    1500,
    2099
   ]
  ],
  "ing": [
   1150,
   860
  ],
  "nfEu": [
   1100,
   691
  ],
  "nfUs": [
   900,
   1311
  ],
  "tint": "#941ea0"
 },
 "lakkriskonfekt": {
  "pack": [
   707,
   1100
  ],
  "open": [
   713,
   1100
  ],
  "macros": [
   [
    1500,
    2099
   ],
   [
    1500,
    2099
   ],
   [
    1500,
    2099
   ]
  ],
  "ing": [
   1156,
   690
  ],
  "nfEu": [
   1100,
   691
  ],
  "nfUs": [
   900,
   1311
  ],
  "tint": "#c92509"
 },
 "lakkrisreimar": {
  "pack": [
   1000,
   301
  ],
  "open": [
   774,
   1100
  ],
  "macros": [
   [
    1500,
    2099
   ],
   [
    1500,
    2100
   ]
  ],
  "ing": [
   1152,
   582
  ],
  "nfEu": [
   1100,
   691
  ],
  "nfUs": [
   900,
   1311
  ],
  "tint": "#91726b"
 },
 "olsen-olsen": {
  "pack": [
   927,
   229
  ],
  "open": [
   359,
   1100
  ],
  "macros": [
   [
    1500,
    2099
   ],
   [
    1500,
    2099
   ],
   [
    1500,
    2099
   ]
  ],
  "ing": [
   1152,
   798
  ],
  "nfEu": [
   1100,
   691
  ],
  "nfUs": [
   900,
   1311
  ],
  "tint": "#da6a0b"
 },
 "paskaboltinn": {
  "pack": [
   1000,
   852
  ],
  "macros": [
   [
    1500,
    1613
   ]
  ],
  "tint": "#e5b242"
 },
 "paskaegg": {
  "pack": [
   1000,
   1467
  ],
  "open": [
   764,
   1500
  ],
  "macros": [],
  "tint": "#e8b51c"
 },
 "saela": {
  "pack": [
   817,
   224
  ],
  "macros": [
   [
    1500,
    2099
   ],
   [
    1500,
    2099
   ],
   [
    1500,
    2099
   ]
  ],
  "ing": [
   1142,
   712
  ],
  "nfEu": [
   1100,
   691
  ],
  "nfUs": [
   900,
   1311
  ],
  "tint": "#cb1e2b"
 },
 "sexa-buff": {
  "macros": [
   [
    1500,
    2099
   ],
   [
    1499,
    2100
   ],
   [
    1500,
    2100
   ],
   [
    1500,
    2099
   ]
  ],
  "ing": [
   1150,
   676
  ],
  "nfEu": [
   521,
   335
  ],
  "nfUs": [
   900,
   1311
  ]
 },
 "snjoboltar": {
  "pack": [
   903,
   1078
  ],
  "open": [
   824,
   1100
  ],
  "macros": [
   [
    1500,
    2099
   ],
   [
    1400,
    2100
   ],
   [
    1500,
    2099
   ]
  ],
  "ing": [
   1152,
   866
  ],
  "nfEu": [
   1100,
   691
  ],
  "nfUs": [
   900,
   1311
  ],
  "tint": "#bcb8c2"
 },
 "sport-lakkris": {
  "pack": [
   822,
   1100
  ],
  "open": [
   711,
   1100
  ],
  "macros": [
   [
    1500,
    2099
   ],
   [
    1500,
    2099
   ],
   [
    1500,
    2100
   ]
  ],
  "ing": [
   1154,
   750
  ],
  "nfEu": [
   1100,
   691
  ],
  "nfUs": [
   900,
   1311
  ],
  "tint": "#ca361f"
 },
 "superboltar": {
  "pack": [
   913,
   1100
  ],
  "open": [
   887,
   1100
  ],
  "macros": [
   [
    1500,
    2099
   ],
   [
    1500,
    2099
   ]
  ],
  "ing": [
   1148,
   1256
  ],
  "nfEu": [
   1100,
   691
  ],
  "nfUs": [
   900,
   1311
  ],
  "tint": "#a58d76"
 },
 "thrista-paskaegg": {
  "pack": [
   763,
   1100
  ],
  "macros": [
   [
    1500,
    1779
   ],
   [
    1500,
    2022
   ]
  ],
  "tint": "#b19938"
 },
 "thrista-stubbar": {
  "pack": [
   704,
   917
  ],
  "macros": [
   [
    1400,
    2100
   ]
  ],
  "tint": "#cac3c3"
 },
 "thristakulur": {
  "pack": [
   885,
   1045
  ],
  "open": [
   669,
   1100
  ],
  "macros": [
   [
    1500,
    2099
   ]
  ],
  "ing": [
   1150,
   1262
  ],
  "nfEu": [
   1100,
   691
  ],
  "nfUs": [
   900,
   1311
  ],
  "tint": "#b7ad6e"
 },
 "thristur": {
  "pack": [
   831,
   1100
  ],
  "open": [
   700,
   1100
  ],
  "macros": [
   [
    1500,
    2099
   ],
   [
    1500,
    2099
   ],
   [
    1500,
    2099
   ]
  ],
  "ing": [
   1152,
   762
  ],
  "nfEu": [
   1100,
   691
  ],
  "nfUs": [
   900,
   1311
  ],
  "tint": "#f29902"
 },
 "thristur-stong": {
  "pack": [
   1000,
   395
  ],
  "open": [
   229,
   1100
  ],
  "macros": [
   [
    1500,
    2099
   ],
   [
    1500,
    2099
   ],
   [
    1500,
    2099
   ]
  ],
  "ing": [
   1152,
   762
  ],
  "nfEu": [
   1100,
   691
  ],
  "nfUs": [
   900,
   1311
  ],
  "tint": "#f9de01"
 },
 "thristur-travel": {
  "pack": [
   976,
   922
  ],
  "macros": [
   [
    1500,
    2099
   ]
  ],
  "tint": "#fc3d1d"
 }
}
